### ISSUE TITLE
希望在使用的时候加入一些可选参数而非一开始设置好

### ISSUE THREAD

**Issue by Jiaheliu137** [RockChinQ/QChatGPT#101]
希望在使用的时候加入一些可选参数而非一开始设置好：比如说，希望可以在输入的时候通过命令控制理性值temperature，符合程度值top_p,图片尺寸size等；如果输入的时候没有这些，再参考默认的配置文件

**Comment by RockChinQ** [comment]
这样会在一定程度上增加使用难度，不会添加进主线，可以自行编写插件实现此功能
