### ISSUE TITLE
[BUG]!update命令无法使用，centos7环境中的docker用issues77无法解决

### ISSUE THREAD

**Issue by HackerBG** [RockChinQ/QChatGPT#104]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    例如： Centos 7 64

**描述漏洞**  
!update和!version指令无法使用，提示dulwich模块未安装，实际已经根据issues77解决方案安装dulwich模块，仍无法解决，重启服务器也是无法解决。

**完整报错信息**  
![image](https://user-images.githubusercontent.com/68801102/213062378-b543b963-5412-4f55-8ef5-658b5e4c8d34.png)
![image](https://user-images.githubusercontent.com/68801102/213062670-8d32db8b-e57c-4f05-a360-27cf50d99e35.png)

**Comment by RockChinQ** [comment]
docker每次启动会还原文件，请使用本仓库提到的其他方式重新部署此程序

**Comment by HackerBG** [comment]
好的谢谢
