### ISSUE TITLE
[ENHANCE]如何后台运行？用vps部署，每次关闭ssh就会终止程序，mirai可以后台运行目前，但是不知道py程序如何后台运行

### ISSUE THREAD

**Issue by lzyq0912** [RockChinQ/QChatGPT#105]
不是需求建议请勿填写此模板！！！！
如题，请教如何能够后台运行，并且断开ssh不会关闭进程

**Comment by RockChinQ** [comment]
Linux下用screen指令

**Comment by lzyq0912** [comment]
> Linux下用screen指令

好的，谢谢，我会尝试一下，还有就是我使用机器人时询问某商品价格之后，对应的qq就被冻结了（涉及诈骗），是否是不能出现价格相关字眼，如果是的话感觉可以考虑添加敏感词

**Comment by RockChinQ** [comment]
> > Linux下用screen指令
> 
> 好的，谢谢，我会尝试一下，还有就是我使用机器人时询问某商品价格之后，对应的qq就被冻结了（涉及诈骗），是否是不能出现价格相关字眼，如果是的话感觉可以考虑添加敏感词

目前我没有遇到这种情况，建议你不要使用新开QQ号，不要频繁加好友、加群，减少敏感内容交流；同时你可以在sensitive.json中编辑要过滤的敏感词，使用方法见本仓库Wiki：功能使用页

**Comment by RockChinQ** [comment]
> > > > Linux下用screen指令
> > > 
> > > 
> > > 好的，谢谢，我会尝试一下，还有就是我使用机器人时询问某商品价格之后，对应的qq就被冻结了（涉及诈骗），是否是不能出现价格相关字眼，如果是的话感觉可以考虑添加敏感词
> > 
> > 目前我没有遇到这种情况，建议你不要使用新开QQ号，不要频繁加好友、加群，减少敏感内容交流；同时你可以在sensitive.json中编辑要过滤的敏感词，使用方法见本仓库Wiki：功能使用页
> 
> 可能确实是因为新开qq号的缘故？我这个号确实是新开的，加了两个好友，一个自己一个朋友

提醒注意风控，mirai毕竟是逆向工程
