### ISSUE TITLE
反馈: mirai正常登陆可接受消息,启动主程序提示 IndexError    无法和chatgpt互动 

### ISSUE THREAD

**Issue by LiamWang2** [RockChinQ/QChatGPT#111]
**运行环境**
- 部署方式：
  Docker
- 系统环境：
    ubuntu 22.04-amd64-server-20221206

**描述漏洞**  
mirai正常工作 主程序报错
**完整报错信息**  
![image](https://user-images.githubusercontent.com/97073752/215693491-1a4eb4d9-330b-49bd-9a4a-06741969ac61.png)

![image](https://user-images.githubusercontent.com/97073752/215693022-34bbbb32-4700-4a72-a782-4c5f6fa72e85.png)

**Comment by RockChinQ** [comment]
发一下config.py最后的help_message字段及之后的内容

**Comment by LiamWang2** [comment]
感谢您如此迅速的回复

请问是这里吗?
![image](https://user-images.githubusercontent.com/97073752/215927324-4a8e1cd8-514a-458a-8813-c5de48613655.png)

**Comment by RockChinQ** [comment]
把79行中的`{20}`改成`{}`
