### ISSUE TITLE
[BUG]配置好机器人且成功登录后后台与qq均无消息回复

### ISSUE THREAD

**Issue by ariaxo** [RockChinQ/QChatGPT#114]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    win64
- Python环境（仅手动部署填写）：
    

**描述漏洞**  
配置好机器人且成功登录后后台与qq均无消息回复

**完整报错信息**  

> 2023-02-03 15:08:39 - INFO     [WebSocket] 成功登录到账号730803613。
> [2023-02-03 15:08:39.949] websocket.py (194) - [INFO] : [WebSocket] 成功登录到账号730803613。
> 2023-02-03 15:08:39 - INFO     [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
> [2023-02-03 15:08:39.949] websocket.py (250) - [INFO] : [WebSocket] 机器人开始运行。按 Ctrl + C 停止。
> [2023-02-03 15:08:49.811] main.py (193) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息, 请查看 https://github.com/RockChinQ/QChatGPT/issues/37
> [2023-02-03 15:08:56.662] main.py (206) - [INFO] : 当前已是最新版本

![D 38{1H{@6G)`~ _` {_( L](https://user-images.githubusercontent.com/97863000/216542227-364359e3-230f-4f36-8aa0-d166c7e96296.png)

**Comment by RockChinQ** [comment]
1. 检查命令行窗口是否处于“选择”状态，这会导致程序暂停  
2. 查看mirai控制台是否输出收到的消息

**Comment by ariaxo** [comment]
> 1. 检查命令行窗口是否处于“选择”状态，这会导致程序暂停
> 2. 查看mirai控制台是否输出收到的消息

1. 不在选择状态
![TS75LIKCM%G J$YXC3Z~O2](https://user-images.githubusercontent.com/97863000/216545416-ea18e7fc-9d01-4200-b7f1-77780a6dd6cf.png)


2. mirai控制台可以输出收到的消息

**Comment by ariaxo** [comment]
另：这个bot有接chatlearning，不知道有没有关系:(

**Comment by ariaxo** [comment]
不知道为什么解决了。。。。。。。感谢！

**Comment by ShinoKana** [comment]
请问机器人运行了，显示登陆成功，能收到输出的消息，但是不回复是什么情况？

**Comment by elsyia-2** [comment]
我发现我每次修改完config文件机器人就不回复了，但是登录加载什么的都是正常顺利的

**Comment by KaerMorh** [comment]
同上问题

**Comment by Chinesespeople** [comment]
你们里面配代理都是这么配的，我是机场链接

**Comment by Chinesespeople** [comment]
@ariaxo 你是咋解决的，我这一直不回信息

**Comment by Chinesespeople** [comment]
> 不知道为什么解决了。。。。。。。感谢！

你是咋解决的，我这一直不回信息

**Comment by RockChinQ** [comment]
目前估计只能重启，或者去 github.com/mamoe/mirai/issues 搜索解决办法，将在`v2.4.0`接入`gocq-http`，请持续关注。

**Comment by RockChinQ** [comment]
近期将通过NoneBot2框架接入go-cqhttp，请关注 #423
