### ISSUE TITLE
[BUG]聊天問題

### ISSUE THREAD

**Issue by huaji55** [RockChinQ/QChatGPT#117]
您好，已完成所有动作，请问如何找出机器人并与其开始对话呢，看好友列表没有机器人

**Comment by RockChinQ** [comment]
> 您好，已完成所有动作，请问如何找出机器人并与其开始对话呢，看好友列表没有机器人
> 

估计是你使用个人账号登录了程序，你自己的账号变成了机器人，建议换个小号来登录机器人程序

**Comment by huaji55** [comment]
对的，发现原因了...另外想问新的open ai 帐户仍然说API调用额度超额是甚么原因呢

**Comment by RockChinQ** [comment]
> 对的，发现原因了...另外想问新的open ai 帐户仍然说API调用额度超额是甚么原因呢

超额？是自己手动注册的账号吗？

**Comment by huaji55** [comment]
是的

**Comment by RockChinQ** [comment]
> 是的

自己注册的账号不应该出现超额问题，请前往官网查看账号免费额度

**Comment by huaji55** [comment]
是的，帳號有18元美金，4月1日過期....

**Comment by RockChinQ** [comment]
> 是的，帳號有18元美金，4月1日過期....

请贴上超额时的聊天窗口截图、控制台输出截图以及`config.py`中apikey的截图，**注意打码apikey部分内容，避免泄露**

**Comment by huaji55** [comment]
您好，
![3](https://user-images.githubusercontent.com/61001780/216925562-afbe7277-1da7-47d4-ba63-580d4b06931b.jpg)
![2](https://user-images.githubusercontent.com/61001780/216925566-e1463f52-075f-4728-93fa-b98da8a1aa55.png)
![1](https://user-images.githubusercontent.com/61001780/216925569-2554e6a2-a548-485d-8e44-e4307d66181a.png)

**Comment by RockChinQ** [comment]
问题已解决，key填写错误

**Comment by huaji55** [comment]
謝謝大佬解決!

**Comment by Mr-yf-shui** [comment]
> 是的，帳號有18元美金，4月1日過期....

在哪里看余额啊……

**Comment by RockChinQ** [comment]
到 https://platform.openai.com 登录你的账号，点击右上角`view account`，在下一个界面点击左侧的`usage`即可查看额度

<img width="1368" alt="image" src="https://github.com/RockChinQ/QChatGPT/assets/45992437/2665405c-0b80-4428-8d9c-660915abe2b9">

**Comment by Mr-yf-shui** [comment]
就这里怪怪的
![image](https://github.com/RockChinQ/QChatGPT/assets/129752220/e99bca5a-3b5a-4936-9295-2114c430c43f)

**Comment by RockChinQ** [comment]
> 就这里怪怪的 ![image](https://user-images.githubusercontent.com/129752220/246584154-e99bca5a-3b5a-4936-9295-2114c430c43f.png)

那就是没有额度，自行查找解决办法
