### ISSUE TITLE
大佬，能否支持在replit上部署？

### ISSUE THREAD

**Issue by drw2005** [RockChinQ/QChatGPT#118]
免费的(https://replit.com/ )主机很好用，大佬能不能支持一下部署在上面。
我尝试安装时老是报错。

**Comment by RockChinQ** [comment]
我得花时间研究一下，毕竟我没了解过这个平台。你可以贴上你的报错信息截图，越详细越好，也许可以帮助你定位问题原因。

**Comment by RockChinQ** [comment]
由于此项目运行需要同时运行mirai和主程序，进程较多，暂时不会考虑支持代码托管平台，请自行研究部署
