### ISSUE TITLE
[BUG]The server had an error while processing your request. Sorry about that!

### ISSUE THREAD

**Issue by CastleYu** [RockChinQ/QChatGPT#126]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：自动部署
- 系统环境：Windows 10

**描述漏洞**  
会话过程中，偶尔回复`[bot]err:RateLimitError,请重试或联系作者，或等待修复`

**完整报错信息**  
* main.py运行报错
```
util.py (67) - [INFO] : error_code=None error_message='The server had an error while processing your request. Sorry about that!' error_param=None error_type=server_error message='OpenAI API error received' stream_error=False
```
* 管理员收到消息
`[bot]会话调用API失败:The server had an error while processing your request. Sorry about that!`

（是否是openai那边的问题或者是我本地网络问题？

**Comment by RockChinQ** [comment]
openai接口问题，最近接口都不稳定，可以将程序升级到最新版本，最新版本支持在发生此错误时自动重试，降低报警率

**Comment by CastleYu** [comment]
> openai接口问题，最近接口都不稳定，可以将程序升级到最新版本，最新版本支持在发生此错误时自动重试，降低报警率

好的，感谢！
