### ISSUE TITLE
有使用QQ会提示违规的案例吗

### ISSUE THREAD

**Issue by Rwindest168888** [RockChinQ/QChatGPT#132]
我昨天接入半天，提示违规，有可能是问了不好的问题，给TX检测了，还是异常登录不允许使用机器人了，VX最近几天是不能用了。

**Comment by RockChinQ** [comment]
违规提示是在哪显示的？聊天窗提示警告可以忽略，QQ机器人很多风险的，毕竟操作QQ用的不是腾讯官方的接口，而是逆向工程的接口，请自行控制风险：降低加好友频率、在sensitive.json中添加更多敏感词以降低风险、退出不需要的群、降低加群频率、减少异地登录等。

**Comment by Rwindest168888** [comment]
> 违规提示是在哪显示的？聊天窗提示警告可以忽略，QQ机器人很多风险的，毕竟操作QQ用的不是腾讯官方的接口，而是逆向工程的接口，请自行控制风险：降低加好友频率、在sensitive.json中添加更多敏感词以降低风险、退出不需要的群、降低加群频率、减少异地登录等。

是直接让我的号下线了，然后提示违规，叫我自己检查是不是异常登录，几个勾让我打，写保证差不多的，然后解了。我注意点再试下吧，谢谢了。
