### ISSUE TITLE
[ENHANCE]可通过命令来让机器人自动切换不同的人格，即切换不同的default_prompt

### ISSUE THREAD

**Issue by HualuozhE** [RockChinQ/QChatGPT#135]
可通过命令来让机器人自动切换不同的人格，即切换不同的default_prompt；

具体的说，default_prompt配置项可以配置多种人格，即key-value形式配置，默认第一条为默认人格

通过QQ群@或QQ私聊关键字-key，给不同用户切换到不同的机器人人格，从而让多个使用者可以根据需要来切换到自己喜欢用的人格进行使用，并且default_prompt配置项中如果只具有一条人格或为空，则默认禁用切换人格的功能

主要是由于prompt_submit_length限制导致手动使用魔法指令后，一段时间后，因为上下文超过限制而导致机器人记忆丢失，又需要重新使用魔法指令，非常麻烦

**Comment by RockChinQ** [comment]
非常好的点子

**Comment by RockChinQ** [comment]
现已更新此功能，请更新主程序，并查看`config-template.py`中default_prompt字段的注释以了解如何设置多个情景（注意：请将修改写到config.py中)；并前往[wiki指令](https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%8C%87%E4%BB%A4) 查看如何通过 `!reset` `!default`指令控制和使用此功能。
