### ISSUE TITLE
用了几天，同一个Q号出现版本过低，删了mirai\bots也不行？

### ISSUE THREAD

**Issue by Rwindest168888** [RockChinQ/QChatGPT#137]
![image](https://user-images.githubusercontent.com/124567966/218280137-23c29166-e519-46ba-8eab-0397b5f11aed.png)

**Comment by RockChinQ** [comment]
版本过低或网络连接中报错解决办法如下：   
**以下操作均要求先关闭mirai**  

1. 删除mirai/bots/目录，重启mirai后重新登录机器人QQ
2. 删除mirai/bots目录，前往`mirai/config/Console/`目录编辑`AutoLogin.yml`（若未设置自动登录，请先按照文件内注释填写机器人账号自动登录信息），修改对应账号的协议为其他协议（自行参考文件内注释，建议修改为`IPAD` `ANDROID_PAD` `MACOS`等不常用协议），重启mirai进行登录
3. 更换机器人QQ号

**Comment by 24779987** [comment]
autologin add <机器人QQ号> <机器人密码>
autologin setConfig <机器人QQ号> protocol ANDROID_WATCH

**Comment by Rwindest168888** [comment]
> 版本过低或网络连接中报错解决办法如下： **以下操作均要求先关闭mirai**
> 
> 1. 删除mirai/bots/目录，重启mirai后重新登录机器人QQ
> 2. 删除mirai/bots目录，前往`mirai/config/Console/`目录编辑`AutoLogin.yml`（若未设置自动登录，请先按照文件内注释填写机器人账号自动登录信息），修改对应账号的协议为其他协议（自行参考文件内注释，建议修改为`IPAD` `ANDROID_PAD` `MACOS`等不常用协议），重启mirai进行登录
> 3. 更换机器人QQ号
改了协议可以了，谢谢大佬

**Comment by KimiFT** [comment]
又出现了新的问题，我协议是改好了，但是输入验证码无限卡在网络不稳定

**Comment by RockChinQ** [comment]
> 又出现了新的问题，我协议是改好了，但是输入验证码无限卡在网络不稳定
> ![Q7874](https://user-images.githubusercontent.com/43104582/218805051-8b9cb8f5-3ea5-4465-8210-b55376e0b9a1.png)
> 就是无轮重开多少次，删掉多少次bots，都会卡在这里

请根据上述步骤更改协议重试，注意每次更改前请关闭mirai并再次删除bots/目录

**Comment by Moshiluo** [comment]
同样出现了网络不稳定登陆失败的提示

**Comment by Moshiluo** [comment]
> 

我也有这个问题，并且按照你所说的这个全部试了一遍确实登录不上，但是换了其他的qq就没有了这个问题

**Comment by ruruamour** [comment]
关于尝试Issues所有方法仍无法登录的情况可以试试我成功这个思路：
1.删除bots下账号文件，修改登录协议，配置好自动登录，重启mirai
2.手机官方客户端登录QQ，账号安全>登录设备管理>开启陌生设备登录保护，删除所有设备，这时候会退出登录
3,mirai登录，出现要求验证码的提示
mirai版本2.14 协议ANDROID_WATCH

**Comment by adminluluxiu** [comment]
其实还有一个办法，mirai论坛上的解决方案是用真实的设备生成"device.json"，然后替换掉mirai"bot"文件夹里的"device.json"，再选择自动登录，对应协议对应账号，这样就可以避免被风控。但是如果是已经被风控的号，可能不行，在手机端生成的时候也可能会跳235或者237，这样没法生成也替换不了。

mirai论坛解决方案:
https://mirai.mamoe.net/topic/223/%E6%97%A0%E6%B3%95%E7%99%BB%E5%BD%95%E7%9A%84%E4%B8%B4%E6%97%B6%E5%A4%84%E7%90%86%E6%96%B9%E6%A1%88?lang=zh-CN

如果已经被风控了可以尝试修改密码，删除登录设备，重新开启保护，和上面的方法一样，就是登录这里变成了替换bot文件，而不是验证登录。

**Comment by RockChinQ** [comment]
此问题统一解法 #285
