### ISSUE TITLE
[BUG]无法连接到 mirai。

### ISSUE THREAD

**Issue by Ren-Boo** [RockChinQ/QChatGPT#138]
**运行环境**
- 部署方式：
    自动部署/手动部署，都试了
- 系统环境：
    例如： Win x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
运行run-mirai.bat，不关闭窗口，接着运行run-bot.bat，会这样提示
![0R4B8B`_M~T5B_D(}RQ_Q J](https://user-images.githubusercontent.com/63947664/218301275-40401233-79b4-4c69-9596-5c9c2a7c5581.png)

运行run-mirai.bat，关闭窗口，接着运行run-bot.bat，会这样提示
![image](https://user-images.githubusercontent.com/63947664/218301374-5250e1ae-14b6-4e35-b398-b2d65fcccc27.png)

端口状态是这样的
![image](https://user-images.githubusercontent.com/63947664/218301422-a16bc76f-6c60-49db-9d3d-6c268e3a67e2.png)

**Comment by Ren-Boo** [comment]
> **运行环境**
> 
> * 部署方式：
>   自动部署/手动部署，都试了
> * 系统环境：
>   例如： Win x64
> * Python环境（仅手动部署填写）：
>   例如： Python 3.10.9
> 
> **描述漏洞** 运行run-mirai.bat，不关闭窗口，接着运行run-bot.bat，会这样提示 ![0R4B8B`_M~T5B_D(}RQ_Q J](https://user-images.githubusercontent.com/63947664/218301275-40401233-79b4-4c69-9596-5c9c2a7c5581.png)
> 
> 运行run-mirai.bat，关闭窗口，接着运行run-bot.bat，会这样提示 ![image](https://user-images.githubusercontent.com/63947664/218301374-5250e1ae-14b6-4e35-b398-b2d65fcccc27.png)
> 
> 端口状态是这样的 ![image](https://user-images.githubusercontent.com/63947664/218301422-a16bc76f-6c60-49db-9d3d-6c268e3a67e2.png)

找到原因了。运行run-mirai.bat后没有输入login <QQ号> <QQ密码>根据提示登录账号。醉了。。。

**Comment by RockChinQ** [comment]
如果已解决请关闭issue
