### ISSUE TITLE
[BUG]login登录的时候要求输入验证码，然后就是登录失败

### ISSUE THREAD

**Issue by Jiaheliu137** [RockChinQ/QChatGPT#139]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
    例如： Centos x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
什么时候发生的，mirai还是主程序，越详细越好

**完整报错信息**  
完整的报错信息

**Comment by Jiaheliu137** [comment]
请认真按照实际情况填写以下信息！！！！

- 部署方式：
    手动部署
- 系统环境：
    例如： ubuntu20.04
- Python环境（仅手动部署填写）：
    例如： Python 3.9

**描述漏洞**  
mirai无法登录QQ

**完整报错信息**  
<img width="790" alt="截屏2023-02-13 02 10 46" src="https://user-images.githubusercontent.com/52644185/218325871-345cc39e-d8f0-4739-9b68-115233135964.png">

**Comment by RockChinQ** [comment]
去 github.com/mamoe/mirai/issues 去搜关键词

**Comment by RockChinQ** [comment]
mamoe/mirai#2418

**Comment by Jiaheliu137** [comment]
> mamoe/mirai#2418

问题解决了
解决方法：重新安装mirai和yirimirai，全部安装最新版本，之后mirai可以正常连接qq了

但是出现新的问题
<img width="697" alt="截屏2023-02-14 00 49 02" src="https://user-images.githubusercontent.com/52644185/218505562-edbc19e3-a629-4ed9-8c99-7db34a938e99.png">

asyncio.exceptions.TimeoutError报错

跟据现有issue解决方法，mirai和本项目的端口全部都是相同的8080，但是依旧有这种问题

环境：ubuntu20.04，python3.9
