### ISSUE TITLE
[ENHANCE]考虑添加 用户绑定自己的key而不是 后台配置的统一的key

### ISSUE THREAD

**Issue by nicknull** [RockChinQ/QChatGPT#140]
是否有考虑添加 用户绑定自己的key而不是 后台配置的统一的key

**Comment by RockChinQ** [comment]
这个大概是什么使用场景啊？是允许用户设置某群内私用key吗？

**Comment by nicknull** [comment]
> > 这个大概是什么使用场景啊？是允许用户设置某群内私用key吗？
> 
> 公用额度用完了,用户申请账号自己用，免去搭建机器人的烦恼，自己申请的key会省着点花

对的 是这个意思

**Comment by RockChinQ** [comment]
key由openai库管理，是单例模式，同时使用多个key难以控制，且有隐私泄露风险，此功能暂时不会考虑加入
