### ISSUE TITLE
[BUG]在有些QQ群里机器人不回复@

### ISSUE THREAD

**Issue by 459zyt** [RockChinQ/QChatGPT#141]

**Comment by RockChinQ** [comment]
日志

**Comment by AlasKuNull** [comment]
我也遇到了这个问题, mirai的控制台和bot的控制台都打印出来了 但是没有回复群里

**Comment by RockChinQ** [comment]
麻烦遇到此问题的朋友提供mirai和主程序的控制台输出截图，以及消息窗口截图

**Comment by AlasKuNull** [comment]
![image](https://user-images.githubusercontent.com/19400206/218490517-91edde3a-c638-41a6-aeb0-7da253a1f28e.png)
![image](https://user-images.githubusercontent.com/19400206/218490573-b5386fc5-6788-4fa5-bbd7-45298bb1f20f.png)

**Comment by AlasKuNull** [comment]
![image](https://user-images.githubusercontent.com/19400206/218492254-dd144897-4ab9-4e8a-bfde-ad435fc0576a.png)
![image](https://user-images.githubusercontent.com/19400206/218492393-d588fe48-2966-4101-86e3-de8200a6fb4f.png)

**Comment by AlasKuNull** [comment]
![image](https://user-images.githubusercontent.com/19400206/218492527-928060c6-d9dc-4b28-b0cf-ddb60e0e9fb5.png)

**Comment by RockChinQ** [comment]
> ![image](https://user-images.githubusercontent.com/19400206/218492254-dd144897-4ab9-4e8a-bfde-ad435fc0576a.png) ![image](https://user-images.githubusercontent.com/19400206/218492393-d588fe48-2966-4101-86e3-de8200a6fb4f.png)

 主程序被修改过，你这是哪里的发行

**Comment by AlasKuNull** [comment]
我用的安装包,然后自己加了一些写数据的代码和打印

**Comment by AlasKuNull** [comment]
谢谢 我试试

**Comment by RockChinQ** [comment]
若问题已解决，请关闭issue

**Comment by 459zyt** [comment]
用电脑登录机器人号，在群里说话就好了
