### ISSUE TITLE
[BUG]机器人日期认识错误，怎么修改呢

### ISSUE THREAD

**Issue by imkenf** [RockChinQ/QChatGPT#142]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    debian11

**描述漏洞**  
询问机器人当前日期，回答是2020年11月9日，不知是否bug还是训练模型问题

**Comment by RockChinQ** [comment]
https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#%E9%99%90%E5%88%B6
