### ISSUE TITLE
[ENHANCE] 功能不支持写代码吗？

### ISSUE THREAD

**Issue by mqEpiphany** [RockChinQ/QChatGPT#145]
希望能增加写代码的功能。
![image](https://user-images.githubusercontent.com/79396680/218749266-85c375a8-fb0d-4f4f-8288-9189dc457a86.png)

**Comment by RockChinQ** [comment]
问法不对，请发送 !reset 之后重试，而且请提供详细需求，而不是这种笼统的要求
