### ISSUE TITLE
[BUG]mirai.exceptions.ApiError: (5,'[ERROR 5]发送消息目标不存在，或指定对象不存在。','指定对象不存在')

### ISSUE THREAD

**Issue by xiatiaopoi** [RockChinQ/QChatGPT#146]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署
- 系统环境：
     Windows 11 x64
- Python环境：
     Python 3.10.9

**描述漏洞**  
     运行run-mirai ，Login successful后，运行run-bot。就这样提示了，他说新版本可用，但是不知道怎么输入!update

**完整报错信息**  

![image](https://user-images.githubusercontent.com/88807621/218772305-51691d07-7df2-4839-87e4-638896f98f3f.png)

**Comment by RockChinQ** [comment]
机器人加了管理员账号为好友吗

**Comment by RockChinQ** [comment]
请将原报错最后一行写到标题；若问题已解决，请关闭issue
