### ISSUE TITLE
[BUG] 卸载unvicorn后出现的，之前的问题是成功了但是没反应

### ISSUE THREAD

**Issue by knigth95** [RockChinQ/QChatGPT#148]
请认真按照实际情况填写以下信息！！！！

**运行环境：**
- 部署方式：
    手动部署
- 系统环境：
    例如： manjaro x64
- Python环境（仅手动部署填写）：
    Python 3.10.9

**描述漏洞**  
卸载unvicorn后出现的，之前的问题是成功了但是没反应然后就下了unvicorn，不管用后卸载unvicorn后就出现这个bug了

**完整报错信息**  
![image](https://user-images.githubusercontent.com/91075975/218809913-9a20e9e4-772e-4ecc-b6d0-865a61862fd6.png)

**Comment by RockChinQ** [comment]
估计是端口问题，尝试按照 #22 更换端口

**Comment by knigth95** [comment]
> 估计是端口问题，尝试按照 #22 更换端口

但是不做修改的情况下，我关闭了8080端口占用，重启还是出现一样的错误
![image](https://user-images.githubusercontent.com/91075975/218814606-a6c506c3-1269-4544-a024-77b11155c375.png)

**Comment by RockChinQ** [comment]
> > 估计是端口问题，尝试按照 #22 更换端口
> 
> 再看一次#22后，我将端口改为22端口，登录成功了，但是不知道机器人是否运行成功了
> ![image](https://user-images.githubusercontent.com/91075975/218817403-ab8da78b-6a01-4b39-8881-92b0e987b8f1.png)
> 

继续改，请使用1024之后的端口，随机给你想一个，就11451吧

**Comment by RockChinQ** [comment]
重复issue，请查看 #68
