### ISSUE TITLE
运行run-mirai.bat报错

### ISSUE THREAD

**Issue by Luo-XiuFeng** [RockChinQ/QChatGPT#150]
自动部署后输入了api的命令和QQ号后提示运行run-mirai.bat。
我以管理员方式运行，提示如下错误：
![image](https://user-images.githubusercontent.com/45417928/218898029-12fb9d85-7f87-4760-988e-56e100a69992.png)

**Comment by RockChinQ** [comment]
mirai检查更新时报错，应该不影响正常使用吧？

**Comment by Luo-XiuFeng** [comment]
> 自动化部配置后输入了api的命令和QQ号后提示运行run-mirai.bat。 我以管理员方式运行，提示如下错误： ![图像](https://user-images.githubusercontent.com/45417928/218898029-12fb9d85-7f87-4760-988e-56e100a69992.png)
完整报错如下：
![image](https://user-images.githubusercontent.com/45417928/218905469-9151d702-71e0-472e-b6ee-ac1f31430b36.png)
![image](https://user-images.githubusercontent.com/45417928/218905480-838985cd-825d-41bb-b363-fc94657caf7c.png)
![image](https://user-images.githubusercontent.com/45417928/218905499-de4e6cb8-eff4-4fd0-9e2c-6698e30ae755.png)
![image](https://user-images.githubusercontent.com/45417928/218905518-7e83dcbc-bc25-4ae1-bcf7-291193cba320.png)

![image](https://user-images.githubusercontent.com/45417928/218905539-0b538b06-0c78-4640-ae7f-44c57731a419.png)

**Comment by RockChinQ** [comment]
未知的mirai问题，看起来是网络问题，建议你到 mamoe/mirai 的issues去搜索

**Comment by Luo-XiuFeng** [comment]
> 

就是没搜到

**Comment by RockChinQ** [comment]
尝试使用`./mcl --disable-module updater`禁用更新模块后重启，注意：这需要你在命令行进入mirai目录手动执行

**Comment by Luo-XiuFeng** [comment]
> 尝试使用`./mcl --disable-module updater`禁用更新模块后重启，注意：这需要你在命令行进入mirai目录手动执行

禁用后 报错如下：
![image](https://user-images.githubusercontent.com/45417928/218973350-87f6d927-02c1-4168-b247-a90305d29149.png)

**Comment by RockChinQ** [comment]
估计还是网络问题，可以再试试看根据mirai的文档禁用announcement的获取模块，其他mirai问题请参阅mirai文档及issues
