### ISSUE TITLE
希望能够加上可以询问编程的能力（比如一些代码模板，编程问题的参考解答）[ENHANCE]

### ISSUE THREAD

**Issue by knigth95** [RockChinQ/QChatGPT#151]
例如像这样
![image](https://user-images.githubusercontent.com/91075975/219102333-2997cdfa-ddf5-4f9c-b4a9-cdb92c187d17.png)

**Comment by RockChinQ** [comment]
#145

**Comment by RockChinQ** [comment]
本项目只做调用工作，不控制内容，请自行研究
