### ISSUE TITLE
[ENHANCE] 现在使用的模型是1版本的吗？

### ISSUE THREAD

**Issue by xionghaizhi** [RockChinQ/QChatGPT#152]
![image](https://user-images.githubusercontent.com/30396478/219297858-9838a53c-581a-4c5d-a7e4-51b2f1aac91b.png)

**Comment by RockChinQ** [comment]
本项目使用GPT-3模型，关于此项目的实现原理的问题，请仔细阅读仓库内文档以及wiki，并以此仓库为标准，其他解释均视为无效。
https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#%E9%99%90%E5%88%B6
