### ISSUE TITLE
docker 安装端口出现问题[BUG]

### ISSUE THREAD

**Issue by knigth95** [RockChinQ/QChatGPT#154]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    Centos x64

**描述漏洞**  
重新用docker部署后出现的问题，终端反馈端口返回错误，但是查询8080端口，没有问题，那个占用是mirai的占用，启动前查看端口是没有任何占用的

**完整报错信息**  
启动前：
![image](https://user-images.githubusercontent.com/91075975/219720492-42dd8965-68e2-4330-9b8c-b7648d6ab693.png)

启动后：
![image](https://user-images.githubusercontent.com/91075975/219720137-dfcf8d0a-fd21-4bef-87d1-a629203985ba.png)
![image](https://user-images.githubusercontent.com/91075975/219720180-7f5afead-a876-4040-b06d-db628229b5d7.png)

**Comment by RockChinQ** [comment]
查看 #127
