### ISSUE TITLE
[BUG]mirai报错显示版本过低，已经试过issues里面所有的方法了但还是不行

### ISSUE THREAD

**Issue by smz202000** [RockChinQ/QChatGPT#159]
![QQ截图20230219095930](https://user-images.githubusercontent.com/69295615/219908075-fbce5692-f0fe-445a-a13f-fe856eb33f1d.png)
就这样的

**Comment by RockChinQ** [comment]
请使用 #137 的办法解决，记得每次更换协议都要先关闭mirai再删除bots之后更换；若仍然不行，请考虑更换QQ号。

**Comment by ruruamour** [comment]
关于尝试Issues所有方法仍无法登录的情况可以试试我成功这个思路：
 1.删除bots下账号文件，修改登录协议，配置好2自动登录，重启mirai
2.手机官方客户端登录QQ，账号安全>登录设备管理>开启陌生设备登录保护，删除所有设备，这时候会退出登录
3,mirai登录，出现要求验证码的提示
mirai版本2.14 协议ANDROID_WATCH
