### ISSUE TITLE
[BUG]已安装但无法导入yaml

### ISSUE THREAD

**Issue by smz202000** [RockChinQ/QChatGPT#160]
![6249bc262599e966.jpg](https://user-images.githubusercontent.com/69295615/219909965-184d1ffb-a04a-445f-b7ee-cef9bed5d8ca.jpg)
如题，我安装了yaml但是不能导入它

**Comment by RockChinQ** [comment]
独立插件问题请到插件仓库反馈 https://github.com/dominoar/QChatPlugins
