### ISSUE TITLE
[ENHANCE] 私聊能否不回应/或!开头的命令

### ISSUE THREAD

**Issue by Speechless22** [RockChinQ/QChatGPT#165]

**Comment by RockChinQ** [comment]
啥意思

**Comment by Speechless22** [comment]
就是我在私聊中用/help、/friend list等等这些命令想要管理机器人时，ChatGPT也会回应，我觉得这没必要
![image](https://user-images.githubusercontent.com/61347609/219948923-81489321-ff0a-4682-9279-ff4a1fa38ea9.png)

**Comment by RockChinQ** [comment]
> 就是我在私聊中用/help、/friend list等等这些命令想要管理机器人时，ChatGPT也会回应，我觉得这没必要 ![image](https://user-images.githubusercontent.com/61347609/219948923-81489321-ff0a-4682-9279-ff4a1fa38ea9.png)

这个图不是我的机器人，但你是想借此图表达意思吗？  
此问题不会出现在我的项目中

**Comment by Speechless22** [comment]
你可能误会了，这是第三方QQ客户端的界面。
我想说，对于一些Mirai基本命令，QChatGPT也会回应
![image](https://user-images.githubusercontent.com/61347609/219949370-a0fce4a7-5144-46ac-b363-7aeeb80c116e.png)

**Comment by RockChinQ** [comment]
了解了，需要时间设计一下

**Comment by RockChinQ** [comment]
还有哪些常用的需要忽略的指令呢，可否提供一些

**Comment by Speechless22** [comment]
我觉得默认屏蔽/或!开头的命令已经足够了，再加的话最好让用户自定义

**Comment by RockChinQ** [comment]
ok,目前默认忽略`/`和`\`开头的消息，由于`!`是本程序指令默认前缀，不可忽略

**Comment by RockChinQ** [comment]
已实现，请更新主程序并查看`config-template.py`中的`ignore_rules`字段的注释，并在`config.py`中设置此字段
