### ISSUE TITLE
[ENHANCE]希望增加情景预设读取本目录.TXT文件

### ISSUE THREAD

**Issue by shadowtyw** [RockChinQ/QChatGPT#167]
比如，!reset 猫娘

会自动读取本目录内 猫娘.txt 文件，根据txt文件内容加载预设场景。

**Comment by RockChinQ** [comment]
已实现，请更新程序并查看方法 https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#%E9%A2%84%E8%AE%BE%E6%96%87%E5%AD%97
