### ISSUE TITLE
[BUG]服务器部署时没有弹窗且禁止登录

### ISSUE THREAD

**Issue by 1372501421** [RockChinQ/QChatGPT#170]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：win自动
    手动部署/自动部署/Docker部署
- 系统环境：Windows Server 2022 DataCenter 64bit CN
    例如： Centos x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
mirai登录时没有弹窗，且禁止登录。QQ号已改密码且能在服务器用客户端无验证登录。

**完整报错信息**  
完整的报错信息
![DH`}S8ZSA)8AK_P7A 3E502](https://user-images.githubusercontent.com/49863054/220380739-7b2371b6-6e71-47be-a06a-55b21da04f24.png)
![@L XP W~($NHS@5U3H3$K0G](https://user-images.githubusercontent.com/49863054/220380785-05b1e300-1ae4-4e76-906c-87b06aec9eee.png)

**Comment by 1372501421** [comment]
![Y2@ZSIWL24L5MVX6R7FY7X0](https://user-images.githubusercontent.com/49863054/220381242-bae75fe8-dbd8-44a2-b8f6-7312ae5fae53.png)

**Comment by RockChinQ** [comment]
查看 #137

**Comment by RockChinQ** [comment]
此问题统一解法 #285
