### ISSUE TITLE
[BUG]No module named 'pkg' No module named 'colorlog'

### ISSUE THREAD

**Issue by r5rinimaa** [RockChinQ/QChatGPT#173]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
   自动部署
- 系统环境：
    例如： windows server
**描述漏洞**  
C:\aaa\QChatGPT>..\python\python.exe main.py
Traceback (most recent call last):
  File "C:\aaa\QChatGPT\main.py", line 11, in <module>
    import colorlog
ModuleNotFoundError: No module named 'colorlog'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\aaa\QChatGPT\main.py", line 14, in <module>
    import pkg.utils.pkgmgr as pkgmgr
ModuleNotFoundError: No module named 'pkg'

C:\aaa\QChatGPT>pause
请按任意键继续. . .

**Comment by RockChinQ** [comment]
这是python环境问题，请删除主机上所有python环境后参考本仓库文档中的步骤进行手动部署

**Comment by RockChinQ** [comment]
与 #112 相同原因
