### ISSUE TITLE
[BUG] enabled字段自动变成true问题

### ISSUE THREAD

**Issue by Speechless22** [RockChinQ/QChatGPT#177]
似乎执行!update或!plugin update（不确定是哪个）后enabled字段会由false变成true
![image](https://user-images.githubusercontent.com/61347609/221076246-ab2816f1-1e7f-4dc6-98c9-23f68ce8b9de.png)

**Comment by Speechless22** [comment]
不止如此blog_msg_strategy也会重置到blog_msg_strategy = "forward_msg_component"

**Comment by RockChinQ** [comment]
你是手动部署的吗

**Comment by Speechless22** [comment]
> 你是手动部署的吗

是

**Comment by RockChinQ** [comment]
无法复现此问题，可能是意外的更新失败导致，先关闭此issue，之后遇到再开启

**Comment by RockChinQ** [comment]
dulwich 问题，将在之后根据语义化版本进行更新以弃用使用dulwich的基于提交信息的自动更新

**Comment by RockChinQ** [comment]
已修复，请更新
