### ISSUE TITLE
怎样关闭情景预设

### ISSUE THREAD

**Issue by d4renk** [RockChinQ/QChatGPT#186]
在发起会话并发送消息时，会先发送情景预设，导致ChatGPT需要先回复情景预设，这会导致第一次回复速度变慢。

**Comment by RockChinQ** [comment]
> 在发起会话并发送消息时，会先发送情景预设，导致ChatGPT需要先回复情景预设，这会导致第一次回复速度变慢。

现已更新，初次对话不再单独发生情景预设，而是拼接预设文字和第一个问题，你可以尝试更新主程序和revLibs；若仍要关闭情景预设功能，请到config.py讲default_prompt设为""
