### ISSUE TITLE
support gpt-3.5-turbo[ENHANCE]

### ISSUE THREAD

**Issue by fanxiaoyu0** [RockChinQ/QChatGPT#195]
增加对新发布的 gpt-3.5-turbo API 的支持

**Comment by RockChinQ** [comment]
see #194

**Comment by RockChinQ** [comment]
请更新主程序，并在config.py中将`completion_api_params`的`model`参数设置为`gpt-3.5-turbo`

**Comment by RockChinQ** [comment]
若提示找不到`ChatCompletion`，请查看 #196

**Comment by RockChinQ** [comment]
若已安装`revLibs`插件，可以到`plugins/switch,json`将对应的`enable`设为`false`禁用`revLibs`插件，以使用gpt-3.5-turbo模型
