### ISSUE TITLE
无法安装yiri-mirai依赖

### ISSUE THREAD

**Issue by China-QinSe** [RockChinQ/QChatGPT#202]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：手动部署
- 系统环境：Centos7
- Python环境（仅手动部署填写）：Python 3.11.2

**描述漏洞**  
登录完mirai之后 开始部署QchatGPT
安装依赖pip3 install yiri-mirai openai colorlog func_timeout
另外3个正常安装  yiri-mirai提示未找到

**完整报错信息**  
[root@ser576670844266 QChatGPT]# pip3 install yiri-mirai openai colorlog func_timeout -i https://mirrors.aliyun.com/pypi/simple/
Looking in indexes: https://mirrors.aliyun.com/pypi/simple/
ERROR: Could not find a version that satisfies the requirement yiri-mirai (from versions: none)
ERROR: No matching distribution found for yiri-mirai

![image](https://user-images.githubusercontent.com/94440319/222698370-dac2c06e-e301-452d-bdaf-072fab6e14c8.png)

**Comment by RockChinQ** [comment]
阿里源的问题，换个豆瓣源或者清华源

**Comment by China-QinSe** [comment]
![image](https://user-images.githubusercontent.com/94440319/222957163-cb2e2caf-318e-477e-a0d3-659709fc2f43.png)
豆瓣源也没有

**Comment by China-QinSe** [comment]
已解决  原因是升级完py之后  pip的指向还是3.6版本  通过设置全局变量指向到最新版py解决
