### ISSUE TITLE
[BUG]调用api返回的结果不全，前面的部分被截掉了；调用逆向库返回的结果正常

### ISSUE THREAD

**Issue by haozhc** [RockChinQ/QChatGPT#204]
调用api返回的结果
![api返回的结果](https://user-images.githubusercontent.com/9688577/222749937-a5c36520-1e61-4733-9ebf-8ab4f5567259.png)
调用逆向库返回的结果
![逆向库返回结果](https://user-images.githubusercontent.com/9688577/222750084-e3860018-7bfd-4289-bd13-a21755741442.png)

**Comment by RockChinQ** [comment]
不一定是被截断了，可能就是只有这些回复，请提供更多的控制台信息便于确定问题

**Comment by RockChinQ** [comment]
我这边没发现这个问题，先关闭了
```
我: 写一封感谢信
机器人: 尊敬的xx先生/女士，

您好！

我是您的客户，写这封信是为了表达我的感激之情。

在过去的几个月里，我受到了您和您团队的专业、高效和细致帮助。从最初的咨询到后续跟进，您始终以极为用心的态度为我服务，不厌其烦地解答我的各种问题，并提供了许多宝贵的建议和意见。

我很庆幸能有您这样优秀的合作伙伴，真心感谢您对我的支持和关注！这些经验将长久留在我心中，也使我对未来充满信心和期待。

再次衷心感谢你们的付出与协助！祝工作顺利、身体健康、家庭美满！

此致

敬礼

xx启
```
