### ISSUE TITLE
[BUG]每次程序内!update更新后，自定义屏蔽词sensitive.json被覆盖

### ISSUE THREAD

**Issue by wenyinos** [RockChinQ/QChatGPT#206]
**运行环境**
- 部署方式：
    手动部署/自动部署
- 系统环境：
    Ubuntu 20.04
- Python环境（仅手动部署填写）：
   Python 3.10.

**描述漏洞**  
如题

**Comment by RockChinQ** [comment]
是你修改了sensitive.json然后更新之后你的修改就被重置了？

**Comment by wenyinos** [comment]
程序内发送!update更新会被覆盖掉，但在目录下手动执行git pull不会

**Comment by RockChinQ** [comment]
dulwich问题，之后更新语义化版本的方式进行更新就不会了 #188
