### ISSUE TITLE
[BUG]主程序运行时cpu占用100%

### ISSUE THREAD

**Issue by nanyansky** [RockChinQ/QChatGPT#209]
**运行环境**
- 部署方式：
    Docker部署
- 系统环境：
    例如： Ubuntu 20.04 x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.10

**描述漏洞**  
主程序运行时cpu占用100%

**完整报错信息**  
暂无

**Comment by RockChinQ** [comment]
#221，是否也是在更新时遇到此情况？

**Comment by nanyansky** [comment]
> #221，是否也是在更新时遇到此情况？

现在正常，应该就是之前版本更新的问题

**Comment by RockChinQ** [comment]
> > #221，是否也是在更新时遇到此情况？
> 
> 现在正常，应该就是之前版本更新的问题

ok
