### ISSUE TITLE
[BUG]Banlist不工作

### ISSUE THREAD

**Issue by DannyLI0319** [RockChinQ/QChatGPT#211]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    例如： Windows 10 x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
文件banlist.py配置如下，默认配置，未做改动：
enable = True

person = [2854196310]  # 2854196310是Q群管家机器人的QQ号，默认屏蔽以免出现循环
![image](https://user-images.githubusercontent.com/120266145/222902335-5674cda0-a7f0-4333-89f7-09f5f493182b.png)

复查群管家qq号和配置一致：
![image](https://user-images.githubusercontent.com/120266145/222902237-013f075b-40e6-4c67-b08f-ce1ffa7f49f9.png)

拉机器人入群后，入群消息会触发无限循环：
![image](https://user-images.githubusercontent.com/120266145/222902276-a27d0f4e-a1f3-4d66-ad55-b31754b2d233.png)

**完整报错信息**  
完整的报错信息

**Comment by RockChinQ** [comment]
测试一下其他号是否能被屏蔽

**Comment by RockChinQ** [comment]
bug，新版本中person对群内特定人不生效

**Comment by RockChinQ** [comment]
已修复
