### ISSUE TITLE
[BUG]求助！在mcl里面输入QQ账号密码后出错

### ISSUE THREAD

**Issue by MoYuNEKO** [RockChinQ/QChatGPT#213]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署/自动部署
- 系统环境：
   windows11
- Python环境（仅手动部署填写）：
Python 3.11.2

**描述漏洞**  
![微信图片_20230304234425](https://user-images.githubusercontent.com/120086511/222915717-ab70fb73-225f-470f-8667-d36cc264ec31.png)
如上图所示，手动和自动版本我都尝试过，都是卡在输入账号密码登录的时候，修改协议也是同样的错误，希望能得到解决！

**完整报错信息**  
完整的报错信息

**Comment by RockChinQ** [comment]
请先查看 #137  
注意在每次修改协议之前都需要 1. 关闭mirai  2. 删除`bots/`目录  
建议在登录时关闭网络代理  
若仍然不行，请更换QQ号

**Comment by MoYuNEKO** [comment]
关闭网络代理指的是防火墙吗？

**Comment by RockChinQ** [comment]
翻墙软件

**Comment by MoYuNEKO** [comment]
好的

**Comment by MoYuNEKO** [comment]
![image](https://user-images.githubusercontent.com/120086511/222916698-635ddf67-0336-4aa2-947a-2fcc0d8928ab.png)
没有弹出登录而是验证

**Comment by RockChinQ** [comment]
根据提示验证登录，具体方法请查看教程

**Comment by MoYuNEKO** [comment]
![image](https://user-images.githubusercontent.com/120086511/222917781-93ea8918-1978-4e66-b639-955a183e501d.png)
输入验证码后还是无法登录如图
