### ISSUE TITLE
[ENHANCE]不建议将长消息转图片的功能放在本体中

### ISSUE THREAD

**Issue by LINSTCL** [RockChinQ/QChatGPT#216]
不建议将长消息转图片的功能放在本体中，而应该作为一个插件选择性安装，原因如下
1、在本体程序增加PIL库，会增加部署难度，或者产生意想不到的错误
2、图像处理会占用更多性能资源，在一些复杂情况中会使主程序运行缓慢
3、文图转换用到的字体文件不适宜放在git仓库
4、在插件中可以客制化字体而不用更改本体，使得本体运行不易出错

**Comment by RockChinQ** [comment]
有一定道理：  
1. 目前程序会在启动时使用内置的pip尝试解决依赖保证依赖正常
2. 确实
3. 字体不提交到tree中可能更好
4. 但打插件来解决这个问题感觉有点小题大做

目前只有简单的文字转图片功能，之后若需要图片风格化或者更加复杂的文字转图片可以考虑使用插件来解决这个问题，况且目前插件之间的互调暂时没有很好的方案，若使用单独插件来解决文字转图片功能，调用方法很复杂。  

所以现在的想法是：
1. 从主线中删除字体文件
2. 程序默认以`forward`策略处理长消息
3. 若用户需要启用`image`策略，在config.py中修改，程序默认使用系统默认字体，同时支持用户自行下载并指定字体文件

**Comment by RockChinQ** [comment]
现在不再自带字体文件，用户必须在config.py中指定使用的字体文件路径
```Python


# 文字转图片时使用的字体文件路径
# 当策略为"image"时生效
#   若在Windows系统下，程序会自动使用Windows自带的微软雅黑字体
#   若未填写或不存在且不是Windows，将禁用文字转图片功能，改为使用转发消息组件
font_path = ""
```
当`blob_message_strategy`为`image`时，若未指定或指定的字体文件不存在：
1. 若是在Windows系统上，程序将使用`C:/Windows/Fonts/msyh.ttc`作为默认字体文件，若仍不存在则将`blob_message_strategy`设为`forward`
2. 其他系统上，程序将直接把`blob_message_strategy`设为`forward`
