### ISSUE TITLE
[ENHANCE]建议添加自动分段（落）发送和图片发送的一些小建议。

### ISSUE THREAD

**Issue by McPeter111** [RockChinQ/QChatGPT#218]
建议添加自动分段（落）发送
比如：
输出内容：
chatgpt：“芝士雪豹

芝士猞狸”
可以根据中间的空行进行分发，而不是根据字数分发消息
比如：
chatgpt：“芝士雪豹”
chatgpt：“芝士猞狸”

图片发送不支持emoji，还是会出现错位问题，比如ansi art，棋盘等（也可能是gpt自己没控制？）

**Comment by RockChinQ** [comment]
现在仅有两种长消息处理模式，不再截断消息：

- 转发消息组件
- 文字转图片
