### ISSUE TITLE
[BUG]QQ登录时遇到无法登录

### ISSUE THREAD

**Issue by MoYuNEKO** [RockChinQ/QChatGPT#220]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署/自动部署
- 系统环境：
win11
- Python环境（仅手动部署填写）：
Python 3.11.2

**描述漏洞**  
![1677999034544](https://user-images.githubusercontent.com/120086511/222946170-0d77b50d-bdd5-4be9-99fa-b2002f902a71.jpg)
如上图所示，在登录QQ时遇到了滑动验证，在手机端操作后将代码输入到验证框内出现无法登录现象。

**完整报错信息**  
完整的报错信息

**Comment by RockChinQ** [comment]
很抱歉，如果你已经严格按照指引尝试了 #137 仍然无法解决，请到 mamoe/mirai 的issues尝试查找解决办法或者提出新issue
