### ISSUE TITLE
[BUG]更新程序报错： [WinError 5] 拒绝访问

### ISSUE THREAD

**Issue by McPeter111** [RockChinQ/QChatGPT#224]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署
- 系统环境：
    Windows server 2012
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
主程序更新时报错
关闭文字转图片：string indices must be integers
打开文字转图片：[WinError 5] 拒绝访问。: '.\\res\\simhei.ttf'
![E9C272FE-ECC2-4B08-AF50-95EBA9ACAC25](https://user-images.githubusercontent.com/121279581/222952593-2579e3e9-edc8-4d39-baeb-eca0b7daf4be.jpeg)

**Comment by RockChinQ** [comment]
现在不再自带字体文件，用户必须在config.py中指定使用的字体文件路径
```Python
# 文字转图片时使用的字体文件路径
# 当策略为"image"时生效
#   若在Windows系统下，程序会自动使用Windows自带的微软雅黑字体
#   若未填写或不存在且不是Windows，将禁用文字转图片功能，改为使用转发消息组件
font_path = ""
```
当`blob_message_strategy`为`image`时，若未指定或指定的字体文件不存在：
1. 若是在Windows系统上，程序将使用`C:/Windows/Fonts/msyh.ttc`作为默认字体文件，若仍不存在则将`blob_message_strategy`设为`forward`
2. 其他系统上，程序将直接把`blob_message_strategy`设为`forward`
