### ISSUE TITLE
[bot]更新失败:[WinError 5] 拒绝访问。: '.\\res\\simhei.ttf'

### ISSUE THREAD

**Issue by SkyFutu** [RockChinQ/QChatGPT#227]
自动部署，windows server 2019
[bot]更新失败:[WinError 5] 拒绝访问。: '.\\res\\simhei.ttf'
通知管理员:更新失败:[WinError 5] 拒绝访问。: '.\\res\\simhei.ttf'

**Comment by RockChinQ** [comment]
已修复，请更新 https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#-%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0%E4%BB%A3%E7%A0%81%E5%88%B0%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC
