### ISSUE TITLE
屏蔽词替换功能

### ISSUE THREAD

**Issue by xiaoxin6666666** [RockChinQ/QChatGPT#229]
希望大佬出个屏蔽词自由替换功能

**Comment by RockChinQ** [comment]
屏蔽词掩码自定义

**Comment by RockChinQ** [comment]
已实现，请等待之后的发行版并更新程序，使用方法：  
按照sensitive-template.json的格式在`sensitive.json`加上`mask`字段，程序将使用此字符替换敏感词中的每个字；若存在`mask_word`字段，则程序将使用这个字段的值替换整个敏感词。
