### ISSUE TITLE
如何关闭@回复以及实现主动聊天？

### ISSUE THREAD

**Issue by Fatima-meow** [RockChinQ/QChatGPT#231]
不是需求建议请勿填写此模板！！！！
请问大佬如何关闭bot的@回复功能，只保留关键词回复功能，以及如何实现随机抓取chat回复

**Comment by RockChinQ** [comment]
暂时没有这个功能，之后考虑添加

**Comment by Fatima-meow** [comment]
考虑了一个笨方法，直接把qqbot里manager.py中群聊At回复的代码删掉好像也能允许

**Comment by RockChinQ** [comment]
已实现，请等待发行版更新后依照`config-template.py`中的`response_rules`修改`config.py`
