### ISSUE TITLE
[BUG]运行mirai后，输入账号密码成功后没有弹窗，导致不能验证

### ISSUE THREAD

**Issue by Zwaibk** [RockChinQ/QChatGPT#235]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
    例如： Centos x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
什么时候发生的，mirai还是主程序，越详细越好
![FVV)BKOL2Z157U}4 %U%AOY](https://user-images.githubusercontent.com/115025863/223097937-d9b0b5b1-ca6b-453a-8e27-b7ce01cda67f.png)

**完整报错信息**  
完整的报错信息

**Comment by RockChinQ** [comment]
请仔细阅读指引，并严格按照教程和文档进行

**Comment by Zwaibk** [comment]
谢谢大佬回复的这么及时，仔细阅读完指引后并严格按照教程和文档进行，可还是出现登录时没出现弹窗，无法滑动验证码登录，

**Comment by RockChinQ** [comment]
> 谢谢大佬回复的这么及时，仔细阅读完指引后并严格按照教程和文档进行，可还是出现登录时没出现弹窗，无法滑动验证码登录，

你输入`TxCaptchaHelper`就有了

**Comment by Zwaibk** [comment]
输入后变成这样了
![image](https://user-images.githubusercontent.com/115025863/223103625-a12978dc-8b0d-472b-992f-74464933a518.png)

**Comment by RockChinQ** [comment]
> 输入后变成这样了 ![image](https://user-images.githubusercontent.com/115025863/223103625-a12978dc-8b0d-472b-992f-74464933a518.png)

最近好像确实不太好登录，你可以尝试关闭网络代理或者更换网络重试，或者到 https://github.com/mamoe/mirai/issues 寻求帮助

**Comment by Zwaibk** [comment]
好的，谢谢大佬

**Comment by EricMeteorite** [comment]
把这个http链接复制到手机那个app，然后解锁完复制生成的内容，再粘贴到LOGIN>>这里就可以了应该

**Comment by Zwaibk** [comment]
谢谢大佬们

**Comment by QINGMINGMIKU** [comment]
可以在Mirai-plugin里面添加一个验证插件，插件地址：``https://github.com/KasukuSakura/mirai-login-solver-sakura``

**Comment by RockChinQ** [comment]
今天两会加上腾讯风控机制升级，mirai较为不稳定，可以前往mirai的issues寻求帮助

**Comment by Zwaibk** [comment]
谢谢大佬们的帮助
