### ISSUE TITLE
[ENHANCE]关于会话管理(删除会话)

### ISSUE THREAD

**Issue by EricMeteorite** [RockChinQ/QChatGPT#239]
在使用过程中发现BOT只能查看会话和指定回溯到某一个会话，可否增加一个对会话的管理功能，因为如果会话变多但无法删除的话可能会是一个问题。

当然不排除是不是我没有找到这个功能，目前如果有删除会话的指令，请告诉我。
谢谢！

**Comment by RockChinQ** [comment]
确实暂时没有会话删除功能

**Comment by EricMeteorite** [comment]
> 确实暂时没有会话删除功能

那目前可以在哪里手动删除呀，目前会话有点多了，感谢

**Comment by RockChinQ** [comment]
> > 确实暂时没有会话删除功能
> 
> 那目前可以在哪里手动删除呀，目前会话有点多了，感谢

你可以直接删除database.db，但这会导致apikey使用量记录也被删除，如果在意的话建议等待更新

**Comment by EricMeteorite** [comment]
> > > 确实暂时没有会话删除功能
> > 
> > 
> > 那目前可以在哪里手动删除呀，目前会话有点多了，感谢
> 
> 你可以直接删除database.db，但这会导致apikey使用量记录也被删除，如果在意的话建议等待更新

好的，感谢

**Comment by HuskyRye** [comment]
强烈支持添加删除会话记录的功能

**Comment by RockChinQ** [comment]
已实现，请等待最新版发布后更新，并前往wiki的功能使用页查看`!del`指令和`!delhst`指令
