### ISSUE TITLE
[BUG]程序成功运行后，在群里面@机器人不回信息，但是私信就能回

### ISSUE THREAD

**Issue by Zwaibk** [RockChinQ/QChatGPT#240]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
    例如： Centos x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
什么时候发生的，mirai还是主程序，越详细越好

**完整报错信息**  
![image](https://user-images.githubusercontent.com/115025863/223145152-7c5e55fb-6ebb-41fa-a604-890c52b0de56.png)
![image](https://user-images.githubusercontent.com/115025863/223145243-a36f53ba-c1e0-4c70-a4e0-29432fb16b5e.png)
![image](https://user-images.githubusercontent.com/115025863/223145344-6504a229-da1d-42ac-8d84-3fd075b37c65.png)

完整的报错信息

**Comment by RockChinQ** [comment]
提供控制台输出

**Comment by LiamHua** [comment]
我也出现了同样的问题，机器人控制台中显示已经回复了消息，但是mcl控制台中无法显示的
<img width="957" alt="image" src="https://user-images.githubusercontent.com/49788833/223187940-76e26e58-4792-48ef-bcb4-4af62525060f.png">
<img width="889" alt="image" src="https://user-images.githubusercontent.com/49788833/223188117-8a855ac4-a0e5-4c02-b5f6-b7b2b09a531d.png">

**Comment by LiamHua** [comment]
> 我也出现了同样的问题，机器人控制台中显示已经回复了消息，但是mcl控制台中无法显示的
> <img alt="image" width="957" src="https://user-images.githubusercontent.com/49788833/223187940-76e26e58-4792-48ef-bcb4-4af62525060f.png">
> <img alt="image" width="889" src="https://user-images.githubusercontent.com/49788833/223188117-8a855ac4-a0e5-4c02-b5f6-b7b2b09a531d.png">

我的问题已经解决，是由于该账号被禁言导致

**Comment by HuskyRye** [comment]
检查bot是否对q群开启了免打扰

**Comment by Zwaibk** [comment]
![image](https://user-images.githubusercontent.com/115025863/223307720-591f47c2-34b7-4c79-9230-51e165bc7330.png)
![image](https://user-images.githubusercontent.com/115025863/223307780-03e458c7-06f8-4122-9c9a-eb55753056a8.png)
之前能检测到，重启后就不能了

**Comment by RockChinQ** [comment]
这个是mirai都没有接收到，请尝试重启、重装、更换网络重新登录，或前往mirai的issues反馈
