### ISSUE TITLE
如何实现在运行中强调bot人设的功能？

### ISSUE THREAD

**Issue by Fatima-meow** [RockChinQ/QChatGPT#245]
例如：在bot运行了一段时间后突然说出含有“我是一个AI语言模型”或者“我不是XXX，我没有情感和个性”，“对不起，我不能回答这样的问题”之类的脱离人设的回答时检测到关键词并不发送该消息，转而向API再次上传需要强调的设定以达到稳定人设的目的

**Comment by RockChinQ** [comment]
暂时没有此功能，考虑添加

**Comment by chordfish-k** [comment]
> 暂时没有此功能，考虑添加

有人提到过通过改变请求时的messages数组以注入记忆的方法，试了下，目前是可行的。在messages中的每一组问答中，无论user提出多么不合理的要求，只要伪造assistant作出肯定回答，那之后的请求得到的回复就会保留这个伪造的观点( ﾟ∀。)

**Comment by RockChinQ** [comment]
> > 暂时没有此功能，考虑添加
> 
> 有人提到过通过改变请求时的messages数组以注入记忆的方法，试了下，目前是可行的。在messages中的每一组问答中，无论user提出多么不合理的要求，只要伪造assistant作出肯定回答，那之后的请求得到的回复就会保留这个伪造的观点( ﾟ∀。)

感谢关注，确实是可以在每次请求时将情景预设都固定放置到`prompt`最前方发送给模型，欢迎自行实现此功能后提出pr进行修改

**Comment by RockChinQ** [comment]
将由于 #262 被关闭，请后续升级最新发行版后根据此pr内的说明进行设置
