### ISSUE TITLE
[BUG]有输出信息但是收不到信息没有发送过来吗

### ISSUE THREAD

**Issue by xiaoxin6666666** [RockChinQ/QChatGPT#250]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：自动部署
    手动部署/自动部署/Docker部署
- 系统环境：
    例如： Centos x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
有输出信息但是这边收不到信息

**完整报错信息**

**Comment by xiaoxin6666666** [comment]
![Uploading VZJRH44LS)5ZTF@1KSP]UM0.png…]()

**Comment by xiaoxin6666666** [comment]
![VZJRH44LS)5ZTF@1KSP UM0](https://user-images.githubusercontent.com/110280319/223487907-1b2c78dc-acc4-4634-9b2b-36aaddb51d72.png)

**Comment by xiaoxin6666666** [comment]
我找到原因了，我在sensitive.json里加了一些屏蔽词但是没有弄屏蔽词替换。然后他就这样信息不发过来我后面设置的屏蔽词是：
    "等",
    "此外，",
    "等等",
    "总的来说，",
    "同时，",
    "最后，",
    "“",
    "”",
    "其次，",
    "、",
    "因此，",
    "(",
    ")",
    "总之，",
    ";",
    "另外，"

**Comment by xiaoxin6666666** [comment]
加上屏蔽词替换的配置可以用但是加上，我这些屏蔽词他不会信息怎么解决呢

**Comment by xiaoxin6666666** [comment]
好像是我文本没有稿好的原因现在已经好了

**Comment by RockChinQ** [comment]
mirai问题
