### ISSUE TITLE
[ENHANCE]如何单独禁用API-key功能只使用revLib连接

### ISSUE THREAD

**Issue by wenyinos** [RockChinQ/QChatGPT#254]
最好能加一个开关，否则注释掉所有openai_config部分之后配置文件还是尝试寻找可用的key，在管理员账号上面报错

**Comment by IZege** [comment]
确实，群里说话多了一会儿费用就顶不住了

**Comment by RockChinQ** [comment]
plugins/switch.json中开启逆向库插件时，程序会只调用逆向库插件的功能

**Comment by RockChinQ** [comment]
安装[此插件](https://github.com/RockChinQ/Switcher)，即可在使用中切换文字模型。
