### ISSUE TITLE
[ENHANCE]关于人格的功能

### ISSUE THREAD

**Issue by xiaoxin6666666** [RockChinQ/QChatGPT#259]
求大佬加个，指定某个qq号使用哪个人格预设的，不指定则使用默认人格的功能

**Comment by Fatima-meow** [comment]
用!help查看指令，!reset 人格名称 切换人格

**Comment by xiaoxin6666666** [comment]
那重置会话之后，还要重新选择人格吗

**Comment by Fatima-meow** [comment]
你要切换人格名称啊，不要直接!reset ,!help写清楚了的

**Comment by xiaoxin6666666** [comment]
我知道，我是说如果我后面！reset重置会话之后还要不要重新选择人格

**Comment by RockChinQ** [comment]
关于某会话重置时使用指定情景预设的方式，请到仓库wiki的功能使用页查看相关指令

**Comment by xiaoxin6666666** [comment]
![c91ae3d5668aaad17c2beef487662d2](https://user-images.githubusercontent.com/110280319/224202534-0a1dd5c9-abaa-4b41-97b5-f822ebe5d50c.png)

**Comment by xiaoxin6666666** [comment]
他报错这样没关系的吗

**Comment by RockChinQ** [comment]
> 我知道，我是说如果我后面！reset重置会话之后还要不要重新选择人格

需要，除非你使用`!reset <情景预设名称>`的格式进行重置
