### ISSUE TITLE
[ENHANCE] 机器人消息回复字数极少，往往340字就中断，建议修改输出方式。

### ISSUE THREAD

**Issue by SurviveZ** [RockChinQ/QChatGPT#260]
经我多日测试，Qchatgpt的bot在config中设置上下文token和请求openai token的值极其有问题，值不能过大，稍大一些就爆token宕机，只能设置较小的值来使用。但设置较小的值后Qchatgpt Bot回复的消息字数也极少，通常三百多字就中断，容易中途中断，中断后让它继续它会另输出一段不想关内容。其他人的issues提及过这个问题但都被没有成功复现为由关闭了，事实上经我多日测试这个问题是确实存在的。
经我测试https://lucent.blog/?p=118这个框架能正常输出上千字的大段内容，并且中断后命令继续能正常继续接着上文继续输出，这个框架也不需要分别输入上下文token和请求openai的max token，只需要填写一个token值，我设置为4000后也一直没有出现爆token的情况，而qchatgpt设置的值稍大就爆token无法继续进行对话。
请重视这个问题，该问题导致qchatgpt完全无法输出较长的内容。

**Comment by YuMingC233** [comment]
我在之前也出现过此类问题：

![image](https://user-images.githubusercontent.com/48896152/224252400-8d9a8e7d-1aa8-4bd2-9a71-edba729630a5.png)

目前我的解决方案是：
注释掉 `config.py` 文件中 `completion_api_params`  下 `max_tokens` 这个参数，让模型以默认的Max_token运行。

问题也很明显，要是大于4096这个阈值，它一样会报错
我个人认为，这个问题只能等待官方扩大max_tokens阈值了 : (

**Comment by slot181** [comment]
大佬，能不能让出现这个错误的时候，让他自己重置？每次都得自己手动重置太难了

**Comment by RockChinQ** [comment]
> 大佬，能不能让出现这个错误的时候，让他自己重置？每次都得自己手动重置太难了

近期在调整计算方式，会优化这个问题

**Comment by RockChinQ** [comment]
实测你们去`config.py`把`completion_api_params`的`max_tokens`字段删了就行了
<img width="276" alt="image" src="https://user-images.githubusercontent.com/45992437/225524480-402dec90-fd1f-44ad-b2bc-0a2394bab68a.png">

**Comment by RockChinQ** [comment]
现关闭此issue，若还有相关问题请开启新issue

**Comment by RockChinQ** [comment]
目前测试使用`gpt-3.5-turbo`模型，删除`max_tokens`字段后，未出现中断的问题，如果此问题仍存在，请提供：问题内容、completion_api_params参数内容、回复内容
