### ISSUE TITLE
[ENHANCE]是否可以优化prompt机制，目前本项目的设定回复只能是“好的”。这影响了prompt的引导效果。

### ISSUE THREAD

**Issue by huluii** [RockChinQ/QChatGPT#261]
是否可以优化prompt机制，目前本项目的设定回复只能是“好的”。这影响了prompt的引导效果。

**Comment by RockChinQ** [comment]
目前正在 #262 中加入以JSON形式的对话内容描述的情景预设，请问是否还设想过其他的解决此issue的方案？

**Comment by RockChinQ** [comment]
将由于 #262 被关闭，请后续升级最新发行版后根据此pr内的说明进行设置
