### ISSUE TITLE
更新版本失败https://api.github.com/repos/RockChinQ/QChatGPT/zipball/v2.2.0[BUG]

### ISSUE THREAD

**Issue by lozn00** [RockChinQ/QChatGPT#268]
请认真按照实际情况填写以下信息！！！！

**运行环境**
window
- 部署方式：
    手动部署
- 系统环境：
window 10 64
- Python环境
Python 3.10.9

**描述漏洞**  
刚刚提示要更新的时候我进行了更新 

**完整报错信息**  
完整的报错信息

[2023-03-12 21:07:35.188] main.py (261) - [INFO] : 程序启动完成,如长时间未显示 ”成功登录到账号xxxxx“ ,并且不回复消息,请查看 https://github.com/RockChinQ/QChatGPT/issues/37
[2023-03-12 21:07:43.007] manager.py (337) - [INFO] : 通知管理员:新版本可用，请发送 !update 进行自动更新
更新日志:
v2.2.0 更好的情景预设
[2023-03-12 21:09:25.817] command.py (165) - [INFO] : [person_35068264]发起指令:!update
[2023-03-12 21:09:25.819] process.py (155) - [INFO] : 回复[person_35068264]文字消息:[bot]正在更新，请耐心等待，请勿重复发起更新...
[2023-03-12 21:09:26.794] updater.py (73) - [INFO] : 更新日志: ['v2.2.0 更好的情景预设', 'v2.1.4 响应规则、敏感词、修复重载bug']
[2023-03-12 21:09:26.795] updater.py (82) - [INFO] : 开始下载最新版本: https://api.github.com/repos/RockChinQ/QChatGPT/zipball/v2.2.0
[2023-03-12 21:09:29.276] updater.py (98) - [INFO] : 下载最新版本完成: temp/updater/v2.2.0.zip
[2023-03-12 21:09:30.071] manager.py (337) - [INFO] : 通知管理员:更新失败:[Errno 2] No such file or directory: '.\\scenario\\default-template.json'

**Comment by RockChinQ** [comment]
> 我给全部覆盖了,
> 
> ```
> [2023-03-12 21:16:43.083] main.py (144) - [WARNING] : [preset_mode]不存在
> [2023-03-12 21:16:43.083] main.py (147) - [WARNING] : 配置文件不完整，请依据config-template.py检查config.py
> [2023-03-12 21:16:43.086] main.py (148) - [WARNING] : 以上配置已被设为默认值，将在5秒后继续启动...
> Database initialized.
> [2023-03-12 21:16:49.600] keymgr.py (62) - [INFO] : 使用api-key:api1
> [2023-03-12 21:16:49.601] manager.py (30) - [INFO] : 文字总使用量：856383
> [2023-03-12 21:16:49.605] manager.py (95) - [INFO] : 加载禁用列表: person: [11111], group: [11111, 11111111]
> [2023-03-12 21:16:49.607] host.py (88) - [INFO] : 加载插件
> [2023-03-12 21:16:49.671] models.py (219) - [INFO] : 插件注册完成: n='BanMassage', d='屏蔽插件，若匹配到关键词则屏蔽，不回复', v=0.1, a='多米诺艾尔' (<class 'plugins.BanMassage.main.HelloPlugin'>)
> [2023-03-12 21:16:49.671] host.py (80) - [INFO] : 加载模块: plugins/BanMassage/main.py 成功
> [2023-03-12 21:16:49.678] host.py (80) - [INFO] : 加载模块: plugins/headers.py 成功
> [2023-03-12 21:16:49.705] models.py (219) - [INFO] : 插件注册完成: n='Hello', d='hello world', v=0.1, a='RockChinQ' (<class 'plugins.randomimg.main.HelloPlugin'>)
> [2023-03-12 21:16:49.706] host.py (80) - [INFO] : 加载模块: plugins/randomimg/main.py 成功
> [2023-03-12 21:16:49.743] models.py (219) - [INFO] : 插件注册完成: n='revLibs', d='接入acheong08/ChatGPT等逆向库', v=0.2.0, a='RockChinQ' (<class 'plugins.revLibs.main.RevLibsPlugin'>)
> [2023-03-12 21:16:49.744] host.py (80) - [INFO] : 加载模块: plugins/revLibs/main.py 成功
> [2023-03-12 21:16:49.751] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/process/proccmd.py 成功
> [2023-03-12 21:16:49.752] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/process/procmsg.py 成功
> [2023-03-12 21:16:49.754] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/process/revss.py 成功
> [2023-03-12 21:16:49.757] host.py (80) - [INFO] : 加载模块: plugins/revLibs/pkg/utils.py 成功
> [2023-03-12 21:16:49.759] host.py (80) - [INFO] : 加载模块: plugins/revLibs/revcfg-template.py 成功
> [2023-03-12 21:16:49.762] host.py (105) - [INFO] : 初始化插件
> [2023-03-12 21:16:49.762] host.py (113) - [INFO] : 插件 BanMassage 已初始化
> [2023-03-12 21:16:49.763] host.py (113) - [INFO] : 插件 Hello 已初始化
> [2023-03-12 21:16:49.766] main.py (69) - [INFO] : [rev] 逆向库初始化成功
> [2023-03-12 21:16:49.767] main.py (81) - [INFO] : [rev] 已将主程序消息处理超时时间设置为10分钟
> [2023-03-12 21:16:49.767] host.py (113) - [INFO] : 插件 revLibs 已初始化
> 2023-03-12 21:16:49 - WARNING  未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
> 仅 HTTP 轮询与正向 WebSocket 可用。
> 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
> 在命令行键入：
>     pip install uvicorn
> 或者
>     pip install hypercorn
> [2023-03-12 21:16:49.772] bot.py (260) - [WARNING] : 未找到可用的 ASGI 服务，反向 WebSocket 和 WebHook 上报将不可用。
> 仅 HTTP 轮询与正向 WebSocket 可用。
> 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。
> 在命令行键入：
>     pip install uvicorn
> 或者
>     pip install hypercorn
> ```
> 
> 这个警告 建议安装 ASGI 服务器，如 `uvicorn` 或 `hypercorn`。pip我无法解决,因为我用的是整合版的python,我进入这个整合版的python的目录pip 安装全是乱码

那就覆盖更新也行了，不用安装这俩
