### ISSUE TITLE
[BUG]机器人掉线重连问题

### ISSUE THREAD

**Issue by xiaoxin6666666** [RockChinQ/QChatGPT#272]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
win11

**描述漏洞**  
就是qq机器人掉线之后无法重连，要手动login重连，然后重连之后发信息过去bot.bat窗口没有反应，也没有进入选择模式，需要手动关闭重新打开bot.bat才行

**完整报错信息**  
完整的报错信息

**Comment by xiaoxin6666666** [comment]
> > 请确认真实情况填写以下信息！！！！
> > **运动环境**
> > 
> > * 部分方式：
> >   自动部分方式
> > * 系统环境：
> >   win11
> > 
> > **Qq机器人是是掉线之后之后无法之后无法无法之后之后之后之后重连手动手动重重重重重重重连重重重重重重重重重重是是是是是是重是重重连重连重连重连重连重连**之后之后之后发过去过去过去过去过去bot.bat.bat窗口窗口窗口
> > **完整报错信息**完整的报错信息
> 
> 这个是YiriMirai问题

好吧

**Comment by RockChinQ** [comment]
压根没法做，yirimirai和nakuru都不能在断连时抛出异常给调用方
