### ISSUE TITLE
[BUG]No such file or directory: 'scenario/default-template.json'

### ISSUE THREAD

**Issue by SkyFutu** [RockChinQ/QChatGPT#275]
自动部署
Windows server 2019
主程序报错，本来正常，在qq使用指令更新失败，回复[bot]更新失败:[Errno 2] No such file or directory: '.\\scenario\\default-template.json'
然后我关掉并再次打开run-bot.bat报错

Traceback (most recent call last):
  File "C:\Users\Administrator\Desktop\QChatGPT\main.py", line 343, in <module>
    shutil.copy("scenario/default-template.json", "scenario/default.json")
  File "shutil.py", line 417, in copy
  File "shutil.py", line 254, in copyfile
FileNotFoundError: [Errno 2] No such file or directory: 'scenario/default-template.json'

**Comment by RockChinQ** [comment]
自动更新的bug，已在最新版修复，请到仓库Release页面下载最新源码压缩包并解压到程序目录以替换内容，配置文件不会被覆盖。
