### ISSUE TITLE
[BUG]场景问题

### ISSUE THREAD

**Issue by Axland233** [RockChinQ/QChatGPT#276]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    Windows Server 2022

**描述漏洞**  
通过!default命令切换场景后，输出内容仍然是默认场景或者是别的场景的内容。重载，使用!reset命令均无效

**完整报错信息**  
无报错

**Comment by RockChinQ** [comment]
提供消息记录以及控制台输出，以及你期望的效果，以便定位问题

**Comment by Axland233** [comment]
好的
第一张是在部分群场景不正常的消息记录
![Screenshot_2023-03-14-13-59-46-672_com tencent mobileqq](https://user-images.githubusercontent.com/91722323/224910130-5746ee84-8acd-46a1-ad4c-be366bc6319d.jpg)
这是我想要的效果
![Screenshot_2023-03-14-14-00-23-348_com tencent mobileqq](https://user-images.githubusercontent.com/91722323/224910365-7873d971-5790-4dfc-a996-2619cdcca640.jpg)
这是我设定的场景
![Screenshot_2023-03-14-14-01-29-603_com microsoft rdc androidx](https://user-images.githubusercontent.com/91722323/224910453-11d85113-0577-47b8-8796-ebcca5abe118.jpg)
这里是主程序控制台输出
![Screenshot_2023-03-14-14-01-14-794_com microsoft rdc androidx](https://user-images.githubusercontent.com/91722323/224910491-0f7a1827-1b7f-4196-b8aa-c40203044291.jpg)

**Comment by Axland233** [comment]
![Screenshot_2023-03-14-14-06-57-966_com microsoft rdc androidx](https://user-images.githubusercontent.com/91722323/224910857-fe99bc8c-3507-4923-9beb-c4b98abaa990.jpg)
再补充一张重载以及重新设定了场景的控制台输出

**Comment by RockChinQ** [comment]
更改情景预设之后不仅要重载，还需要`!reset`使其重置会话，否则使用的仍然是重载之前的前文
