### ISSUE TITLE
不用艾特叫名字机器人自行出现

### ISSUE THREAD

**Issue by JJ448** [RockChinQ/QChatGPT#28]

**Comment by hissincn** [comment]
建议添加唤醒前缀例如！: 或是/chat

**Comment by RockChinQ** [comment]
我在思考到底设计成什么样的，如果仅是在消息中包含特定名字即进行回复很容易实现；
但是在实践中发现，经常是大家在聊一个话题期间就会想就某句话提问机器人，是否有更加符合日常使用的优化方案？

**Comment by D1654** [comment]
命令符号“/”

**Comment by hissincn** [comment]
> 我在思考到底设计成什么样的，如果仅是在消息中包含特定名字即进行回复很容易实现； 但是在实践中发现，经常是大家在聊一个话题期间就会想就某句话提问机器人，是否有更加符合日常使用的优化方案？

我觉得可以让用户**自由设置**
例如：
呼出前缀“/”,"!",":","/chat"....,这些关键词将不被包含在问题正文中，当然@机器人也是这个效果
呼出疑问词"为什么","怎样"，“how to”,"why not"...这些将被包含在问题正文中。
当然以上这些可以让用户自由配置

**Comment by RockChinQ** [comment]
> > 我在思考到底设计成什么样的，如果仅是在消息中包含特定名字即进行回复很容易实现； 但是在实践中发现，经常是大家在聊一个话题期间就会想就某句话提问机器人，是否有更加符合日常使用的优化方案？
> 
> 我觉得可以让用户**自由设置**
> 例如：
> 呼出前缀“/”,"!",":","/chat"....,这些关键词将不被包含在问题正文中，当然@机器人也是这个效果
> 呼出疑问词"为什么","怎样"，“how to”,"why not"...这些将被包含在问题正文中。
> 当然以上这些可以让用户自由配置

感觉不错，疑问词的想法很好
