### ISSUE TITLE
[BUG]消息只能回复一两个字

### ISSUE THREAD

**Issue by Axland233** [RockChinQ/QChatGPT#287]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    Windows Server 2022

**描述漏洞**  
如图所示，从今早上开始，bot不管是什么问题都只能回复一两个字
![Screenshot_2023-03-16-16-58-14-943_com tencent mobileqq](https://user-images.githubusercontent.com/91722323/225565785-a1341a36-ec58-48b0-b346-b9febc2fd7dd.jpg)
排除场景预设问题
![Screenshot_2023-03-16-16-40-25-356_com microsoft rdc androidx](https://user-images.githubusercontent.com/91722323/225565909-daf754f6-f4be-4902-9366-9d900c4cfa5a.jpg)
然后又参考了 #260，均无法解决问题

**完整报错信息**  
无报错信息

**Comment by Axland233** [comment]
顺带补充一下，使用逆向库是正常的

**Comment by RockChinQ** [comment]
bug，请使用!update指令更新到最新版
