### ISSUE TITLE
[BUG] full_scneario模式时，!default指令输出的仍然是默认模式的情景预设

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/QChatGPT#289]

**Comment by chordfish-k** [comment]
暂时可以考虑在 `config.py`中的`default_prompt` 下添加json文件名称，例如有一个`json_default.json`：
```python
default_prompt = {
    "default": "如果我之后想获取帮助，请你说“输入!help获取帮助”",
    "json_default": ""
}
```

**Comment by RockChinQ** [comment]
> 暂时可以考虑在 `config.py`中的`default_prompt` 下添加json文件名称，例如有一个`json_default.json`：
> 
> ```python
> default_prompt = {
>     "default": "如果我之后想获取帮助，请你说“输入!help获取帮助”",
>     "json_default": ""
> }
> ```

我这说的是`!default`指令输出，只显示普通模式的情景预设

**Comment by chordfish-k** [comment]
> > 暂时可以考虑在 `config.py`中的`default_prompt` 下添加json文件名称，例如有一个`json_default.json`：
> > ```python
> > default_prompt = {
> >     "default": "如果我之后想获取帮助，请你说“输入!help获取帮助”",
> >     "json_default": ""
> > }
> > ```
> 
> 我这说的是`!default`指令输出，只显示普通模式的情景预设

对是这样，我暂时的处理方法就是在这里加上这个json预设的介绍，反正在full_scenario模式不会从这里加载(`ε´ )

**Comment by RockChinQ** [comment]
> > > 暂时可以考虑在 `config.py`中的`default_prompt` 下添加json文件名称，例如有一个`json_default.json`：
> > > ```python
> > > default_prompt = {
> > >     "default": "如果我之后想获取帮助，请你说“输入!help获取帮助”",
> > >     "json_default": ""
> > > }
> > > ```
> > 
> > 
> > 我这说的是`!default`指令输出，只显示普通模式的情景预设
> 
> 对是这样，我暂时的处理方法就是在这里加上这个json预设的介绍，反正在full_scenario模式不会从这里加载(`ε´ )

json模式的编写教程我已经写到`config-template.py`了 (cde168c93c5aea9abcb42a0c536964c0cc49921a)

**Comment by chordfish-k** [comment]
> > > > 暂时可以考虑在 `config.py`中的`default_prompt` 下添加json文件名称，例如有一个`json_default.json`：
> > > > ```python
> > > > default_prompt = {
> > > >     "default": "如果我之后想获取帮助，请你说“输入!help获取帮助”",
> > > >     "json_default": ""
> > > > }
> > > > ```
> > > 
> > > 
> > > 我这说的是`!default`指令输出，只显示普通模式的情景预设
> > 
> > 
> > 对是这样，我暂时的处理方法就是在这里加上这个json预设的介绍，反正在full_scenario模式不会从这里加载(`ε´ )
> 
> json模式的编写教程我已经写到`config-template.py`了 ([cde168c](https://github.com/RockChinQ/QChatGPT/commit/cde168c93c5aea9abcb42a0c536964c0cc49921a))

建议在json模板中强调“陈述要求-肯定并复述要求”的对话模式

**Comment by RockChinQ** [comment]
啥意思

**Comment by chordfish-k** [comment]
> 啥意思

就是在assistant回复中对user/system的话语表示肯定并复述，可以达到巩固人格以及跨越限制的效果。这点应该在json编写教程中被提及

**Comment by RockChinQ** [comment]
> > 啥意思
> 
> 就是在assistant回复中对user/system的话语表示肯定并复述，可以达到巩固人格以及跨越限制的效果。这点应该在json编写教程中被提及

嗯，这个是文档方面的东西

**Comment by RockChinQ** [comment]
现在可以clone仓库编辑子模块wiki的内容然后提交，我再更新到wiki中，可以先了解一下git submodule的相关操作

**Comment by RockChinQ** [comment]
已解决，请等待版本更新
