### ISSUE TITLE
[BUG]机器人无法回复消息

### ISSUE THREAD

**Issue by KimiFT** [RockChinQ/QChatGPT#290]
![image](https://user-images.githubusercontent.com/43104582/225636863-773cf127-c501-43c7-abeb-67f7c1928baf.png)
突然变成这样的

**Comment by RockChinQ** [comment]
有可能是cookies过期了，重新取一下

**Comment by RockChinQ** [comment]
若还有问题，请在`config.py`中将`logging_level`设置为`logging.DEBUG`，重启程序，将此报错前的完整的调试级别日志信息贴到这里。

**Comment by KimiFT** [comment]
原问题已解决，不过更新cookies之后消息无法正常显示
![3$F$08`0I{ G0 ZU H_DA@6](https://user-images.githubusercontent.com/43104582/225649793-c766d62d-ba25-4f49-bd3c-145a05cc4ab5.png)
![A}0 ~SS5F7UMR`@_8~NK1XU](https://user-images.githubusercontent.com/43104582/225649834-1d91bf72-61fa-4bd0-952c-23576e3ea09e.png)
后台显示回复内容但是聊天窗口没显示

**Comment by KimiFT** [comment]
![image](https://user-images.githubusercontent.com/43104582/225650055-ca507621-7e1e-4b0f-81d0-3a425a452fbb.png)

**Comment by RockChinQ** [comment]
mirai的bug，可以去mirai的issues反馈一下
