### ISSUE TITLE
[BUG]百度云出错的时候，程序不会返回任何信息

### ISSUE THREAD

**Issue by DannyLI0319** [RockChinQ/QChatGPT#291]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    例如： Windows 10 x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
当百度云判定出错的时候，程序不会返回任何信息。然后，用户不知道，还在等GPT回复，还是程序挂掉了，还是啥。
我猜，现在的逻辑，是不是，如果返回合规，怎么处理，如果返回不合规，怎么处理。个人建议，加一个逻辑，如果返回的既不是合规也不是不合规，抛出一个“百度云出错，请稍后再试”。如果程序丢信息给百度云，30秒收不到返回的结果，也抛一个信息“百度云出错，请稍后再试”。

**完整报错信息**  
![image](https://user-images.githubusercontent.com/120266145/225652016-9f9933ee-03ba-4048-8d66-ee0a2de8e340.png)

**Comment by DannyLI0319** [comment]
这个报错是api的qps，短时间问了太多次。但是我看了，只有1个群，几分钟才问一个问题。
关于这个报错，我在想啊，会不会是，提问，被抛过去一次，回复，也被抛过去一次？然后，百度云看你连续问了2次，就给你报错，说超过qps了。
那么，解决方案，能不能换个思路，**优化下百度云的判断：问的问题，不做百度云判定**，反正一般也不会特别复杂的问题。只在收到的回复，做百度云判定。

**Comment by Haibersut** [comment]
百度云免费的qps是1秒钟请求2次，我后继改成出错发原消息

**Comment by Haibersut** [comment]
看了下你的日记还有我之前写的，应该是有输出才对
```
            if "error_code" in response_dict:
                error_msg = response_dict.get("error_msg")
                logging.warning(f"百度云判定出错，错误信息：{error_msg}")
                conclusion = f"百度云判定出错，错误信息：{error_msg}\n以下是原消息：{message}"
```

有可能是filter.py里面30~34行的问题，你可以注释掉或者只返回false试试。

```
    def is_illegal(self, message: str) -> bool:
        processed = self.process(message)
        if processed != message:
            return True
        return False
```

**Comment by DannyLI0319** [comment]
完整报错截图：
![image](https://user-images.githubusercontent.com/120266145/225677343-9f9d2480-8ff4-43d2-bf63-45d7e97eef2a.png)

**Comment by DannyLI0319** [comment]
试了下，发送一条信息，百度云，同样的信息，好像触发了2次判定：

![image](https://user-images.githubusercontent.com/120266145/225679934-40602f69-0371-466b-9944-0d46618e28df.png)

**Comment by RockChinQ** [comment]
判断两次是因为：逆向库调用了主程序的过滤功能进行判断，而主程序前天修改了消息处理顺序，会判断逆向库返回的消息，所以造成两次判断，这个明天改逆向库插件逻辑；其他问题明天再看。

**Comment by Haibersut** [comment]
报了qps错误消息，返回消息被吞了也是这个问题？

**Comment by RockChinQ** [comment]
> 这个报错是api的qps，短时间问了太多次。但是我看了，只有1个群，几分钟才问一个问题。 关于这个报错，我在想啊，会不会是，提问，被抛过去一次，回复，也被抛过去一次？然后，百度云看你连续问了2次，就给你报错，说超过qps了。 那么，解决方案，能不能换个思路，**优化下百度云的判断：问的问题，不做百度云判定**，反正一般也不会特别复杂的问题。只在收到的回复，做百度云判定。

可以在`config.py`中设置`income_msg_check = False`来关闭用户消息检查

**Comment by RockChinQ** [comment]
逆向库插件目前不再检查敏感词，请使用`!plugin update`更新逆向库插件

**Comment by RockChinQ** [comment]
现已修复重复判定的问题，经过测试，若百度云审核出错，会报出错误
<img width="454" alt="image" src="https://user-images.githubusercontent.com/45992437/226165239-149da19b-9b72-45ec-9025-a96d085607c1.png">
