### ISSUE TITLE
[BUG]关闭百度云审核后，群里没办法回复长信息

### ISSUE THREAD

**Issue by DannyLI0319** [RockChinQ/QChatGPT#293]
请认真按照实际情况填写以下信息！！！！

**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    例如： windows 10 x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
目前观察到，
开启百度云审核，私聊和群信息都正常回复。
关闭百度云审核，群友私聊信息正常回复，群聊信息，如果两三百字以内可以正常回复，太长的话，后台显示有信息过来，机器人不回复。同时沟通有梯子逆向库不再处理长信息。
目前的配置：
Lib：EdgeGPT
Config发送最大值2000，接受最大值4000，长信息设置值256，长信息处理方式转发

**完整报错信息**  
配置截图
![Screenshot_20230317_115000.jpg](https://user-images.githubusercontent.com/120266145/225808220-4ea2ae6b-2b82-4d4c-88e1-1a18f34131c6.jpg)

完整报错截图，可以看到，前面问天气怎么样，有回复。后面问流浪地球，沟通收到回复，但是...，没有回复群里
![Screenshot_20230317_114941.jpg](https://user-images.githubusercontent.com/120266145/225808257-2031a418-ec49-4608-bc6a-b9fd6a3155e9.jpg)

**Comment by RockChinQ** [comment]
现在更新一下逆向库插件之后试试看
