### ISSUE TITLE
[BUG]部分群调用不了历史会话记录

### ISSUE THREAD

**Issue by KimiFT** [RockChinQ/QChatGPT#298]
![image](https://user-images.githubusercontent.com/43104582/226090024-30252734-dc7f-4fa7-8d12-86192aa78623.png)

**Comment by RockChinQ** [comment]
上传一下`database.db`

**Comment by RockChinQ** [comment]
可能是由于消息内包含字符集无法识别的字符导致的，可以使用[`!delhst`指令](https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#%E6%9C%BA%E5%99%A8%E4%BA%BA%E6%8C%87%E4%BB%A4)删除会话历史记录
