### ISSUE TITLE
关于被检测到异常操作从而被封禁的疑问

### ISSUE THREAD

**Issue by MilkWind** [RockChinQ/QChatGPT#302]
手动部署
中国-北京服务器
QChatGPT为最新版本

报错信息：This key is associated with a deactivated account. If you feel this is an error, contact us through our help center at help.openai.com.

开了代理，且按照config.py进行了正确格式配置，但仍然会被封号。
opai似乎可以检测到你是否使用了代理服务器...？

不开代理直接调用APIKey的话会连接超时，但开了代理（挂的美国或是越南节点）再调用的话，最开始是成功的，但很快就会被封号，所以想问一下使用代理调用是不是需要注意一些什么？或是额外配置一些参数？

**Comment by RockChinQ** [comment]
你的代理服务器的节点ip可能被OpenAI列入黑名单，建议你更换网络代理服务商或者使用境外主机部署

**Comment by MilkWind** [comment]
> 

确实是节点的问题，已解决，感谢(*'▽'*)♪

**Comment by Rieko0328** [comment]
> > 
> 
> 确实是节点的问题，已解决，感谢(_'▽'_)♪

可以问一下更换了什么代理吗 我这边也遇到了同样的问题 /(ㄒoㄒ)/~~
