### ISSUE TITLE
[ENHANCE]将chatgpt和bing接入微信

### ISSUE THREAD

**Issue by joe12801** [RockChinQ/QChatGPT#303]
利用PC微信hook项目，可以参考下

下面参加项目 推荐
https://github.com/dualxu/wechat_pc_api
https://github.com/lich0821/WeChatFerry

**Comment by RockChinQ** [comment]
暂时不会考虑，但我们近期这种考虑接入nonebot2框架，此框架支持接入微信的adapter，请关注 https://github.com/users/RockChinQ/projects/2
