### ISSUE TITLE
找不到模块，请问该怎么办呢？

### ISSUE THREAD

**Issue by Cattailglows** [RockChinQ/QChatGPT#305]
Traceback (most recent call last):
  File "D:\桌面\QChatGPT\main.py", line 389, in <module>
    qqbot = main(True)
  File "D:\桌面\QChatGPT\main.py", line 137, in main
    sh = reset_logging()
  File "D:\桌面\QChatGPT\main.py", line 82, in reset_logging
    import pkg.utils.context
ModuleNotFoundError: No module named 'pkg.utils'
![420e82271fbe93](https://user-images.githubusercontent.com/127735632/226165611-3cad35d1-ce11-4124-a1e2-46ec163b061d.png)
![QG9}U`3TC2THZ M4 }TTMM](https://user-images.githubusercontent.com/127735632/226165646-578e6c99-9ded-4179-9973-7ec7f70f788f.png)

**Comment by RockChinQ** [comment]
python版本

**Comment by RockChinQ** [comment]
主机上python环境复杂，建议查看文档手动部署

**Comment by RockChinQ** [comment]
#112
