### ISSUE TITLE
[BUG] 回复信息断点问题仍然存在

### ISSUE THREAD

**Issue by SurviveZ** [RockChinQ/QChatGPT#309]
处理长消息时只回复半截内容，疑似空余token不够导致模型只能部分回复。
请重视

**Comment by RockChinQ** [comment]
相同 #208

**Comment by RockChinQ** [comment]
本问题统一迁移到 #208 跟踪，此issue关闭，请前往 #208 按照以下指引提供日志

> 若仍遇到此问题，请提供控制台输出、开启DEBUG模式(在`config.py`编辑`logging_level = logging.DEBUG`)后的控制台输出、对话内容等信息
