### ISSUE TITLE
[BUG]更新出错

### ISSUE THREAD

**Issue by KimiFT** [RockChinQ/QChatGPT#311]
我使用git更新报错
![image](https://user-images.githubusercontent.com/43104582/226242763-e32d5d99-3469-413b-8146-c12db3bbafbe.png)
![image](https://user-images.githubusercontent.com/43104582/226242785-ab5f0f4c-51a6-4e72-ae01-578b75d11d88.png)

**Comment by RockChinQ** [comment]
目前已经不能使用git更新了，请使用`!update`指令自动更新或从releases页面下载最新版源码解压覆盖
