### ISSUE TITLE
[ENHANCE]允许自行配置指令权限

### ISSUE THREAD

**Issue by 2675hujilo** [RockChinQ/QChatGPT#321]
不是需求建议请勿填写此模板！！！！
消息过滤如何仅回复管理员的指令。非管理员发送的指令不回复？

**Comment by RockChinQ** [comment]
啥意思

**Comment by 2675hujilo** [comment]
！default和！default [指定情景预设为默认]",这两个指令分开设置管理员权限和非管理员权限。
