### ISSUE TITLE
[BUG] 连接bot失败:run() got an unexpected keyword argument 'debug' 自动部署没有安装uvicorn和hypercorn

### ISSUE THREAD

**Issue by DerilJust** [RockChinQ/QChatGPT#322]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    Windows 11

**描述漏洞**  
运行run-bot报错
连接bot失败:run() got an unexpected keyword argument 'debug'
根据自动部署的步骤，没有安装uvicorn和hypercorn，一样是报错了

**完整报错信息**  
main.py (233) - [ERROR] : 连接bot失败:run() got an unexpected keyword argument 'debug', 解决方案: https://github.com/RockChinQ/QChatGPT/issues/82

**Comment by RockChinQ** [comment]
说明你电脑上已经有python了，参考文档手动部署一下吧

**Comment by DerilJust** [comment]
那我直接在服务器部署试一下
