### ISSUE TITLE
[BUG]！last无法正常使用

### ISSUE THREAD

**Issue by lk343** [RockChinQ/QChatGPT#328]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
     Windows 11

**描述漏洞**  
！last 只能切换前两个会话，无法切换到第三个

**Comment by RockChinQ** [comment]
![1679842494645](https://user-images.githubusercontent.com/45992437/227784183-52ac603d-e9c1-4ca6-8fa2-420fd997978d.png)

我这里测试未发现此问题，请尝试更新程序后再测试，若仍有此问题，请带上消息记录、!list指令输出等更多信息回复此issue

**Comment by lk343** [comment]
今天更新了一下就好了！
