### ISSUE TITLE
[ENHANCE] Azure OpenAI service 接入

### ISSUE THREAD

**Issue by yoo-bit** [RockChinQ/QChatGPT#329]
建议增加ChatGPT service On Azure 支持，[Azure OpenAI service](https://azure.microsoft.com/en-in/products/cognitive-services/openai-service/)

**Comment by RockChinQ** [comment]
这是什么

**Comment by yoo-bit** [comment]
就是微软提供的Azure集成ChatGpt的服务，https://github.com/zhayujie/chatgpt-on-wechat有做支持（参考1.1 ChapGPT service On Azure），能不能也集成到QQ啊😃

**Comment by RockChinQ** [comment]
好的，我先了解一下

**Comment by aseer01** [comment]
我粗略地修改了一下，只需要在pkg\openai\modelmgr.py的开头加上这么几句：
```
openai.api_type = "azure"
openai.api_base = "你的azure终结点"
openai.api_version = "2023-03-15-preview"
```
然后再在config.py里的completion_api_params补上`"engine":"你的模型部署名称"`
再把api_key改成自己的密钥就可以了
