### ISSUE TITLE
[Bug]: 填写了反向代理，但是发送消息只回复了参数错误:Invalid URL (POST /chat/completions

### ISSUE THREAD

**Issue by hexiang-x** [RockChinQ/QChatGPT#335]
### 部署方式

Docker部署

### 系统环境

ubuntu20.04

### Python环境

python3.9

### 异常情况

参数错误:Invalid URL (POST /chat/completions）

### 报错信息

参数错误:Invalid URL (POST /chat/completions

**Comment by hexiang-x** [comment]
> 

好的，感谢，请问key需要改吗？现在提示我的key是错的，但是我在kook上搭的机器人可以用。

**Comment by RockChinQ** [comment]
> > 
> 
> 好的，感谢，请问key需要改吗？现在提示我的key是错的，但是我在kook上搭的机器人可以用。

key跟这个无关，报错是其他问题

**Comment by hexiang-x** [comment]
加上v1
