### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by supersun3757** [RockChinQ/QChatGPT#341]
### 部署方式

Docker部署

### 系统环境

Centos 7.6

### Python环境

python 

### 异常情况

正常按照dockers部署，最后QChatGPT部署时报错。
` docker run  -it -p 8080:8080  --name mcl   --network host   -v ${PWD}/:/QChatGPT  mikumifa/qchatgpt-docker`
是在QChatGPT目录下输入的

### 报错信息

![image](https://user-images.githubusercontent.com/72365603/228444984-25a0f27c-ee16-4049-a549-61864ce1a435.png)
![image](https://user-images.githubusercontent.com/72365603/228445405-e7a36998-aa7a-4fce-9a53-6bf425c39bec.png)
![image](https://user-images.githubusercontent.com/72365603/228445447-8b4fcb9b-c482-4692-9099-3f1027840901.png)

**Comment by RockChinQ** [comment]
参考 #127，https://github.com/mikumifa/QChatGPT-Docker-Installer/issues/11
