### ISSUE TITLE
[Bug]: No module named 'requests'

### ISSUE THREAD

**Issue by CBEpt** [RockChinQ/QChatGPT#343]
### 部署方式

一键安装包部署

### 系统环境

winserver

### Python环境

3.10

### 异常情况

本地win可以正常运行。。打包之后，放到winserver解压 就报错如图。。

### 报错信息

![image](https://user-images.githubusercontent.com/103420806/228595280-8bbe29ad-8a98-4809-aec7-0215f5a7d70c.png)

**Comment by RockChinQ** [comment]
https://github.com/RockChinQ/qcg-installer/issues/15 ，参考这个执行`python/Scripts/pip.exe install requests`

**Comment by CBEpt** [comment]
![image](https://user-images.githubusercontent.com/103420806/228723955-154556d1-3ec0-48d9-a713-9ca3ac69c977.png)
还是报错。。

**Comment by RockChinQ** [comment]
根据文档使用手动部署



---Original---
From: ***@***.***&gt;
Date: Thu, Mar 30, 2023 11:49 AM
To: ***@***.***&gt;;
Cc: "Rock ***@***.******@***.***&gt;;
Subject: Re: [RockChinQ/QChatGPT] [Bug]: No module named 'requests' (Issue#343)




 

 还是报错。。

**Comment by CBEpt** [comment]
已解决，感谢。
