### ISSUE TITLE
[Bug]: 关键词匹配无法匹配开头空格。

### ISSUE THREAD

**Issue by 2675hujilo** [RockChinQ/QChatGPT#345]
### 部署方式

一键安装包部署

### 系统环境

win10

### Python环境

python3.10

### 异常情况

关键词匹配无法匹配到开头空格。
![image](https://user-images.githubusercontent.com/113016971/228636416-c405fbf2-0318-4126-ac75-f7e5d2953e4b.png)

**Comment by 2675hujilo** [comment]
![image](https://user-images.githubusercontent.com/113016971/228636790-f33a404d-f3c5-454c-a4ca-79922bd9a4c9.png)
开头空格无法识别。其他字符正常

**Comment by 2675hujilo** [comment]
因为空格是很容易打出来的符号，相比都好句号，就在键盘下方，很容易打出来，和机器人交流也很方便，所以要用空格

**Comment by RockChinQ** [comment]
这个是特性，程序在接受到消息时会删除消息前后的空格以及换行，因为某些设备（如iPad）发出的消息前方自带一个空格，这样会导致非匹配空格的响应规则无法使用
