### ISSUE TITLE
[Feature]: urlikethisijustsix 插件在群聊的使用

### ISSUE THREAD

**Issue by CBEpt** [RockChinQ/QChatGPT#347]
### 这是一个？

现有功能优化

### 详细描述

现在必须加上gpt触发关键词（如@或者ai）才能回复。。比如群友a必须输入 ai fuck you，机器人才会回复他，而直接在群里骂fuck you，这个插件就不会响应

不知道可不可以修改为只要检测到有任何人骂人（不包含触发关键词ai等），就自动回复他'好好好', "啊对对对", "好好好好", "你说得对", "谢谢夸奖"？

**Comment by RockChinQ** [comment]
这个功能需要更改插件绑定的监听器，作为一个示例插件，此插件不会再更改功能；你可以参考插件内容以及本仓库wiki中的插件开发页自行编写插件实现此功能
