### ISSUE TITLE
自定义消息提示语

### ISSUE THREAD

**Issue by 2675hujilo** [RockChinQ/QChatGPT#353]
### 这是一个？

现有功能优化

### 详细描述

希望可以自定义消息错误提示
比如在config.py界面加入reply_message，replys_message，command_err_message等字段。

QChatGPT/pkg/qqbot/manager.py
私聊消息超时提示,line:271
reply_message = "超时提醒。"

群聊消息超时提示,line:310
replys_message = "超时提醒。"

QChatGPT/pkg/qqbot/command.py，line:57
指令权限不足/无效提示
command_err_message = "指令权限不足/无效提示 "

#QChatGPT/pkg/qqbot/cmds/mgr.py， line :265,278
raise CommandPrivilegeError('权限不足: {}'.format(path))
raise CommandPrivilegeError('找不到指令: {}'.format(path))

**Comment by RockChinQ** [comment]
此issue由于重复将关闭，请跟踪 #310
