### ISSUE TITLE
大佬安装器怎么直接调用new bing模型啊

### ISSUE THREAD

**Issue by theManOfNB** [RockChinQ/QChatGPT#358]
windows系统用的安装器，安好之后没有openAI账号，想要直接用new bing，但是不知道怎么配置，求教

**Comment by RockChinQ** [comment]
看README.md的最前方公告里的插件链接

**Comment by theManOfNB** [comment]
那个机器人是要自己用mirai登陆吗

**Comment by RockChinQ** [comment]
> 那个机器人是要自己用mirai登陆吗

对的，按照文档操作

**Comment by theManOfNB** [comment]
请问mirai登陆的是自己的号还是随便填的号
