### ISSUE TITLE
[Bug]: 配置出错，不按照config回复

### ISSUE THREAD

**Issue by SkyFutu** [RockChinQ/QChatGPT#363]
### 部署方式

一键安装包部署

### 系统环境

windows  server 2019

### Python环境

py 3.10 自动部署

### 异常情况

更新新版本后出现的问题，config里的自定义help没有回复，然后!usage也没有回复剩下额度和使用额度，新版本问题，还有我上个提出的编码问题大佬你还没有确认
![QQ图片20230401235746](https://user-images.githubusercontent.com/119418823/229301327-15d5fe7a-555a-4f95-812e-eee6bbc642ec.png)
![QQ图片20230401235751](https://user-images.githubusercontent.com/119418823/229301328-3e10c071-73c5-40a9-a79c-7f0c643fa2bb.png)

**Comment by RockChinQ** [comment]
help命令现在仅输出支持的命令列表，之后将`help_message`的内容加回来，使用额度的接口这几天没法用了，之后考虑删除获取额度的功能

**Comment by RockChinQ** [comment]
现已回复`!help`命令对`help_message`的使用，改为使用`!cmd`命令查看命令说明
