### ISSUE TITLE
建议统一doc string格式

### ISSUE THREAD

**Issue by zyckk4** [RockChinQ/QChatGPT#367]
### 这是一个？

现有功能优化

### 详细描述

简单查看了本项目代码，建议统一doc string的格式，规则为
1.使用双引号"""
2.对于单行文字，前后的引号都不单独成行，一起写成一行
3.对于多行文字，前面的引号不单独成行和第一行文字写一起就好，后面的引号单独成行
4.引号"""和文字间不加空格
5.对于要在函数doc string中写参数和返回的，考虑确定选择一种doc string模板，不要混用:param:和Args:,Return:两种格式

**Comment by RockChinQ** [comment]
感谢关注！近期事务繁多，无暇顾及请见谅，欢迎持续提交pr以优化注释和代码规范。
