### ISSUE TITLE
README.md的“手动部署”部分似乎有小问题

### ISSUE THREAD

**Issue by zyckk4** [RockChinQ/QChatGPT#375]
### 这是一个？

现有功能优化

### 详细描述

在README.md的如下部分：
>2. 安装依赖

>```bash
>pip3 install yiri-mirai openai colorlog func_timeout dulwich Pillow
>```

似乎缺少了requests库？

**Comment by RockChinQ** [comment]
yirimirai会自动安装websockets 9.x

**Comment by zyckk4** [comment]
> yirimirai会自动安装websockets 9.x

**requests** 库

**Comment by zyckk4** [comment]
@RockChinQ .github/workflows/update-cmdpriv-template.yml里好像也缺requests库

**Comment by RockChinQ** [comment]
> @RockChinQ .github/workflows/update-cmdpriv-template.yml里好像也缺requests库

这个无伤大雅，那里安装只是为了脚本能成功导入各指令模块
