### ISSUE TITLE
[Bug]: docker部署 登录成功 但是没有回复

### ISSUE THREAD

**Issue by alanchange** [RockChinQ/QChatGPT#377]
### 部署方式

Docker部署

### 系统环境

群晖docker

### Python环境

3.8.12

### 异常情况

bot登录成功
![image](https://user-images.githubusercontent.com/129581823/230090493-254a0f62-ffdd-41f7-8960-ae5b44f5b60c.png)
mirai可以接受到信息
![image](https://user-images.githubusercontent.com/129581823/230090756-ba9d3093-2a1c-4007-b781-e9e3a74c6d37.png)

**Comment by RockChinQ** [comment]
请使用Python 3.9以上版本

**Comment by RockChinQ** [comment]
实在不行建议手动部署

**Comment by RockChinQ** [comment]
这可能是一个程序漏洞或依赖库漏洞，统一到 #376 跟踪
