### ISSUE TITLE
[Feature]: BOT提示有错字

### ISSUE THREAD

**Issue by 7980963** [RockChinQ/QChatGPT#378]
### 这是一个？

现有功能优化

### 详细描述

[bot]err: 此命令已启用(弃用)，请使用 !plugin get <插件仓库地址> 进行安装
无伤大雅，但是还是改一下比较好。

**Comment by 7980963** [comment]
竟然把指令改了，那么顺手把wiki也给改一下吧，嘻嘻
https://github.com/RockChinQ/QChatGPT/wiki/%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8#plugin-%E6%8C%87%E4%BB%A4

**Comment by 7980963** [comment]
既然把指令改了，那么顺手把wiki给改一下吧，嘻嘻
https://github.com/RockChinQ/QChatGPT/wiki/%E6%8F%92%E4%BB%B6%E4%BD%BF%E7%94%A8#plugin-%E6%8C%87%E4%BB%A4

**Comment by RockChinQ** [comment]
已修改，感谢关注！
