### ISSUE TITLE
切换gpt3（text-davinci-003）模型时，回复不完整问题

### ISSUE THREAD

**Issue by SAKANA3Y3** [RockChinQ/QChatGPT#379]
### 部署方式

手动部署

### 系统环境

Ubuntu22.04.2 LTS amd64

### Python环境

python3.10

### 异常情况

切换GPT3后，回复文字不完整，使用!resend命令重新回答也一样
![Screenshot_20230406-075102](https://user-images.githubusercontent.com/122886136/230239434-669e4749-7a58-411b-a8b8-2e83e92f314c.png)
![Screenshot_20230406-075336](https://user-images.githubusercontent.com/122886136/230239466-5a2b47bb-256d-411a-9bda-ed88bb18eb72.png)

### 报错信息

控制台没有报错

**Comment by RockChinQ** [comment]
Switcher插件目前可以在切换时自动调整max_tokens，可以更新一下
