### ISSUE TITLE
[BUG] mirai登录时提示版本过低：当前QQ版本过低，请升级至最新版本后再登录。点击进入下载页面

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/QChatGPT#38]
mirai方面问题，见[此issue](https://github.com/mamoe/mirai/issues/2323)

**Comment by 24779987** [comment]
1. 删除mirai/bots/目录，重启mirai后重新登录机器人QQ ### 不行执行继续2 的操作
2. 删除mirai/bots目录 启动 mirai 输入以下命令:       ### 不要带 < > 修改协议为安卓手表登录或更换其他协议登录，重启mirai登录 ，也可以进入mirai/config/Console/目录编辑AutoLogin.yml，自行参考文件内注释修改，查看协议。
autologin add <机器人QQ号> <机器人密码>
autologin setConfig <机器人QQ号> protocol ANDROID_WATCH

**Comment by RockChinQ** [comment]
解决办法详细 #137

**Comment by 24779987** [comment]
1. 删除mirai/bots/目录，重启 mirai 后重新登录机器人QQ      ### 还是提示版本问题的话执行 2 的操作
2. 删除mirai/bots/目录  启动 mirai   输入以下命令:  

    autologin add <机器人QQ号> <机器人密码>             ###  不要带 < > 
    autologin setConfig <机器人QQ号> protocol <ANDROID_WATCH>          ### 不要带 < >

    修改协议为安卓手表登录，或修改  <ANDROID_WATCH>  为其他协议登录。 
    
    "protocol": "ANDROID_PHONE" / "ANDROID_PAD" / "ANDROID_WATCH" / "MACOS" / "IPAD"
    
    重启 mirai 会自动登录。

    也可以进入mirai/config/Console/目录编辑AutoLogin.yml，自行参考文件内注释查看并修改自动登录和协议。
3. 更换机器人QQ号
