### ISSUE TITLE
[Feature]: 建议加入API2D的中转key支持

### ISSUE THREAD

**Issue by wenyinos** [RockChinQ/QChatGPT#380]
### 这是一个？

新功能

### 详细描述

通过第三方访问openAI的接口，国内大部分地区可用，支持常用支付手段（价格为OpenAI官方1.5倍）

[https://api2d.com/wiki/doc](url)

示例：[http://chat.wenyinos.com](url)

**Comment by RockChinQ** [comment]
建议自行编写插件实现
