### ISSUE TITLE
[Bug]: 始终没反应，已经成功登录了

### ISSUE THREAD

**Issue by Szeroy** [RockChinQ/QChatGPT#382]
### 部署方式

安装器部署

### 系统环境

window10

### Python环境

安装器自带版本

### 异常情况

已经成功登录了，账号也对过好几遍，用的方法是auto的登录方法，但是发消息给机器人毫无反应，命令行里面也没有其他响应，尝试在http_proxy添加代理"http://localhost:1080"，也没有任何反应，gpt的key也填进去了，不知道什么原因

### 报错信息

![微信截图_20230406204320](https://user-images.githubusercontent.com/61006429/230382021-36a16dee-3bea-4692-a468-f5e2ebbead03.png)

**Comment by RockChinQ** [comment]
这可能是一个程序漏洞或依赖库漏洞，统一到 #376 跟踪
