### ISSUE TITLE
[Bug]:插件revLibs初始化时发生错误: (<class 'NameError'>, NameError("name 'ConversationStyle' is not defined"), <traceback object at 0x000001F980871680>)

### ISSUE THREAD

**Issue by KimiFT** [RockChinQ/QChatGPT#386]
### 部署方式

手动部署

### 系统环境

windows 10

### Python环境

Python 3.11

### 异常情况

初始化插件发生错误
![image](https://user-images.githubusercontent.com/43104582/230437246-6f969eee-85a8-4a52-8c52-cbc49880fda7.png)

**Comment by RockChinQ** [comment]
往你revcfg.py最前方加一行
```python
from EdgeGPT import ConversationStyle
```
