### ISSUE TITLE
[Bug]: 吞消息

### ISSUE THREAD

**Issue by 2675hujilo** [RockChinQ/QChatGPT#387]
### 部署方式

一键安装包部署

### 系统环境

win10

### Python环境

python3.10

### 异常情况

![image](https://user-images.githubusercontent.com/113016971/230539268-d7a24c77-7288-4cfe-8a6b-1358373b64b7.png)
消息回复了但是没完全回复

**Comment by RockChinQ** [comment]
整条消息没法出去？

**Comment by 2675hujilo** [comment]
> 整条消息没有发出去？

bot控制台显示发出去了，但是miriai控制台并没有收到，qq也没收到回复。长消息经常遇到这种情况。

**Comment by RockChinQ** [comment]
试一下重启程序、更换长消息处理策略。  
这种情况一般是mirai的问题

**Comment by 2675hujilo** [comment]
重启后，隔一段时间，就会又出现这种情况。

# 应用长消息处理策略的阈值
# 当回复消息长度超过此值时，将使用长消息处理策略
blob_message_threshold = 256

# 长消息处理策略
# - "image": 将长消息转换为图片发送
# - "forward": 将长消息转换为转发消息组件发送
blob_message_strategy = "forward"

**Comment by RockChinQ** [comment]
那指定是mirai问题了

**Comment by qq466627701** [comment]
blob_message_threshold这个值是以byte计算吗？

**Comment by RockChinQ** [comment]
> blob_message_threshold这个值是以byte计算吗？

python的len函数统计
