### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by ZHmQAQ** [RockChinQ/QChatGPT#389]
### 部署方式

一键安装包部署

### 系统环境

Win10

### Python环境

Python 3.10

### 异常情况

运行 run-bot.bat 

弹出这行语句之后
Requirement already satisfied: openai in c:\users\chatbot1\desktop\mirai\python\lib\site-packages (0.27.2)

无限循环这行语句
WARNING: Retrying (Retry(total=4, connect=None, read=None, redirect=None, status=None)) after connection broken by 'ProxyError('Cannot connect to proxy.', TimeoutError('_ssl.c:980: The handshake operation timed out'))': /simple/openai/

**Comment by RockChinQ** [comment]
到`config.py`设置`upgrade_depenencies = False`
