### ISSUE TITLE
[Bug]: 插件安装后使用!plugin命令依旧显示插件为0

### ISSUE THREAD

**Issue by FUSLUN** [RockChinQ/QChatGPT#392]
### 部署方式

安装器部署

### 系统环境

win11

### Python环境

python3.10.11

### 异常情况

我的问题是这样的，机器人本体功能运作是正常的，但在想使用ChatWaifu插件时出了问题，不论是手动下载安装还是用!plugin get命令下载都没有正常工作，使用!plugin命令也显示插件0，同时出现下面的报错，把插件作者提供的model扔到根目录里并删掉了不要的插件之类都做了，也安装了requirements.txt的依赖，还是没法解决问题。
最后试着安装了差不多功能的chat_voice，按作者写得步骤做完也遭遇了差不多的情况，一样显示插件为0。大大能有空看一下吗

### 报错信息

[2023-04-08 01:36:16.711] host.py (83) - [ERROR] : 加载模块: plugins/QChatPlugins/ChatWaifu/main.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'scipy'"), <traceback object at 0x000001A5DE5E5FC0>)

**Comment by FUSLUN** [comment]
plugins目录下的switch.json文件里设置填好之后，一启动机器人就会重新变成空白

**Comment by RockChinQ** [comment]
热重载或者重启了吗？

**Comment by RockChinQ** [comment]
你这个插件是能被加载的，但是缺少了插件的依赖库，这可能是插件的问题，可以前往插件的仓库反馈一下

**Comment by FUSLUN** [comment]
好的，大佬，我去试试
