### ISSUE TITLE
[Bug]: 请问大佬，在网络不稳定的情况下，后台从api接受到的文本信息不会被机器人转发出去，是因为被判定为废弃信息了吗，我应该修改哪个文件的哪个函数来防止这种事情发生呢？

### ISSUE THREAD

**Issue by BuMing119** [RockChinQ/QChatGPT#393]
### 部署方式

一键安装包部署

### 系统环境

windows 10

### Python环境

python 3.10

### 异常情况

请问大佬，在网络不稳定的情况下，后台从api接受到的文本信息不会被机器人转发出去，是因为被判定为废弃信息了吗，我应该修改哪个文件的哪个函数来防止这种事情发生呢？

**Comment by RockChinQ** [comment]
#387 ，mirai的bug，请前往mirai的仓库查找解决办法或反馈
