### ISSUE TITLE
[Bug]: 没有回复消息

### ISSUE THREAD

**Issue by SkyFutu** [RockChinQ/QChatGPT#395]
### 部署方式

一键安装包部署

### 系统环境

windows  server 2019

### Python环境

py 3.10 自动部署

### 异常情况

控制台有回复，但是聊天却回复超时，mirai api貌似没接收消息
![QQ图片20230408120314](https://user-images.githubusercontent.com/119418823/230702381-a3481aa2-fa22-4828-b01d-79a6295ab53d.png)
![QQ图片20230408120319](https://user-images.githubusercontent.com/119418823/230702382-cc066542-427e-4c64-a97c-4f5bea8c389e.jpg)
![QQ图片20230408120323](https://user-images.githubusercontent.com/119418823/230702383-43bf3e49-12bb-4b08-bf13-c0b38c89d9a5.png)

**Comment by 7980963** [comment]
确实有类似的情况，短消息基本上没问题，长消息基本上超时。

**Comment by RockChinQ** [comment]
短消息没问题，长消息超时问题应该是因为OpenAI服务器太卡，可以尝试在`config.py`把超时时间设置得更高

**Comment by SkyFutu** [comment]
> 短消息没问题，长消息超时问题应该是因为OpenAI服务器太卡，可以尝试在`config.py`把超时时间设置得更高

是的，这就是解决方法
