### ISSUE TITLE
[Feature]: 查询当前OpenAI账号余额

### ISSUE THREAD

**Issue by wenyinos** [RockChinQ/QChatGPT#396]
### 这是一个？

新功能

### 详细描述

接口调用方法：https://community.openai.com/t/get-the-remaining-credits-via-the-api/18827/5
API2D亦可使用，见https://api2d.com/wiki/doc#api

**Comment by RockChinQ** [comment]
曾在 cbab824f 支持通过此接口获取额度，并由于该接口失效已在 9edb32b0 删除此功能
