### ISSUE TITLE
自定义!cmd

### ISSUE THREAD

**Issue by SkyFutu** [RockChinQ/QChatGPT#398]
### 这是一个？

现有功能优化

### 详细描述

希望能自定义!cmd，这样可以把Qchatgpt插件和mirai插件的指令都统一归纳

**Comment by RockChinQ** [comment]
涉及到插件管理模块重构以及多模块解耦重构，预计将在`2.5.0`实现

**Comment by RockChinQ** [comment]
已支持命令组件扩展，这种方式的命令支持将帮助信息显示到 `!cmd`命令中，请等待 v3.1 发布后查看文档中的组件扩展方式。

**Comment by SkyFutu** [comment]
难绷，我自己已经写了个help插件了

**Comment by RockChinQ** [comment]
因为!cmd命令的响应都是程序自动生成的，所以单独附加自定义内容会破坏单一性原则~
