### ISSUE TITLE
[BUG]运行run-bot.bat 后出现python.exe mian.py后直接闪退

### ISSUE THREAD

**Issue by LancelotLamp** [RockChinQ/QChatGPT#42]
**运行环境**
- 部署方式：
    自动部署
- 系统环境：
    e,g, win10

**描述漏洞**
run-mirai 登录成功后运行run-bot出现python.exe mian.py直接闪退

**完整报错信息**

**Comment by RockChinQ** [comment]
查看 https://github.com/RockChinQ/qcg-installer/issues/2

**Comment by LancelotLamp** [comment]
更新过了依旧无用，前两天老版本可用，下了新版本后出现

**Comment by RockChinQ** [comment]
你是前几天正常使用了，然后现在更新了用不了了？你是怎么进行更新的？
