### ISSUE TITLE
[Feature]: mirai可以换成2.15吗

### ISSUE THREAD

**Issue by lftny** [RockChinQ/QChatGPT#420]
### 这是一个？

新功能

### 详细描述

更新了miari之后，
![image](https://user-images.githubusercontent.com/130929472/232735420-7bb6eade-1ee4-414b-91f1-644f7a5da0a0.png)
j就无法靠这个启动了，
![image](https://user-images.githubusercontent.com/130929472/232735542-b7859f5a-8c8d-4a44-8902-934b8707fafa.png)

**Comment by RockChinQ** [comment]
自行根据 mamoe/mirai 的文档部署mirai或进行升级，然后保证mirai-api-http插件已安装并正确按照本项目要求配置即可。
