### ISSUE TITLE
[Bug]: 自定义报错没了

### ISSUE THREAD

**Issue by McPeter111** [RockChinQ/QChatGPT#425]
### 部署方式

手动部署

### 系统环境

windows

### Python环境

py310

### 异常情况

![DE8BA1F4-047A-4DDD-85FD-2F4B10593F2D](https://user-images.githubusercontent.com/121279581/233778004-a8e84f77-f890-4c79-bac3-aa558dffd307.jpeg)

**Comment by RockChinQ** [comment]
这就是你自定义的报错，报错信息自定义已迁移到tips.py

**Comment by McPeter111** [comment]
彳亍
