### ISSUE TITLE
不知道是正向通讯还是什么

### ISSUE THREAD

**Issue by seagullz4** [RockChinQ/QChatGPT#432]
请把go-cqhttp的通讯协议写详细一点，qq那行又不知道填不填

**Comment by RockChinQ** [comment]
你可以帮助完善res/wiki/下的说明文件并提交pr

**Comment by Luoyongping** [comment]
main.py (275) - [CRITICAL] : 程序启动完成,如长时间未显示 "Protocol: connected" ,并且不回复消息,请检查config.py中的nakuru_config是否正确
卡在这里了，难受

**Comment by RockChinQ** [comment]
关于 连接不上go-cqhttp的问题，请统一前往 #460 查看解决步骤
