### ISSUE TITLE
[BUG]登录mirai的时候使用ticket登录仍然存在安全问题。

### ISSUE THREAD

**Issue by jiushanmen** [RockChinQ/QChatGPT#44]
**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
    e.g. Centos x64
- Python环境（仅手动部署填写）：
    e.g. Python 3.10.9

**描述漏洞**
12月14日时，使用mirai登录无问题。

16日登录mirai发现需要重新验证。
使用ticket验证后，mirai仍然无法登录。

**完整报错信息**
![image](https://user-images.githubusercontent.com/120302494/208053441-7e078735-2997-49d1-8aba-cb450026d3a1.png)

**Comment by RockChinQ** [comment]
https://github.com/mamoe/mirai/issues/2117

**Comment by jiushanmen** [comment]
把2117的全部功能测试了一遍，没有办法能够解决此问题。已经把qq号删除，尝试注册新号以解决。

**Comment by jiushanmen** [comment]
重新注册了一个qq，成功了。
