### ISSUE TITLE
[Feature]: 如何对CFG中的某项的子项进行修改

### ISSUE THREAD

**Issue by p6oy** [RockChinQ/QChatGPT#443]
### 这是一个？

现有功能优化

### 详细描述

文档中并未找到，例如对apikey进行修改

**Comment by RockChinQ** [comment]
直接在config.py改就行了

**Comment by RockChinQ** [comment]
!cfg指令的话请使用dict形式发送，例如

```
!cfg openai_config {
    "api_key": "xxxxx"
}

**Comment by p6oy** [comment]
我希望可以通过QQ直接更改，例如!cfg openai_config.api_key.default sk-xxx



***@***.***
 
发件人： Rock Chin
发送时间： 2023-04-26 17:59
收件人： RockChinQ/QChatGPT
抄送： p6oy; Author
主题： Re: [RockChinQ/QChatGPT] [Feature]: 如何对CFG中的某项的子项进行修改 (Issue #443)
直接在config.py改就行了

**Comment by RockChinQ** [comment]
> 我希望可以通过QQ直接更改，例如!cfg openai_config.api_key.default sk-xxx ***@***.*** 发件人： Rock Chin 发送时间： 2023-04-26 17:59 收件人： RockChinQ/QChatGPT 抄送： p6oy; Author 主题： Re: [RockChinQ/QChatGPT] [Feature]: 如何对CFG中的某项的子项进行修改 (Issue #443) 直接在config.py改就行了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***>

可以考虑添加

**Comment by RockChinQ** [comment]
已实现，将在下一个版本生效
