### ISSUE TITLE
[Bug]: 无法使用cq-http

### ISSUE THREAD

**Issue by pingguo114514** [RockChinQ/QChatGPT#445]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Windown10

### Python环境

Python 3.10

### 异常情况

程序启动完成,长时间未显示 "Protocol: connected" ,并且不回复消息,并且config.py中的nakuru_config配置正确,并且cq-http后台也没有任何提示

**Comment by RockChinQ** [comment]
麻烦提供一下go-cqhttp的输出以及根据 #402 开启调试模式后的主程序输出

**Comment by a1014068504** [comment]
![image](https://user-images.githubusercontent.com/45983488/234753757-a9993838-847b-4759-a666-d1ff39559451.png)
![image](https://user-images.githubusercontent.com/45983488/234753931-4508fca6-7dc1-42f5-a597-f69e1d1f5d8b.png)
使用docker部署。程序启动之后，就会一直卡在这里,没有后文了。go-cqhttp也没有接受到任何连接请求。
从QQ发送消息也不会有有消息

**Comment by RockChinQ** [comment]
请提供go-cqhttp的完整输出

**Comment by a1014068504** [comment]
邮件已收到~

**Comment by a1014068504** [comment]
![image](https://user-images.githubusercontent.com/45983488/234755437-fdfc8724-974b-44e1-9fda-9be60c70545c.png)
这是从启动go-cqhttp到处理消息的整个日志。反向连接那个是另一个应用在使用，可以不用关心。

**Comment by RockChinQ** [comment]
> ![image](https://user-images.githubusercontent.com/45983488/234755437-fdfc8724-974b-44e1-9fda-9be60c70545c.png)
> 这是从启动go-cqhttp到处理消息的整个日志。反向连接那个是另一个应用在使用，可以不用关心。

未按照文档正确选择gocq的监听协议，请仔细按照本仓库wiki中的gocq配置说明开启正向http和正向ws接口

**Comment by a1014068504** [comment]
![image](https://user-images.githubusercontent.com/45983488/234756618-2233b867-f93d-49c4-aed1-5450bf5fe5ec.png)
![image](https://user-images.githubusercontent.com/45983488/234756672-ba70ce9e-3b0f-4a98-a3c5-d7fca4bf285d.png)
这是开启开启正向http的截图。就如[pingguo114514] 一样。没有任何响应

**Comment by RockChinQ** [comment]
如果你gocq和主程序在一个主机上，建议你把config.py中nakuru_config那个host设置为localhost，否则你需要检查host指定ip的可达性，尝试ping一下看看通不通

**Comment by a1014068504** [comment]
不在一个主机上。
![image](https://user-images.githubusercontent.com/45983488/234757160-23029048-aeb6-4d18-822d-db921b290718.png)
而且通过容器去连接telnet端口是通的.

**Comment by pingguo114514** [comment]
<img width="972" alt="无标题" src="https://user-images.githubusercontent.com/109885180/234852612-a555e175-0ef5-4d7c-b1a0-fb08c0a4277e.png">
![新建位图图像](https://user-images.githubusercontent.com/109885180/234852667-cc9d2cbf-8004-4396-8340-d3959e400fb9.png)

**Comment by RockChinQ** [comment]
自行检查一下网络连通性

**Comment by pingguo114514** [comment]
发现把地址改成localhost就行了......
但是
<img width="356" alt="无标题" src="https://user-images.githubusercontent.com/109885180/234862926-0f2bd755-2106-438b-9306-2fb48f27853a.png">
