### ISSUE TITLE
[Bug]: API参数调用错误

### ISSUE THREAD

**Issue by pingguo114514** [RockChinQ/QChatGPT#446]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Windows10

### Python环境

Python3.10

### 异常情况

<img width="356" alt="无标题" src="http://user-images.githubusercontent.com/109885180/234862926-0f2bd755-2106-438b-9306-2fb48f27853a.png">

### 报错信息

<img width="711" alt="无标题" src="https://user-images.githubusercontent.com/109885180/234878350-c6041186-b780-4abe-b541-e207ef82ed2a.png">

**Comment by RockChinQ** [comment]
看看你的config.py中的completion_api_params

**Comment by pingguo114514** [comment]
completion_api_params = {
    "model": "gpt-3.5-turbo",
    "temperature": 0.9,  # 数值越低得到的回答越理性，取值范围[0, 1]
    "top_p": 1,  # 生成的文本的文本与要求的符合度, 取值范围[0, 1]
    "frequency_penalty": 0.2,
    "presence_penalty": 1.0,
}

**Comment by RockChinQ** [comment]
不太清楚，不应该发生这种问题，建议尝试更新`openai`依赖库

**Comment by pingguo114514** [comment]
em……试了一下，是反向代理的问题……
