### ISSUE TITLE
[Bug]: 程序启动后长时间不显示 "成功登录到账号xxxxx" ,并且不回复消息，且#37的并不适用于我的问题

### ISSUE THREAD

**Issue by xiexin621** [RockChinQ/QChatGPT#448]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Ubuntu 20.04.6

### Python环境

Python 3.8.10

### 异常情况

在进行到登录qq连接框架时一直卡在 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37
在运行主程序时
一开始报错“WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv”
然后我用了虚拟环境，再运行主程序时报错如下
注：且两个框架我都能正常的接消息（后台能看见）

### 报错信息

WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Collecting requests~=2.28.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d2/f4/274d1dbe96b41cf4e0efb70cbced278ffd61b5c7bb70338b62af94ccb25b/requests-2.28.2-py3-none-any.whl (62 kB)
Collecting openai~=0.27.4
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/3a/c5/590e2285484583d470dc862b6f3d2629cd32ddc457d8e9de590e0702f491/openai-0.27.5-py3-none-any.whl (71 kB)
Processing /root/.cache/pip/wheels/ef/3d/b8/d292e98d280c16b6d1f14881fe1afec45163c5ea1df7ce3d3f/dulwich-0.21.3-cp38-cp38-linux_armv7l.whl
Collecting colorlog~=6.6.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7d/54/e24efe5469ecb2710112055de87a2900e9494810bcfc25c12c7a0723eb64/colorlog-6.6.0-py2.py3-none-any.whl (11 kB)
Collecting yiri-mirai~=0.2.6.1
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/09/33/77e90acad15d210a7d326bf450eb6952fa77b339e53bae7125643286a4d3/yiri_mirai-0.2.6.2-py3-none-any.whl (77 kB)
Collecting websockets
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ea/8a/32116db59137262378ba72a124e5ee28f78f8a3a621281cfbddb6a634b37/websockets-11.0.2-py3-none-any.whl (118 kB)
Collecting urllib3~=1.26.10
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/7b/f5/890a0baca17a61c1f92f72b81d3c31523c99bec609e60c292ea55b387ae8/urllib3-1.26.15-py2.py3-none-any.whl (140 kB)
Processing /root/.cache/pip/wheels/05/6a/62/9a83dc35bc860485e36be3b1ec253520e6ca389db34dc9b117/func_timeout-4.3.5-py3-none-any.whl
Processing /root/.cache/pip/wheels/89/51/3c/50b87cbb66e93cad1b069940ea65e0b661c9f71f1ac57bbc87/Pillow-9.5.0-cp38-cp38-linux_armv7l.whl
Collecting nakuru-project-idk
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/19/17/24bbfe07e2c22910aaeaa836ee6905169117ab6fbab6c0d4ff7e081a666d/nakuru_project_idk-0.0.2-py3-none-any.whl (23 kB)
Collecting certifi>=2017.4.17
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/71/4c/3db2b8021bd6f2f0ceb0e088d6b2d49147671f25832fb17970e9b583d742/certifi-2022.12.7-py3-none-any.whl (155 kB)
Collecting charset-normalizer<4,>=2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/ef/81/14b3b8f01ddaddad6cdec97f2f599aa2fa466bd5ee9af99b08b7713ccd29/charset_normalizer-3.1.0-py3-none-any.whl (46 kB)
Collecting idna<4,>=2.5
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/fc/34/3030de6f1370931b9dbb4dad48f6ab1015ab1d32447850b9fc94e60097be/idna-3.4-py3-none-any.whl (61 kB)
Collecting tqdm
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e6/02/a2cff6306177ae6bc73bc0665065de51dfb3b9db7373e122e2735faf0d97/tqdm-4.65.0-py3-none-any.whl (77 kB)
Processing /root/.cache/pip/wheels/88/64/ee/693835337d5c11e9a3178d7921b8e585a67f131c08cfc59325/aiohttp-3.8.4-cp38-cp38-linux_armv7l.whl
Collecting httpx<1.0,>=0.18.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/4e/c1/692013f1e6115a061a14f6c7d05947515a1eb7b85ef6e9bf0ffbf0e92738/httpx-0.24.0-py3-none-any.whl (75 kB)
Collecting pydantic<2.0.0,>=1.8.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/8d/e1/d9219c4e4161a511158e531a84aa719087064d208c2bf87df5c58812f190/pydantic-1.10.7-py3-none-any.whl (157 kB)
Collecting starlette<1.0,>=0.14.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/12/48/f9c1ec6bee313aba264fbc2483d9070f4e4526f2538e2b55b1e4a391d938/starlette-0.26.1-py3-none-any.whl (66 kB)
Collecting aiofiles<0.8.0,>=0.7.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/e7/61/007ac6f27fe1c2dc44d3a62f429a8440de1601428b4d0291eae1a3494d1f/aiofiles-0.7.0-py3-none-any.whl (13 kB)
Processing /root/.cache/pip/wheels/36/32/08/3db697d1e2b7a4eb76eb6d32b1c07507526c67b0fdd7849b4a/Logbook-1.5.3-cp38-cp38-linux_armv7l.whl
Collecting async-lru
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/17/f8/bdc723f93ec2458db76352e0f2c017331fe284e4e6b749db262199803f81/async_lru-2.0.2-py3-none-any.whl (5.7 kB)
Processing /root/.cache/pip/wheels/54/ed/bd/ac84eeaa7b6c23c6f2074e3d8419ac27c548f8a2066d4f9679/yarl-1.9.2-cp38-cp38-linux_armv7l.whl
Processing /root/.cache/pip/wheels/75/fb/7b/4343e5061528af75deeb4c52645b4a5cd363aa6ea9e1c40d8c/multidict-6.0.4-cp38-cp38-linux_armv7l.whl
Collecting attrs>=17.3.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/f0/eb/fcb708c7bf5056045e9e98f62b93bd7467eb718b0202e7698eb11d66416c/attrs-23.1.0-py3-none-any.whl (61 kB)
Collecting async-timeout<5.0,>=4.0.0a3
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/d6/c1/8991e7c5385b897b8c020cdaad718c5b087a6626d1d11a23e1ea87e325a7/async_timeout-4.0.2-py3-none-any.whl (5.8 kB)
Collecting aiosignal>=1.1.2
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/76/ac/a7305707cb852b7e16ff80eaf5692309bde30e2b1100a1fcacdc8f731d97/aiosignal-1.3.1-py3-none-any.whl (7.6 kB)
Processing /root/.cache/pip/wheels/de/f1/ec/c7d6720c58010a5e98742f5629c1d5e2bd2d36a144c8c46882/frozenlist-1.3.3-cp38-cp38-linux_armv7l.whl
Collecting sniffio
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/c3/a0/5dba8ed157b0136607c7f2151db695885606968d1fae123dc3391e0cfdbf/sniffio-1.3.0-py3-none-any.whl (10 kB)
Collecting httpcore<0.18.0,>=0.15.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/6c/39/05ebe30333ec66bba849d3c25c85d759b94c43bb03b2222de051c50d4390/httpcore-0.17.0-py3-none-any.whl (70 kB)
Collecting typing-extensions>=4.2.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/31/25/5abcd82372d3d4a3932e1fa8c3dbf9efac10cc7c0d16e78467460571b404/typing_extensions-4.5.0-py3-none-any.whl (27 kB)
Collecting anyio<5,>=3.4.0
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/77/2b/b4c0b7a3f3d61adb1a1e0b78f90a94e2b6162a043880704b7437ef297cad/anyio-3.6.2-py3-none-any.whl (80 kB)
Collecting h11<0.15,>=0.13
  Using cached https://pypi.tuna.tsinghua.edu.cn/packages/95/04/ff642e65ad6b90db43e668d70ffb6736436c7ce41fcc549f4e9472234127/h11-0.14.0-py3-none-any.whl (58 kB)
ERROR: yiri-mirai 0.2.6.2 has requirement websockets<11.0,>=10.0, but you'll have websockets 11.0.2 which is incompatible.
Installing collected packages: certifi, charset-normalizer, urllib3, idna, requests, tqdm, multidict, yarl, attrs, async-timeout, frozenlist, aiosignal, aiohttp, openai, dulwich, colorlog, sniffio, anyio, h11, httpcore, httpx, typing-extensions, pydantic, websockets, starlette, aiofiles, yiri-mirai, func-timeout, Pillow, logbook, async-lru, nakuru-project-idk
Successfully installed Pillow-9.5.0 aiofiles-0.7.0 aiohttp-3.8.4 aiosignal-1.3.1 anyio-3.6.2 async-lru-2.0.2 async-timeout-4.0.2 attrs-23.1.0 certifi-2022.12.7 charset-normalizer-3.1.0 colorlog-6.6.0 dulwich-0.21.3 frozenlist-1.3.3 func-timeout-4.3.5 h11-0.14.0 httpcore-0.17.0 httpx-0.24.0 idna-3.4 logbook-1.5.3 multidict-6.0.4 nakuru-project-idk-0.0.2 openai-0.27.5 pydantic-1.10.7 requests-2.28.2 sniffio-1.3.0 starlette-0.26.1 tqdm-4.65.0 typing-extensions-4.5.0 urllib3-1.26.15 websockets-11.0.2 yarl-1.9.2 yiri-mirai-0.2.6.2
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already up-to-date: websockets in ./tutorial-env/lib/python3.8/site-packages (11.0.2)
[2023-04-28 12:53:33.144] main.py (73) - [INFO] : 检查config模块完整性.
[2023-04-28 12:53:33.150] main.py (101) - [INFO] : 检查tips模块完整性.
正在更新依赖库，请等待...
这个操作不是必须的,如果不想更新,请在config.py中将upgrade_dependencies设置为False
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
ERROR: Exception:
Traceback (most recent call last):
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 357, in run
    resolver.resolve(requirement_set)
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 177, in resolve
    discovered_reqs.extend(self._resolve_one(requirement_set, req))
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 333, in _resolve_one
    abstract_dist = self._get_abstract_dist_for(req_to_install)
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 270, in _get_abstract_dist_for
    skip_reason = self._check_skip_installed(req)
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/legacy_resolve.py", line 246, in _check_skip_installed
    self.finder.find_requirement(req_to_install, upgrade=True)
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 898, in find_requirement
    best_candidate_result = self.find_best_candidate(
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 881, in find_best_candidate
    candidates = self.find_all_candidates(project_name)
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 825, in find_all_candidates
    package_links = self.process_project_url(
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/index/package_finder.py", line 796, in process_project_url
    with indent_log():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 107, in indent_log
    _log_state.indentation += num
AttributeError: '_thread._local' object has no attribute 'indentation'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/cli/base_command.py", line 186, in _main
    status = self.run(options, args)
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/commands/install.py", line 475, in run
    requirement_set.cleanup_files()
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/req/req_set.py", line 207, in cleanup_files
    with indent_log():
  File "/usr/lib/python3.8/contextlib.py", line 113, in __enter__
    return next(self.gen)
  File "/root/QChatGPT/tutorial-env/lib/python3.8/site-packages/pip/_internal/utils/logging.py", line 107, in indent_log
    _log_state.indentation += num
AttributeError: '_thread._local' object has no attribute 'indentation'

**Comment by xiexin621** [comment]
这个是config.py我已经配置修改的部分，其余部分未修改
msg_source_adapter = "yirimirai"

mirai_http_api_config = {
    "adapter": "WebSocketAdapter",
    "host": "localhost",
    "port": 8080,
    "verifyKey": "yirimirai",
    "qq": 1417627367
}

nakuru_config = {
    "host": "localhost",  # go-cqhttp的地址
    "port": 6700,  # go-cqhttp的正向websocket端口
    "http_port": 5700,  # go-cqhttp的正向http端口
    "token": ""  # 若在go-cqhttp的config.yml设置了access_token, 则填写此处
}
admin_qq = 3328659340

**Comment by RockChinQ** [comment]
项目要求Python高于3.9

**Comment by xiexin621** [comment]
> 
好的谢谢
