### ISSUE TITLE
[BUG] 运行主程序时报错: signal only works in main thread of the main interpreter

### ISSUE THREAD

**Issue by dominoar** [RockChinQ/QChatGPT#45]
**运行环境**
- 部署方式：手动部署
    手动部署/自动部署/Docker部署
- 系统环境：win x64
    e.g. Centos x64
- Python环境（仅手动部署填写）：
    e.g. Python 3.10.9

**描述漏洞**
![image](https://user-images.githubusercontent.com/105423680/208092018-5109df36-e8f4-4d72-9926-1d5d74bf3499.png)

**完整报错信息**
完整的报错信息

**Comment by dominoar** [comment]
![image](https://user-images.githubusercontent.com/105423680/208092266-5381464e-cf0f-4321-9508-a94a2285cfe6.png)
mirai正常执行了，允许主程序报错

**Comment by dominoar** [comment]
![image](https://user-images.githubusercontent.com/105423680/208092438-c1891bcf-aa21-4676-a462-0a54d22bec6a.png)
mirai正常执行，上面是运行项目后报错

**Comment by dominoar** [comment]
![image](https://user-images.githubusercontent.com/105423680/208092749-a4ab6647-77d3-42bc-aaa2-816ebb821ef2.png)
完整的控制台报错

**Comment by RockChinQ** [comment]
请提供python版本，系统版本以及文字形式的完整报错信息

**Comment by RockChinQ** [comment]
可能是安装了uvicorn或hypercorn导致的，使用以下命令
```
pip3 uninstall uvicorn
pip3 uninstall hypercorn
```
