### ISSUE TITLE
[Feature]: 希望能加一个自动reset并且延续prompt的功能

### ISSUE THREAD

**Issue by McPeter111** [RockChinQ/QChatGPT#463]
### 这是一个？

新功能

### 详细描述

当token炸了后
自动!reset <当前预设>
并且输出相关提示（希望能自定义提示内容）
如果想切换预设就手动reset

举例：
user：114514
（token超出）
bot：检测到token超出，已自动重置 当前预设：猫娘.json

之后除非手动切换，将保持猫娘预设

**Comment by RockChinQ** [comment]
已实现token超限时自动重置会话，请等待版本更新并按照`config-template.py`的`auto_reset`字段修改`config.py`
