### ISSUE TITLE
[Feature]:希望关键词的自定义回复添加无需@的路径 

### ISSUE THREAD

**Issue by lantiantian49** [RockChinQ/QChatGPT#465]
### 这是一个？

现有功能优化

### 详细描述

希望关键词的自定义回复添加无需@的路径
未@机器人的、符合指定规则的消息回复会覆盖插件中关键字的自定义回复

**Comment by RockChinQ** [comment]
不太明白，给点示例

**Comment by lantiantian49** [comment]
hello_plugin插件模板没办法通过不添加@bot获得消息回复
config.py中response_rules规则实现的消息回复无法自定义

**Comment by RockChinQ** [comment]
仍然不清楚你的意思，请提供实例

**Comment by lantiantian49** [comment]
from pkg.plugin.models import *
from pkg.plugin.host import EventContext, PluginHost

"""
在收到私聊或群聊消息"hello"时，回复"hello, <发送者id>!"或"hello, everyone!"
"""


# 注册插件
@register(name="Hello", description="hello world", version="0.1", author="RockChinQ")
class HelloPlugin(Plugin):

    # 插件加载时触发
    # plugin_host (pkg.plugin.host.PluginHost) 提供了与主程序交互的一些方法，详细请查看其源码
    def __init__(self, plugin_host: PluginHost):
        pass

    # 当收到个人消息时触发
    @on(PersonNormalMessageReceived)
    def person_normal_message_received(self, event: EventContext, **kwargs):
        msg = kwargs['text_message']
        if msg == "hello":  # 如果消息为hello

            # 输出调试信息
            logging.debug("hello, {}".format(kwargs['sender_id']))

            # 回复消息 "hello, <发送者id>!"
            event.add_return("reply", ["hello, {}!".format(kwargs['sender_id'])])

            # 阻止该事件默认行为（向接口获取回复）
            event.prevent_default()

    # 当收到群消息时触发
    @on(GroupNormalMessageReceived)
    def group_normal_message_received(self, event: EventContext, **kwargs):
        msg = kwargs['text_message']
        if msg == "hello":  # 如果消息为hello

            # 输出调试信息
            logging.debug("hello, {}".format(kwargs['sender_id']))

            # 回复消息 "hello, everyone!"
            event.add_return("reply", ["hello, everyone!"])

            # 阻止该事件默认行为（向接口获取回复）
            event.prevent_default()

    # 插件卸载时触发
    def __del__(self):
        pass

希望上述插件中添加无需@发送hello时也能触发机器人的hello, everyone回复功能

**Comment by RockChinQ** [comment]
你的意思是修改这个示例插件内容使它支持非at的响应规则？

**Comment by lantiantian49** [comment]
对，但是仅仅是修改插件内容好像很难得到想要的功能

**Comment by RockChinQ** [comment]
这个自行按照wiki中的插件编写教程实现吧，可以看看其他的事件监听器
