### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 5MISAKA** [RockChinQ/QChatGPT#466]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

win10

### Python环境

python 3.11.3

### 异常情况

gocq机器人登录没有问题，但启动Qgpt后，首先好像是説我pip版本低，在控制台輸入python -m pip install --upgrade pip后，显示程序启动完成，但没有弹出protocol：connected 并且不能回复消息，查看nakuru_config后如图所示，一直没有找到问题
![OAUP2OO% 7VWKSHBR78~ENR](https://github.com/RockChinQ/QChatGPT/assets/133449085/0a3ae586-f03c-4d8d-bfc7-ab18721323df)
![HW{TZ9DB86~KULG7}F1TK8O](https://github.com/RockChinQ/QChatGPT/assets/133449085/a2609d16-f5b3-4b8a-8303-61ef64821e41)

**Comment by 5MISAKA** [comment]
![P_~_(_M81ND)N)B(F QV$V9](https://github.com/RockChinQ/QChatGPT/assets/133449085/7cbbf787-33b2-4788-806d-4c11293f1c72)

**Comment by RockChinQ** [comment]
贴上gocq的完整配置文件内容

**Comment by RockChinQ** [comment]
确保gocq启动并正常运行

**Comment by 5MISAKA** [comment]
这是完整的截图 机器人运行完全没问题 还是没找到问题在哪
![1](https://github.com/RockChinQ/QChatGPT/assets/133449085/9de436a2-e150-45de-8269-8167c49d1746)
![2](https://github.com/RockChinQ/QChatGPT/assets/133449085/49303f51-498e-40fc-b3d7-700fd0934e3a)
![3](https://github.com/RockChinQ/QChatGPT/assets/133449085/5d6fb203-b6bf-4347-a240-dbdea0cd2d75)
![4](https://github.com/RockChinQ/QChatGPT/assets/133449085/e5b06b0a-bb34-4240-928c-82925229bd28)
![5](https://github.com/RockChinQ/QChatGPT/assets/133449085/ced638a3-da99-4ecd-81c4-8ff651b25bf6)
![6](https://github.com/RockChinQ/QChatGPT/assets/133449085/23038fd0-3971-4594-b44e-3f64fb85cdb4)

**Comment by 5MISAKA** [comment]
> 贴上gocq的完整配置文件内容

**Comment by RockChinQ** [comment]
那检查一下防火墙有没有拦截 5700和6700端口吧？你这个很玄学，或者按照 #402 开启调试模式看看输出什么

**Comment by 5MISAKA** [comment]
大佬这是按402中开启调试后的界面&nbsp; 然后我再次打开gocq还是登陆没问题 但是回复不给予回复 该怎么办啊 大佬




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "RockChinQ/QChatGPT"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年5月17日(星期三) 下午4:10
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [RockChinQ/QChatGPT] [Bug]:  (Issue #466)





 
那检查一下防火墙有没有拦截 5700和6700端口吧？你这个很玄学，或者按照 #402 开启调试模式看看输出什么

**Comment by RockChinQ** [comment]
没有见到调试信息，检查你的回复内容

**Comment by RockChinQ** [comment]
此issue也是无法连接go-cqhttp的问题，所有讨论转移到 #460 ，本issue锁定
