### ISSUE TITLE
[Bug]: 安装switcher插件后bot就不理会@了

### ISSUE THREAD

**Issue by McPeter111** [RockChinQ/QChatGPT#469]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

windows

### Python环境

py3.10

### 异常情况

![QQ图片20230514212340](https://github.com/RockChinQ/QChatGPT/assets/121279581/e2ec4250-3f48-466e-a8f6-3077c3a9df73)
现在只理会前缀相应

**Comment by McPeter111** [comment]
同样，主程序也接收不到@的信息

**Comment by McPeter111** [comment]
已修复，卸载插件重装

**Comment by RockChinQ** [comment]
已确认的问题，统一到 #471 跟踪，此issue关闭

**Comment by RockChinQ** [comment]
已修复，请更新到`v2.4.4`
