### ISSUE TITLE
[Bug]: 对bot发送！reload后bot不再回复消息

### ISSUE THREAD

**Issue by 2727917216** [RockChinQ/QChatGPT#472]
### 部署方式

一键安装包部署

### 登录框架

go-cqhttp

### 系统环境

Windows10

### Python环境

Python3.10

### 异常情况

在跟bot聊天时bot会概率性不再回复消息，后台无报错且能显示消息发出但不会回复，包括指令也不能回复。
在对bot发送！reload之后百分百触发此问题。

**Comment by RockChinQ** [comment]
#471 已复现此问题，正在查明原因；刚给女孩子过完生日，明天查😋

**Comment by RockChinQ** [comment]
已确认的问题，统一到 #471 跟踪，此issue关闭

**Comment by RockChinQ** [comment]
已修复，请更新到`v2.4.4`
