### ISSUE TITLE
[Bug]: 使用语音包超时

### ISSUE THREAD

**Issue by WIQGE** [RockChinQ/QChatGPT#483]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Windows10

### Python环境

Python3.10.9

### 异常情况

启动QChat时没什么问题，能够正常发送语音和文字，但是过了一会儿之后就出现超时的情况。超时一次之后就开始报错了。

### 报错信息

Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'F:\DD\QQBOT\QChatGPT\WinZH\bot3\QChatGPT\voice-file\voice_0bc4451464ecac8e870fd314e29ab06a.wav':
  Duration: 00:00:25.01, bitrate: 705 kb/s
  Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 22050 Hz, 1 channels, flt, 705 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_f32le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help
Output #0, s16le, to 'F:\DD\QQBOT\QChatGPT\WinZH\bot3\QChatGPT\voice-file\voice_0bc4451464ecac8e870fd314e29ab06a.pcm':
  Metadata:
    encoder         : Lavf59.36.100
  Stream #0:0: Audio: pcm_s16le, 22050 Hz, mono, s16, 352 kb/s
    Metadata:
      encoder         : Lavc59.58.100 pcm_s16le
size=    1077kB time=00:00:24.98 bitrate= 353.1kbits/s speed=1.32e+03x
video:0kB audio:1077kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: 0.000000%
Packets encoded:                1148[2023-05-28 15:02:26.755] manager.py (293) - [WARNING] : person_642686599: 超时，重 试中(0)
[2023-05-28 15:02:26.755] manager.py (369) - [INFO] : 通知管理员:person_642686599 请求超时

**Comment by WIQGE** [comment]
后续报错
Guessed Channel Layout for Input Stream #0.0 : mono
Input #0, wav, from 'F:\DD\QQBOT\QChatGPT\WinZH\bot3\QChatGPT\voice-file\voice_75274e37ee72814beca2b016f472662d.wav':
  Duration: 00:00:09.38, bitrate: 705 kb/s
  Stream #0:0: Audio: pcm_f32le ([3][0][0][0] / 0x0003), 22050 Hz, 1 channels, flt, 705 kb/s
Stream mapping:
  Stream #0:0 -> #0:0 (pcm_f32le (native) -> pcm_s16le (native))
Press [q] to stop, [?] for help


[q] command received. Exiting.

Finishing stream 0:0 without any data written to it.
Output #0, s16le, to 'F:\DD\QQBOT\QChatGPT\WinZH\bot3\QChatGPT\voice-file\voice_75274e37ee72814beca2b016f472662d.pcm':
  Metadata:
    encoder         : Lavf59.36.100
  Stream #0:0: Audio: pcm_s16le, 22050 Hz, mono, s16, 352 kb/s
    Metadata:
      encoder         : Lavc59.58.100 pcm_s16le
size=       0kB time=-577014:32:22.77 bitrate=  -0.0kbits/s speed=N/A
video:0kB audio:0kB subtitle:0kB other streams:0kB global headers:0kB muxing overhead: unknown
Output file is empty, nothing was encoded (check -ss / -t / -frames parameters if used)

**Comment by RockChinQ** [comment]
请到语音插件仓库提issue
