### ISSUE TITLE
[Bug]: 运行一段时间（大概半小时）后崩溃

### ISSUE THREAD

**Issue by zyk6** [RockChinQ/QChatGPT#484]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Ubuntu 20

### Python环境

Python 3.9.7

### 异常情况

突然，发消息给bot无反应，包括gpt提问和`!cmd`。
使用了switcher 和 revLibs 插件，使用 gpt3.5逆向工程 模型
19:25部署完成，19:43报报错信息内的错误。

### 报错信息

![image](https://github.com/RockChinQ/QChatGPT/assets/35987378/b2d25520-50b6-4df4-8796-117e585e7c28)

**Comment by RockChinQ** [comment]
主程序与mirai断连，这是由于你网络不稳定导致的
