### ISSUE TITLE
[Feature]: latex语法转为图片

### ISSUE THREAD

**Issue by XYCode-Kerman** [RockChinQ/QChatGPT#488]
### 这是一个？

新功能

### 详细描述

希望实现一个将latex语法转换为图片并发送的功能

**Comment by RockChinQ** [comment]
> @RockChinQ 这个Issue的代码我来写吧，到时候我发个PR

耶，祝你好运

**Comment by RockChinQ** [comment]
这个功能，现在可以写插件实现: https://qchatgpt.rockchin.top/posts/plugin/extension.html. 扩展一个长消息处理策略。
