### ISSUE TITLE
[Feature]: bot中有些文本还是不能修改，没找到修改的地方

### ISSUE THREAD

**Issue by NekoMua** [RockChinQ/QChatGPT#497]
### 这是一个？

现有功能优化

### 详细描述

[bot] 消息中存在不合适的内容, 请更换措辞
[bot]重载完成
类似于这种消息，没有地方可以修改

**Comment by For-Lin0601** [comment]
在vscode中直接搜“重载完成”，直接就找到了唯一的结果，路径是QchatGPT\pkg\utils\reloader.py最后一行。不过看着这个地方可能每次更新都会被覆盖，你可以自己写一个小的程序来控制更改，代码如下：
"""
'''

[r'文件路径地址',
     """
原文（注意缩进）
""",
     """
修改后文字（注意缩进）
"""],

'''

text = [
# 把上面注释的内容复制到这里，有几处要修改的就复制几个就行
# 注意所有的'\'都要写成'\\'，这个只能手动改，因为会和自动换行的冲突。地址，原文和修改后都要更改
]
for item in text:
    # 读取文件内容
    with open(item[0], 'r', encoding='utf-8') as f:
        file_content = f.read()

    # 查询内容并修改
    index = file_content.find(item[1])
    if index != -1:
        new_content = file_content[:index] + item[2] + file_content[index+len(item[1]):]
        with open(item[0], 'w', encoding='utf-8') as f:
            f.write(new_content)
        print(f"文件{item[0]}成功更新~") # 更改成功
    else:
        index = file_content.find(item[2])
        if index != -1:
            print(f"文件{item[0]}已完成修改") # 检查是否更改成功
        else:
            print(f"文件{item[0]}中未找到待替换内容！") # 更改失败，要么是缩进，要么路径，要么这块源码作者大大改过了所以找不到替换内容
"""
这样每次更新 !update 后，再运行一遍这个文件就能修改好了。因为我自己改了挺多地方，然后 !update 以后心态崩了QwQ

**Comment by RockChinQ** [comment]
> 在vscode中直接搜“重载完成”，直接就找到了唯一的结果，路径是QchatGPT\pkg\utils\reloader.py最后一行。不过看着这个地方可能每次更新都会被覆盖，你可以自己写一个小的程序来控制更改，代码如下：
> """
> '''
> 
> [r'文件路径地址',
>      """
> 原文（注意缩进）
> """,
>      """
> 修改后文字（注意缩进）
> """],
> 
> '''
> 
> text = [
> # 把上面注释的内容复制到这里，有几处要修改的就复制几个就行
> # 注意所有的'\'都要写成'\\'，这个只能手动改，因为会和自动换行的冲突。地址，原文和修改后都要更改
> ]
> for item in text:
>     # 读取文件内容
>     with open(item[0], 'r', encoding='utf-8') as f:
>         file_content = f.read()
> 
>     # 查询内容并修改
>     index = file_content.find(item[1])
>     if index != -1:
>         new_content = file_content[:index] + item[2] + file_content[index+len(item[1]):]
>         with open(item[0], 'w', encoding='utf-8') as f:
>             f.write(new_content)
>         print(f"文件{item[0]}成功更新~") # 更改成功
>     else:
>         index = file_content.find(item[2])
>         if index != -1:
>             print(f"文件{item[0]}已完成修改") # 检查是否更改成功
>         else:
>             print(f"文件{item[0]}中未找到待替换内容！") # 更改失败，要么是缩进，要么路径，要么这块源码作者大大改过了所以找不到替换内容
> """
> 这样每次更新 !update 后，再运行一遍这个文件就能修改好了。因为我自己改了挺多地方，然后 !update 以后心态崩了QwQ

感谢您的实践，不过这种方式会被更新覆盖，建议您提出pr，实现支持用户在tips.py中修改此字段

**Comment by RockChinQ** [comment]
请您总结需要支持自定义的文本，之后进行修改

**Comment by For-Lin0601** [comment]
> 请您总结需要支持自定义的文本，之后进行修改

捉纳西妲！一个小建议，一些小bug。
        建议是 QChatGPT\pkg\qqbot\blob.py 长文本转化成群消息回复格式，单一的一长条消息比较丑，我把它以 config.blob_message_threshold 的长度做了分割，并尽可能按照换行符切割，美观一点点~。然后还可以重载一下方法，比如说如果传入的是列表，那么就直接按照列表的切割处理；如果是字符串，那么按照上述长文本切割，我的代码在下面，我不会发github的格式，可能比较混乱QwQ。
        第一个bug是做插件的时候发现 QChatGPT\pkg\plugin\host.py 中的 ‘发送私聊消息’‘发送群聊消息’‘通知管理员’ 没有引用 blob 做长文本处理，不过我自己美化的挺好的，你改了我还得重构QwQ。
        第二个bug是监听器，一些监听器虽然作者大大没有做反馈，但是控制台是能检测到变化的，这类监听器只需要在 QChatGPT\pkg\qqbot\messager.py 中注册，编写逻辑，正确注销就可以正常使用。但是有一些mirai文档中有的监听器无法正常监听，注册编写逻辑也并没有反馈，很怪。我这里找到的一个是‘头像戳一戳事件’，文件是 bot3\python\Lib\site-packages\mirai\models\events.py 第742行，这段代码完全不执行，按理说虽然我没注册，但是事件会在控制台反馈出来的，但是这个不反馈。并且这个文件的661行 ‘添加好友申请’是能正常响应的，也完成了程序的编写。


最后是我的blob，希望可以节约大佬一点时间QwQ



’‘’
# 长度切割，超出config长度限制后寻找换行符，并在换行符切割文本保证美观；若到达两倍config限制长度仍没出现换行符，那只能暴力切割咯


    [r'QChatGPT\\pkg\\qqbot\\blob.py',


    '''
            # 包装转发消息
            display = ForwardMessageDiaplay(
                title='群聊的聊天记录',
                brief='[聊天记录]',
                source='聊天记录',
                preview=["bot: "+text],
                summary="查看1条转发消息"
            )

            node = ForwardMessageNode(
                sender_id=config.mirai_http_api_config['qq'],
                sender_name='bot',
                message_chain=MessageChain([text])
            )

            forward = Forward(
                display=display,
                node_list=[node]
            )
''',


    '''
            # 包装转发消息
            segments = []
            while text:
                if len(text) <= config.blob_message_threshold:
                    segments.append(text)
                    break
                else:
                    split_index = config.blob_message_threshold
                if '\\n' in text[split_index:split_index*2]:
                    split_index = text.index('\\n', split_index, split_index*2) + 1
                else:
                    split_index = split_index*2
                segments.append(text[:split_index])
                text = text[split_index:]
            display = ForwardMessageDiaplay(
                title='群聊的聊天记录',
                brief='[聊天记录]',
                source='聊天记录',
                preview=[f"bot: {segment}" for segment in segments],
                summary=f"查看{len(segments)}条转发消息"
            )
            node_list = [ForwardMessageNode(
                sender_id=config.mirai_http_api_config['qq'],
                sender_name='bot',
                message_chain=MessageChain([segment])
            ) for segment in segments]
            forward = Forward(
                display=display,
                node_list=node_list
            )
'''],






################## 这里下面是我自己在用的blob形式，传入blob后得到的就必然是群组消息了，自己用来排版好看

# 因为初学python，所以就直接阉割了图片处理QwQ
# (实际上连python的语法格式都是跟着大佬您的项目学的QwQ，一点点从数据结构，到类与继承，到异步，插件，边观摩边写。大佬好厉害！)







def blob(text) -> MessageComponent:
    """由于原项目插件无长文本模式，故在此手动转为长文本"""

    class ForwardMessageDiaplay(MiraiBaseModel):
        title: str = "群聊的聊天记录"
        brief: str = "[聊天记录]"
        source: str = "聊天记录"
        preview: List[str] = []
        summary: str = "查看x条转发消息"

    class Forward(MessageComponent):
        """合并转发。"""
        type: str = "Forward"
        """消息组件类型。"""
        display: ForwardMessageDiaplay
        """显示信息"""
        node_list: List[ForwardMessageNode]
        """转发消息节点列表。"""
        def __init__(self, *args, **kwargs):
            if len(args) == 1:
                self.node_list = args[0]
                super().__init__(**kwargs)
            super().__init__(*args, **kwargs)

        def __str__(self):
            return '[聊天记录]'

    # 包装转发消息
    if isinstance(text, str):
        segments = []
        while text:
            if len(text) <= config.blob_message_threshold:
                segments.append(text)
                break
            else:
                split_index = config.blob_message_threshold
            if '\n' in text[split_index:split_index*2]:
                split_index = text.index('\n', split_index, split_index*2) + 1
            else:
                split_index = split_index*2
            segments.append(text[:split_index])
            text = text[split_index:]
    else:
        segments = text
    display = ForwardMessageDiaplay(
        title='群聊的聊天记录',
        brief='[聊天记录]',
        source='聊天记录',
        preview=[f"bot: {segment}" for segment in segments],
        summary=f"查看{len(segments)}条转发消息"
    )
    node_list = [ForwardMessageNode(
        sender_id=config.mirai_http_api_config['qq'],
        sender_name='bot',
        message_chain=MessageChain([segment])
    ) for segment in segments]
    forward = Forward(
        display=display,
        node_list=node_list
    )

    return [forward]

‘’‘

**Comment by RockChinQ** [comment]
> 捉纳西妲！一个小建议，一些小bug。 建议是 QChatGPT\pkg\qqbot\blob.py 长文本转化成群消息回复格式，单一的一长条消息比较丑，我把它以 config.blob_message_threshold 的长度做了分割，并尽可能按照换行符切割，美观一点点~。然后还可以重载一下方法，比如说如果传入的是列表，那么就直接按照列表的切割处理；如果是字符串
> ...

抱歉，目前不会再将回复消息截断进行回复，仅支持以下两种长消息处理策略，其他策略请自行使用插件实现：

- 转发消息组件
- 文字转图片

**Comment by RockChinQ** [comment]
预计在3.0版本重构所有配置文件模式时完善提示语修改功能
