### ISSUE TITLE
[Bug]: 收不到消息

### ISSUE THREAD

**Issue by qjsir** [RockChinQ/QChatGPT#502]
### 部署方式

一键安装包部署

### 登录框架

go-cqhttp

### 系统环境

win10

### Python环境

Python310

### 异常情况

如图所示收不到消息
![Screenshot_20230620_115000_com tencent mobileqq](https://github.com/RockChinQ/QChatGPT/assets/129706123/58b28618-4afd-44bc-85bd-8417fee6fd20)

**Comment by RockChinQ** [comment]
go-cqhttp被风控了，消息发不出去，尝试重启、重装或更换mirai

**Comment by qjsir** [comment]
> go-cqhttp被风控了，消息发不出去，尝试重启、重装或更换mirai

好的，感谢
