### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by makuraly** [RockChinQ/QChatGPT#504]
### 部署方式

一键安装包部署

### 登录框架

go-cqhttp

### 系统环境

Win 11

### Python环境

3.9

### 异常情况

启动之后会有main.py (307) - LWARNINGJ：检查更新失败：HTTPSConnectionPool (host=api. github. com, port=443)：Max retries exceeded with ur1: /repos/RockChinQ/ QChatGPI/releases (Caused by SSLErrOr (SSLEOF
Error (8, EOF occurred in violation of protocol ( ss1. c: 997)' ))
[2023-06-30 14:16:33. 584] ma in- py. (316) - [WARNINCJ：获取公告失败;FTTPSComnectignPoo1 (host=’api. gi thub. com', port=443)： Max retries exceeded with url: /repos /RockChinQ/ QChatCPT/contents/res/ announcement. jso (Cau
sed by SSLError (SSLEOFError (8,EOF occurred in violation of protocol ( ss1. c: 997)' ))

发消息后会有[bot]person_3439348753会话调用API失败:Error communicating with OpenAI: HTTPSConnectionPool(host='api.openai.com', port=443): Max retries exceeded with url: /v1/chat/completions (Caused by SSLError(SSLEOFError(8, 'EOF occurred in violation of protocol (_ssl.c:997)')))
请尝试关闭网络代理来解决此问题。
请问如何解决这种问题呀

**Comment by RockChinQ** [comment]
你这个估计是又开了代理又设置了代理地址，只使用一种方式就行了

**Comment by makuraly** [comment]
> 你这个估计是又开了代理又设置了代理地址，只使用一种方式就行了

我只会挂VPN所以可能不是这个问题👀

**Comment by RockChinQ** [comment]
自己主机的网络问题自行解决一下吧，比较复杂，我不了解你的网络架构也无能为力
