### ISSUE TITLE
 你的账号被限制登录, 请配置 SignServer 后重试

### ISSUE THREAD

**Issue by Meng-de-Cao** [RockChinQ/QChatGPT#507]
![image](https://github.com/RockChinQ/QChatGPT/assets/56462540/19fb487f-b871-4ec6-8f91-a7f90931442e)
大哥帮忙看看这个签名服务器要怎么配置

**Comment by RockChinQ** [comment]
前往 https://github.com/Mrs4s/go-cqhttp 的issues搜索解决办法
