### ISSUE TITLE
[BUG]运行卡住了，不会动了

### ISSUE THREAD

**Issue by CXY666CXY** [RockChinQ/QChatGPT#53]
**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
    e.g. Centos x64
- Python环境（仅手动部署填写）：
    e.g. Python 3.10.9

**描述漏洞**
什么时候发生的，mirai还是主程序，越详细越好

**完整报错信息**
![image](https://user-images.githubusercontent.com/120319917/209107632-4d8e014d-32e7-46c5-b675-259961136449.png)

**Comment by RockChinQ** [comment]
见 #37
