### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by 022c** [RockChinQ/QChatGPT#543]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

windows11

### Python环境

3.11

### 异常情况

前面的步骤一切正常，点开run-bot后，加载一段信息，显示初始化失败，但登录了QQ，却没有回复。另一边可以收到信息

### 报错信息

ImportError: cannot import name 'Image' from 'mirai' (F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\__init__.py)
[2023-08-12 02:40:11.764] main.py (284) - [ERROR] : 初始化失败:cannot import name 'Image' from 'mirai' (F:\jqrxxxxxxxxx\python\lib\site-packages\mirai\__init__.py)
[2023-08-12 02:40:13.777] main.py (290) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
[2023-08-12 02:40:25.790] main.py (298) - [INFO] : QQ: 3577698909, MAH: localhost:8080
[2023-08-12 02:40:25.798] main.py (299) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37

**Comment by RockChinQ** [comment]
用pip freeze查看一下yirimirai版本

**Comment by 022c** [comment]
> 用pip freeze查看一下yirimirai版本

aiohttp==3.8.5
aiosignal==1.3.1
APScheduler==3.10.1
async-timeout==4.0.3
attrs==23.1.0
Automat==22.10.0
beautifulsoup4==4.12.2
certifi==2023.7.22
cffi==1.15.1
charset-normalizer==3.2.0
constantly==15.1.0
cryptography==41.0.3
cssselect==1.2.0
exceptiongroup==1.1.2
filelock==3.12.2
frozenlist==1.4.0
h11==0.14.0
HTMLParser==0.0.2
hyperlink==21.0.0
idna==3.4
imageio==2.26.1
incremental==22.10.0
itemadapter==0.8.0
itemloaders==1.1.0
jmespath==1.0.1
lxml==4.9.3
multidict==6.0.4
MyQR==2.3.1
numpy==1.24.2
outcome==1.2.0
packaging==23.1
parsel==1.8.1
Pillow==9.4.0
Protego==0.3.0
pyasn1==0.5.0
pyasn1-modules==0.3.0
pycparser==2.21
PyDispatcher==2.0.7
pyOpenSSL==23.2.0
PySocks==1.7.1
pytz==2023.3
qqbot==2.3.11
queuelib==1.6.2
requests==2.31.0
requests-file==1.5.1
Scrapy==2.10.0
selenium==4.11.2
service-identity==23.1.0
six==1.16.0
sniffio==1.3.0
sortedcontainers==2.4.0
soupsieve==2.4.1
tldextract==3.4.4
trio==0.22.2
trio-websocket==0.10.3
Twisted==22.10.0
twisted-iocpsupport==1.0.4
typing_extensions==4.7.1
tzdata==2023.3
tzlocal==5.0.1
urllib3==2.0.4
w3lib==2.1.2
wsproto==1.2.0
yarl==1.9.2
zope.interface==6.0

**Comment by RockChinQ** [comment]
你这好像依赖没装全啊，按照文档手动部署的命令重新安装一下依赖

**Comment by 022c** [comment]
> 

我删除了重下后，mirai文件夹里没有文件只有一个mcl-installer-a02f711-windows-amd64.exe文件，是为什么阿
