### ISSUE TITLE
[Feature]: 插件中如何获取bot的nickname与qq号码？

### ISSUE THREAD

**Issue by oliverkirk-sudo** [RockChinQ/QChatGPT#547]
### 这是一个？

新功能

### 详细描述

如题

**Comment by RockChinQ** [comment]
目前只能获取到bot的QQ号，主程序也未感知bot的nickname

### `pkg.qqbot.manager.QQBotManager`对象的`bot_account_id`属性

```python
from pkg.utils import context

botmgr = context.get_qqbot_manager()  # 获取运行时QQBotManager对象
bot_id = botmgr.bot_account_id  # 获取qq号
```

**Comment by oliverkirk-sudo** [comment]
这样在插件里面把nickname打印出来了

**Comment by RockChinQ** [comment]
确实，host现在是获取不了底层的bot对象，但是不建议你去改源码，你可以直接按照刚刚的回复，获取QQBotManager的实例，这个实例中的`adapter`对象中的bot属性就是nakuru或者yirimirai框架的bot对象

**Comment by oliverkirk-sudo** [comment]
行
