### ISSUE TITLE
[BUG] ..\python\python.exe main.py
系统找不到指定的路径

### ISSUE THREAD

**Issue by yeming111111** [RockChinQ/QChatGPT#55]
想写啥都行
D:\qqchat>cd QChatGPT

D:\qqchat\QChatGPT>..\python\python.exe main.py
系统找不到指定的路径。

D:\qqchat\QChatGPT>pause
请按任意键继续. . .

**Comment by yeming111111** [comment]
最后一步，卡好久了

**Comment by RockChinQ** [comment]
自动部署还是手动部署？如果是自动部署请检查安装器同目录下是否包含python/文件夹以及其中包含的文件
