### ISSUE TITLE
[Bug]: 

### ISSUE THREAD

**Issue by luckyEason** [RockChinQ/QChatGPT#555]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

windows 10

### Python环境

python 3.9.3

### 异常情况

私聊回答会回复，聊群内不回复
![image](https://github.com/RockChinQ/QChatGPT/assets/109937362/3c3f1d9d-8d5e-4bd9-9bef-5ab85c789731)
![image](https://github.com/RockChinQ/QChatGPT/assets/109937362/8151b9e9-0090-45ce-b5f1-a89a4bafc76c)
![image](https://github.com/RockChinQ/QChatGPT/assets/109937362/1bfcdef1-b11b-4f0e-84c4-78676aec731c)

**Comment by RockChinQ** [comment]
被风控了，去go-cqhttp的issues查找解决办法
https://github.com/Mrs4s/go-cqhttp
