### ISSUE TITLE
[Feature]: 使用QQ官方SDK，在QQ频道中使用

### ISSUE THREAD

**Issue by zhoulvjun** [RockChinQ/QChatGPT#569]
### 这是一个？

新功能

### 详细描述

目前有办法在QQ频道中使用QChatGPT吗？

**Comment by RockChinQ** [comment]
暂时没有，可以看看[QQChannelChatGPT](https://github.com/Soulter/QQChannelChatGPT)或者尝试自行编写插件实现

**Comment by zhoulvjun** [comment]
感谢回复！
