### ISSUE TITLE
[Bug]: 运行./run-bot.sh时显示 “./run-bot.sh: line 2: ../python/bin/python3: No such file or directory”

### ISSUE THREAD

**Issue by EffortMax** [RockChinQ/QChatGPT#570]
### 这是一个？

新功能

### 详细描述

linux系统
安装器文件和python文件均多次检查，运行自动安装器后，../python文件夹中无bin文件夹；
run-mirai.sh可以正常运行并成功登陆账号；

**Comment by EffortMax** [comment]
比较小白 第一次提问请见谅

**Comment by EffortMax** [comment]
> 那应该是安装过程中下载失败了，国内主机经常有这个问题，可以尝试按照安装器文档所述的设置代理方法，或者提前手动下载好文档中说明的文件之后进行离线安装

谢谢大佬解答，还有个问题；

**Comment by EffortMax** [comment]
安装器文档里第二个get-pip.py文件要怎么下载呢，是全部复制下来创建一个py文件吗

**Comment by RockChinQ** [comment]
> 安装器文档里第二个get-pip.py文件要怎么下载呢，是全部复制下来创建一个py文件吗

对的

**Comment by EffortMax** [comment]
大佬 我三个文件都放在那个目录了，但是还是原问题，python文件夹中没有加载出bin文件夹；

**Comment by ZephyrusD** [comment]
> 那应该是安装过程中下载失败了，国内主机经常有这个问题，可以尝试按照安装器文档所述的设置代理方法，或者提前手动下载好文档中说明的文件之后进行离线安装

AWS EC2也出现了

**Comment by RockChinQ** [comment]
请根据文档进行手动部署
