### ISSUE TITLE
[Bug]: 函数调用

### ISSUE THREAD

**Issue by netses** [RockChinQ/QChatGPT#572]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

无

### Python环境

无

### 异常情况

chatgpt可能会调用未在`functions`字段中定义的函数，比如调用`python`运行代码等，这些函数要自己实现一遍。

**Comment by RockChinQ** [comment]
如果你使用的是官方api：这是gpt的问题，没办法修复；  
如果你使用的是revLibs插件提供的函数调用功能：可以到revLibs仓库查看一下实现的prompt，提pr帮助优化。
