### ISSUE TITLE
[Feature]: 请问一下config.py是指具体哪个位置的文件

### ISSUE THREAD

**Issue by laowangsiji** [RockChinQ/QChatGPT#573]
### 这是一个？

现有功能优化

### 详细描述

![image](https://github.com/RockChinQ/QChatGPT/assets/137143102/1e73568e-9219-4bb3-8a22-e8daefe106b6)
![image](https://github.com/RockChinQ/QChatGPT/assets/137143102/91d15e1b-5113-47ca-87fb-905b2065d8ca)
![image](https://github.com/RockChinQ/QChatGPT/assets/137143102/3b5c5cf3-9046-4d18-b5af-42434112f1d8)
该去哪个地址下的文件里面设置管理员qq和在哪里设置机器人qq密码呐

**Comment by RockChinQ** [comment]
就是你启动之后会自动生成一个config.py到main.py的同目录

**Comment by laowangsiji** [comment]
> 就是你启动之后会自动生成一个config.py到main.py的同目录；管理员是必须得设置的，设置成你的QQ号就行了

感谢，我第一次碰这种项目，没想到这么快你就回复了，我再去试一试

**Comment by laowangsiji** [comment]
> 就是你启动之后会自动生成一个config.py到main.py的同目录；管理员是必须得设置的，设置成你的QQ号就行了
![image](https://github.com/RockChinQ/QChatGPT/assets/137143102/19808268-63bf-4d76-a25e-4a67ad9dbcf0)
我按理说之前跑过一次docker run qchatgpt，出现了上图那个报错，可是没看到config.py的文件啊，难道是这个？

**Comment by RockChinQ** [comment]
> > 就是你启动之后会自动生成一个config.py到main.py的同目录；管理员是必须得设置的，设置成你的QQ号就行了
> ![image](https://github.com/RockChinQ/QChatGPT/assets/137143102/19808268-63bf-4d76-a25e-4a67ad9dbcf0)
> 我按理说之前跑过一次docker run qchatgpt，出现了上图那个报错，可是没看到config.py的文件啊，难道是这个？
> 

docker是吧，仔细看文档写的docker最佳实践指南文档吧
