### ISSUE TITLE
[Bug]: 机器人不能正常输出内容到QQ

### ISSUE THREAD

**Issue by Shadowshark996** [RockChinQ/QChatGPT#575]
### 部署方式

一键安装包部署

### 登录框架

Mirai

### 系统环境

Windows10

### Python环境

Python3.10

### 异常情况

机器人能正常接收消息，也能对指令做出反应，控制台中能看到已生成的文本，但无法正常接收消息，会显示超时

**Comment by RockChinQ** [comment]
#574
