### ISSUE TITLE
[Feature]: DALL·E 3 和 多模态架构设计

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/QChatGPT#579]
### 这是一个？

新功能

### 详细描述

接入 OpenAI DALL·E 3 模型并尝试支持多模态的架构

**Comment by leihao** [comment]
这个是不是也与新版关联的问题,就丢这里好了
[bot]err:

You tried to access openai.Image, but this is no longer supported in openai>=1.0.0 - see the README at https://github.com/openai/openai-python for the API.

You can run `openai migrate` to automatically upgrade your codebase to use the 1.0.0 interface. 

Alternatively, you can pin your installation to the old version, e.g. `pip install openai==0.28`

A detailed migration guide is available here: https://github.com/openai/openai-python/discussions/742

**Comment by RockChinQ** [comment]
在 #628 修复绘图命令不可用问题

**Comment by RockChinQ** [comment]
[更新到v2.6.7](https://github.com/RockChinQ/QChatGPT/discussions/595) 可解决绘图命令不可用问题，绘图命令不可用问题请不要再在此issue讨论

**Comment by RockChinQ** [comment]
多模态目前仅计划支持视觉，统一到 #619 跟踪。
