### ISSUE TITLE
[BUG]出现群聊未艾特也会回复的bug

### ISSUE THREAD

**Issue by 421zuoduan** [RockChinQ/QChatGPT#58]
群聊bot没有艾特也会进行回复，个人怀疑是私聊和群聊同时使用的问题，贴图如下：
![1](https://user-images.githubusercontent.com/108874795/209420026-91a08986-5274-4c76-8a0e-186e9a9c87e5.png)
![2](https://user-images.githubusercontent.com/108874795/209420019-40bc4c87-7b1d-48a9-ac48-fa6959368d28.png)
![3](https://user-images.githubusercontent.com/108874795/209420082-8c8499d9-138d-497e-9280-f7e59d0d1f06.png)
第一张图片是先与人进行了对话，在第二张图片中群聊中使用了bot，在晚上群聊使用bot的时候出现没有艾特也回复的现象。
![4](https://user-images.githubusercontent.com/108874795/209420111-4a932e48-d565-4e24-b44e-8da4bacac426.png)
第四张图片是今天上午我在私聊使用bot时，bot在群聊未艾特的情况下回复了群友的消息。

**Comment by RockChinQ** [comment]
由于 #28 增加此功能，但过于敏感的问题已被发现，在 #57 不再提供默认正则表达式匹配。
可到`config.py`将`response_rules`字段中的`regexp`项`[ ]`中的内容删除
