### ISSUE TITLE
[Bug]: 初始化失败:module 'httpcore' has no attribute 'ConnectionPool'

### ISSUE THREAD

**Issue by a86296007** [RockChinQ/QChatGPT#590]
### 部署方式

安装器部署

### 登录框架

Mirai

### 系统环境

Windows Server 2019 Datacenter

### Python环境

Python 3.10

### 异常情况

使用内置!update命令更新到最新版后无法启动，报错信息如下所示

### 报错信息

D:\QCG-2>cd QChatGPT

D:\QCG-2\QChatGPT>..\python\python.exe main.py
[2023-11-10 15:58:07.204] main.py (77) - [INFO] : 检查config模块完整性.
[2023-11-10 15:58:07.206] main.py (110) - [INFO] : 检查tips模块完整性.
正在更新依赖库，请等待...
这个操作不是必须的,如果不想更新,请在config.py中将upgrade_dependencies设置为False
WARNING: pip is being invoked by an old script wrapper. This will fail in a future version of pip.
Please see https://github.com/pypa/pip/issues/5599 for advice on fixing the underlying issue.
To avoid this problem you can invoke Python with '-m pip' instead of running pip directly.
Looking in indexes: https://pypi.tuna.tsinghua.edu.cn/simple
Requirement already satisfied: openai in d:\qcg-2\python\lib\site-packages (1.2.2)
Requirement already satisfied: Pillow in d:\qcg-2\python\lib\site-packages (10.1.0)
Requirement already satisfied: nakuru-project-idk in d:\qcg-2\python\lib\site-packages (0.0.2.1)
Requirement already satisfied: CallingGPT in d:\qcg-2\python\lib\site-packages (0.0.1.0)
Requirement already satisfied: tiktoken in d:\qcg-2\python\lib\site-packages (0.5.1)
Requirement already satisfied: anyio<4,>=3.5.0 in d:\qcg-2\python\lib\site-packages (from openai) (3.7.1)
Requirement already satisfied: distro<2,>=1.7.0 in d:\qcg-2\python\lib\site-packages (from openai) (1.8.0)
Requirement already satisfied: httpx<1,>=0.23.0 in d:\qcg-2\python\lib\site-packages (from openai) (0.25.1)
Requirement already satisfied: pydantic<3,>=1.9.0 in d:\qcg-2\python\lib\site-packages (from openai) (1.10.13)
Requirement already satisfied: tqdm>4 in d:\qcg-2\python\lib\site-packages (from openai) (4.66.1)
Requirement already satisfied: typing-extensions<5,>=4.5 in d:\qcg-2\python\lib\site-packages (from openai) (4.8.0)
Requirement already satisfied: aiohttp in d:\qcg-2\python\lib\site-packages (from nakuru-project-idk) (3.8.6)
Requirement already satisfied: async-lru in d:\qcg-2\python\lib\site-packages (from nakuru-project-idk) (2.0.4)
Requirement already satisfied: logbook in d:\qcg-2\python\lib\site-packages (from nakuru-project-idk) (1.7.0)
Requirement already satisfied: regex>=2022.1.18 in d:\qcg-2\python\lib\site-packages (from tiktoken) (2023.10.3)
Requirement already satisfied: requests>=2.26.0 in d:\qcg-2\python\lib\site-packages (from tiktoken) (2.31.0)
Requirement already satisfied: idna>=2.8 in d:\qcg-2\python\lib\site-packages (from anyio<4,>=3.5.0->openai) (3.4)
Requirement already satisfied: sniffio>=1.1 in d:\qcg-2\python\lib\site-packages (from anyio<4,>=3.5.0->openai) (1.3.0)
Requirement already satisfied: exceptiongroup in d:\qcg-2\python\lib\site-packages (from anyio<4,>=3.5.0->openai) (1.1.3)
Requirement already satisfied: certifi in d:\qcg-2\python\lib\site-packages (from httpx<1,>=0.23.0->openai) (2023.7.22)
Requirement already satisfied: httpcore in d:\qcg-2\python\lib\site-packages (from httpx<1,>=0.23.0->openai) (0.13.7)
Requirement already satisfied: charset-normalizer<4,>=2 in d:\qcg-2\python\lib\site-packages (from requests>=2.26.0->tiktoken) (3.3.2)
Requirement already satisfied: urllib3<3,>=1.21.1 in d:\qcg-2\python\lib\site-packages (from requests>=2.26.0->tiktoken) (2.0.7)
Requirement already satisfied: colorama in d:\qcg-2\python\lib\site-packages (from tqdm>4->openai) (0.4.6)
Requirement already satisfied: attrs>=17.3.0 in d:\qcg-2\python\lib\site-packages (from aiohttp->nakuru-project-idk) (23.1.0)
Requirement already satisfied: multidict<7.0,>=4.5 in d:\qcg-2\python\lib\site-packages (from aiohttp->nakuru-project-idk) (6.0.4)
Requirement already satisfied: async-timeout<5.0,>=4.0.0a3 in d:\qcg-2\python\lib\site-packages (from aiohttp->nakuru-project-idk) (4.0.3)
Requirement already satisfied: yarl<2.0,>=1.0 in d:\qcg-2\python\lib\site-packages (from aiohttp->nakuru-project-idk) (1.9.2)
Requirement already satisfied: frozenlist>=1.1.1 in d:\qcg-2\python\lib\site-packages (from aiohttp->nakuru-project-idk) (1.4.0)
Requirement already satisfied: aiosignal>=1.1.2 in d:\qcg-2\python\lib\site-packages (from aiohttp->nakuru-project-idk) (1.3.1)
Requirement already satisfied: h11<0.13,>=0.11 in d:\qcg-2\python\lib\site-packages (from httpcore->httpx<1,>=0.23.0->openai) (0.12.0)
Database initialized.
[2023-11-10 15:58:08.629] keymgr.py (78) - [INFO] : 使用api-key:default
Traceback (most recent call last):
  File "D:\QCG-2\QChatGPT\main.py", line 210, in start
    openai_interact = pkg.openai.manager.OpenAIInteract(config.openai_config['api_key'])
  File "D:\QCG-2\QChatGPT\.\pkg\openai\manager.py", line 36, in __init__
    self.client = openai.Client(
  File "D:\QCG-2\python\lib\site-packages\openai\_client.py", line 105, in __init__
    super().__init__(
  File "D:\QCG-2\python\lib\site-packages\openai\_base_client.py", line 738, in __init__
    self._client = http_client or httpx.Client(
  File "D:\QCG-2\python\lib\site-packages\httpx\_client.py", line 672, in __init__
    self._transport = self._init_transport(
  File "D:\QCG-2\python\lib\site-packages\httpx\_client.py", line 720, in _init_transport
    return HTTPTransport(
  File "D:\QCG-2\python\lib\site-packages\httpx\_transports\default.py", line 136, in __init__
    self._pool = httpcore.ConnectionPool(
AttributeError: module 'httpcore' has no attribute 'ConnectionPool'. Did you mean: 'SyncConnectionPool'?
[2023-11-10 15:58:08.644] main.py (287) - [ERROR] : 初始化失败:module 'httpcore' has no attribute 'ConnectionPool'
[2023-11-10 15:58:10.645] main.py (293) - [INFO] : 您正在使用Windows系统，若命令行窗口处于“选择”模式，程序可能会被暂停，此时请右键点击窗口空白区域使其取消选择模式。
[2023-11-10 15:58:22.646] main.py (301) - [INFO] : QQ: 2727399847, MAH: localhost:54142
[2023-11-10 15:58:22.654] main.py (302) - [CRITICAL] : 程序启动完成,如长时间未显示 "成功登录到账号xxxxx" ,并且不回复消息,解决办法(请勿到群里问): https://github.com/RockChinQ/QChatGPT/issues/37

**Comment by RockChinQ** [comment]
这个应该是依赖库版本问题，自行上网搜索看看

**Comment by a86296007** [comment]
> 这个应该是依赖库版本问题，自行上网搜索看看

大概搜了下，没找到完全相同的问题来着，试着用pip换了几个版本装也没解决（已经去config里面关掉自动更新了）

**Comment by huang177-jpg** [comment]
我也是这样，好像是yiri-mirai这个模块和新版本的openai模块不兼容的问题？

**Comment by RockChinQ** [comment]
> 我也是这样，好像是yiri-mirai这个模块和新版本的openai模块不兼容的问题？

差不多是这样😄

**Comment by Naka152** [comment]
试试看更新下httpcore

pip install --upgrade httpcore httpx

我也遇到这个问题 更新之后就正常了

**Comment by a86296007** [comment]
> 试试看更新下httpcore
> 
> pip install --upgrade httpcore httpx
> 
> 我也遇到这个问题 更新之后就正常了

试过了，还是不行

**Comment by RockChinQ** [comment]
实测 `pip install -U httpcore httpx` 是有效的，如果问题依旧，可能是因为你运行 QChatGPT 和你 pip 安装依赖的Python环境不是同一个，如果运行QChatGPT使用的不是系统默认Python环境（如使用安装器安装的、使用一键部署包部署的），可以找到启动QChatGPT时使用的python可执行文件，并执行以下命令

```bash
<你的python可执行文件> -m pip install -U httpcore httpx
```

**Comment by a86296007** [comment]
> 实测 `pip install -U httpcore httpx` 是有效的，如果问题依旧，可能是因为你运行 QChatGPT 和你 pip 安装依赖的Python环境不是同一个，如果运行QChatGPT使用的不是系统默认Python环境（如使用安装器安装的、使用一键部署包部署的），可以找到启动QChatGPT时使用的python可执行文件，并在命令行（终端）执行以下命令
> 
> ```shell
> <你的python可执行文件> -m pip install -U httpcore httpx
> ```
> 
> 若安装结束后出现依赖库版本冲突的警告，属正常现象。

解决了
