### ISSUE TITLE
[Bug]: 关于gpt4模型gpt-4-1106-vision-preview

### ISSUE THREAD

**Issue by huang177-jpg** [RockChinQ/QChatGPT#594]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

windows11

### Python环境

python11

### 异常情况

当我使用配置文件cofing.py中的gpt-4-vision-preview模型时，终端会一直循环这个消息，无法正常收到机器人消息[INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 200 OK"
当我切换回gpt-4-1106-preview时，一切又正常了
之前确实是有一段时间是叫gpt-4-vision-preview，但是我刚才去官方网页上看原来的gpt-4-vision-preview变成了gpt-4-1106-vision-preview。
这和openai官方修改模型名称有关系吗？

### 报错信息

![Screenshot_2023-11-13-01-20-19-32_df198e732186825c8df26e3c5a10d7cd](https://github.com/RockChinQ/QChatGPT/assets/136515817/25c9e8a6-a966-404b-b27c-74c912d48b58)

**Comment by RockChinQ** [comment]
目前不支持视觉feature，也没有测试过新发的vision模型在纯文本的表现，可以提供更多的控制台输出供排查

**Comment by RockChinQ** [comment]
gpt-4-vision-preview 的调用会出现意外的无限重试，这是openai库的逻辑，预计QChatGPT在支持视觉功能后会解决这个问题，请跟踪 #579

**Comment by huang177-jpg** [comment]
> gpt-4-vision-preview 的调用会出现意外的无限重试，这是openai库的逻辑，预计QChatGPT在支持视觉功能后会解决这个问题，请跟踪 #579

大佬加油｡◕‿◕｡
