### ISSUE TITLE
是否做了字数限制？

### ISSUE THREAD

**Issue by MoLu10086** [RockChinQ/QChatGPT#60]
我发现有些返回明显是截取过后的

**Comment by RockChinQ** [comment]
https://github.com/RockChinQ/QChatGPT/blob/c21639ce3a190ff5c31dc566208c26eda4ac383b/config-template.py#L73
https://github.com/RockChinQ/QChatGPT/blob/c21639ce3a190ff5c31dc566208c26eda4ac383b/config-template.py#L80
