### ISSUE TITLE
[Feature]: 请求支持OpenShamrock

### ISSUE THREAD

**Issue by ikun0014** [RockChinQ/QChatGPT#603]
### 这是一个？

新功能

### 详细描述

文档:https://whitechi73.github.io/OpenShamrock/
目前测试不会被风控

**Comment by liaofulong** [comment]
已使用nakuru适配器进行测试，目前可以正常消息，功能是否完整正在测试中

**Comment by RockChinQ** [comment]
将在 3.0 中正式支持
