### ISSUE TITLE
[Bug]: 收到的回复 不能显示图片

### ISSUE THREAD

**Issue by xupeng19881010** [RockChinQ/QChatGPT#605]
### 部署方式

Docker部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu

### Python环境

py310

### 异常情况

收到的回复 不能显示图片,能显示图片吗？

**Comment by RockChinQ** [comment]
请提供使用截图和控制台输出

**Comment by xupeng19881010** [comment]
![微信图片_20231120214110](https://github.com/RockChinQ/QChatGPT/assets/19513755/3d66c506-1af3-4c14-8679-4c8928fce3d2)
![微信图片_20231120214203](https://github.com/RockChinQ/QChatGPT/assets/19513755/a9ef0761-b358-4b5e-b33a-a841cb3db9de)

调用的google bard不知道为什么不显示图片，
想问一下画图该怎么调用，config该怎么配置

**Comment by RockChinQ** [comment]
通读文档再使用:

[wiki]https://github.com/RockChinQ/QChatGPT/wiki)
[社区文档](https://qchatgpt.rockchin.top/)

**Comment by xupeng19881010** [comment]
![QQ图片20231120224014](https://github.com/RockChinQ/QChatGPT/assets/19513755/90237356-880e-42e5-bb20-099994462bd2)
不支持了？？

**Comment by RockChinQ** [comment]
这个draw命令目前还没有适配dalle，并且计划在下一个版本移除，需要绘图可以尝试使用插件实现

**Comment by xupeng19881010** [comment]
是QChatAIPaint 这个插件？

**Comment by RockChinQ** [comment]
> 是QChatAIPaint 这个插件？

可以试试看，也可以自己写一个
