### ISSUE TITLE
[Bug]:429 Too many requests

### ISSUE THREAD

**Issue by a1014068504** [RockChinQ/QChatGPT#606]
### 部署方式

Docker部署

### 登录框架

go-cqhttp

### 系统环境

rockchin/qchatgpt:latest

### Python环境

3.10

### 异常情况

向OpenAI接口发送请求的时候，会报错，http429 Too Many Requests。

### 报错信息

[37m[2023-11-20 21:33:59.751] message.py (27) - [INFO] : [person_12345678]发送消息:介绍一下这个项目 https://git...[0m
[37m[2023-11-20 21:34:00.847] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-20 21:34:00.848] _base_client.py (919) - [INFO] : Retrying request to /chat/completions in 0.915115 seconds[0m
[37m[2023-11-20 21:34:02.015] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-20 21:34:02.015] _base_client.py (919) - [INFO] : Retrying request to /chat/completions in 1.881526 seconds[0m
[37m[2023-11-20 21:34:04.155] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-20 22:18:43.250] application.py (95) - [INFO] : Event: handling a event: FriendMessage[0m
[37m[2023-11-20 22:18:43.252] message.py (27) - [INFO] : [person_12345678]发送消息:查询[0m
[37m[2023-11-20 22:18:44.323] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-20 22:18:44.324] _base_client.py (919) - [INFO] : Retrying request to /chat/completions in 0.965826 seconds[0m
[37m[2023-11-20 22:18:45.542] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-20 22:18:45.543] _base_client.py (919) - [INFO] : Retrying request to /chat/completions in 1.825946 seconds[0m
[37m[2023-11-20 22:18:47.619] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-21 07:48:13.043] application.py (95) - [INFO] : Event: handling a event: FriendMessage[0m
[37m[2023-11-21 07:48:13.048] message.py (27) - [INFO] : [person_12345678]发送消息:查询[0m
[37m[2023-11-21 07:48:14.087] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-21 07:48:14.088] _base_client.py (919) - [INFO] : Retrying request to /chat/completions in 0.836453 seconds[0m
[37m[2023-11-21 07:48:15.223] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-21 07:48:15.224] _base_client.py (919) - [INFO] : Retrying request to /chat/completions in 1.782747 seconds[0m
[37m[2023-11-21 07:48:17.356] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-21 07:48:32.260] application.py (95) - [INFO] : Event: handling a event: FriendMessage[0m
[37m[2023-11-21 07:48:32.262] message.py (27) - [INFO] : [person_12345678]发送消息:gpt 你是谁[0m
[37m[2023-11-21 07:48:32.952] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-21 07:48:32.953] _base_client.py (919) - [INFO] : Retrying request to /chat/completions in 0.841468 seconds[0m
[37m[2023-11-21 07:48:34.052] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 429 Too Many Requests"[0m
[37m[2023-11-21 07:48:34.053] _base_client.py (919) - [INFO] : Retrying request to /chat/completions in 1.920742 seconds[0m

**Comment by RockChinQ** [comment]
OpenAI侧问题

**Comment by a1014068504** [comment]
邮件已收到~

**Comment by qq466627701** [comment]
这个确认是OpenAI侧的问题吗？reload后就可以重发请求了

**Comment by a1014068504** [comment]
邮件已收到~
