### ISSUE TITLE
[Bug]: 反代问题

### ISSUE THREAD

**Issue by acocchat** [RockChinQ/QChatGPT#607]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu1804

### Python环境

python3.10

### 异常情况

设置了反代地址，但是依然请求https://api.openai.com/v1/chat/completions。

openai_config = {
    "api_key": {
        "key1": "sk-vxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx"
    },
    "reverse_proxy": "https://xxx.xxx.com/v1"
}

### 报错信息

[2023-11-21 07:01:11.100] _client.py (1013) - [INFO] : HTTP Request: POST https://api.openai.com/v1/chat/completions "HTTP/1.1 401 Unauthorized"

**Comment by RockChinQ** [comment]
已修复，请等待下一版本发行( v2.6.6 )

**Comment by RockChinQ** [comment]
已更新，请根据 https://github.com/RockChinQ/QChatGPT/discussions/595 进行程序更新
