### ISSUE TITLE
[BUG] 部署成功，能显示收到消息，但是得不到回复。

### ISSUE THREAD

**Issue by xmh1011** [RockChinQ/QChatGPT#61]
如题
<img width="985" alt="image" src="https://user-images.githubusercontent.com/88817514/209555812-3e1a3c4e-eeeb-478b-8379-2621179e0be0.png">

**Comment by RockChinQ** [comment]
检查是否按照文档启动mirai和主程序

**Comment by wukibaka** [comment]
和楼主一样 部署成功但是得不到回复
