### ISSUE TITLE
[Bug]: claude ai json解析错误

### ISSUE THREAD

**Issue by xupeng19881010** [RockChinQ/QChatGPT#615]
### 部署方式

Docker部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu

### Python环境

py310

### 异常情况

使用claude 保json错误

### 报错信息

stderr: Traceback (most recent call last):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
stderr:     for section in session.get_reply(prompt):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 118, in get_reply
stderr:     for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/impls/claude.py", line 50, in get_reply
stderr:     resp = self.chatbot.send_message(prompt, self.conversation_id)
stderr:   File "/usr/local/lib/python3.10/site-packages/claude_api.py", line 129, in send_message
stderr:     data = json.loads(json_str)
stderr:   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
stderr:     return _default_decoder.decode(s)
stderr:   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
stderr:   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
stderr:     raise JSONDecodeError("Expecting value", s, err.value) from None
stderr: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
stderr: [31m[2023-11-25 21:43:11.825] procmsg.py (63) - [ERROR] : Traceback (most recent call last):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
stderr:     for section in session.get_reply(prompt):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 118, in get_reply
stderr:     for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/impls/claude.py", line 50, in get_reply
stderr:     resp = self.chatbot.send_message(prompt, self.conversation_id)
stderr:   File "/usr/local/lib/python3.10/site-packages/claude_api.py", line 129, in send_message
stderr:     data = json.loads(json_str)
stderr:   File "/usr/local/lib/python3.10/json/__init__.py", line 346, in loads
stderr:     return _default_decoder.decode(s)
stderr:   File "/usr/local/lib/python3.10/json/decoder.py", line 337, in decode
stderr:     obj, end = self.raw_decode(s, idx=_w(s, 0).end())
stderr:   File "/usr/local/lib/python3.10/json/decoder.py", line 355, in raw_decode
stderr:     raise JSONDecodeError("Expecting value", s, err.value) from None
stderr: json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

**Comment by RockChinQ** [comment]
尝试换个新cookies先

**Comment by xupeng19881010** [comment]
cookies已经换过重新获取过了，还是这样，我是用Cookie-Editor直接导出的json

**Comment by RockChinQ** [comment]
上游依赖问题，https://github.com/KoushikNavuluri/Claude-API 这个仓库的 issues 里查查

**Comment by xupeng19881010** [comment]
谢谢，获取了最新的commit解决了。。

**Comment by Cutelinwanfeng** [comment]
> 谢谢，获取了最新的commit解决了。。

请问怎么解决的 我连不上claude

**Comment by RockChinQ** [comment]
> > 谢谢，获取了最新的commit解决了。。
> 
> 请问怎么解决的 我连不上claude 

估计就是claude api那个项目又寄了，可以去那边的issues看看最新情况
