### ISSUE TITLE
[Bug]: google bard问题，IndexError: list index out of range

### ISSUE THREAD

**Issue by xupeng19881010** [RockChinQ/QChatGPT#617]
### 部署方式

Docker部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu

### Python环境

py310

### 异常情况

google bard 问题？

### 报错信息

stderr: Traceback (most recent call last):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
stderr:     for section in session.get_reply(prompt):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 118, in get_reply
stderr:     for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/impls/bard.py", line 54, in get_reply
stderr:     resp = self.chatbot.get_answer(prompt)
stderr:   File "/usr/local/lib/python3.10/site-packages/bardapi/core.py", line 332, in get_answer
stderr:     resp_dict = json.loads(resp.content.splitlines()[-5])[0][2]
stderr: IndexError: list index out of range
stderr: [31m[2023-11-26 15:26:58.739] procmsg.py (63) - [ERROR] : Traceback (most recent call last):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/procmsg.py", line 39, in process_message
stderr:     for section in session.get_reply(prompt):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/revss.py", line 118, in get_reply
stderr:     for reply_period_msg, reply_period_dict in self.__rev_interface_impl__.get_reply(prompt, **kwargs):
stderr:   File "/QChatGPT/plugins/revLibs/pkg/process/impls/bard.py", line 54, in get_reply
stderr:     resp = self.chatbot.get_answer(prompt)
stderr:   File "/usr/local/lib/python3.10/site-packages/bardapi/core.py", line 332, in get_answer
stderr:     resp_dict = json.loads(resp.content.splitlines()[-5])[0][2]
stderr: IndexError: list index out of range

**Comment by RockChinQ** [comment]
同样是上游依赖问题，请到 https://github.com/dsdanielpark/Bard-API/issues 反馈

**Comment by xupeng19881010** [comment]
已经解决
