### ISSUE TITLE
[Feature]: 希望支持AI图片视觉

### ISSUE THREAD

**Issue by a86296007** [RockChinQ/QChatGPT#619]
### 这是一个？

新功能

### 详细描述

GPT-4 with vision模型现在已经可以理解图片内容了，希望这边也整上这个功能（或者包含此功能的插件）

官方文档：https://platform.openai.com/docs/guides/vision

**Comment by a86296007** [comment]
细找了一下，看到之前好像已经有重复的issue了，那这个直接close吧

**Comment by Tigrex-Dai** [comment]
Claude3系列模型也都可以理解图片内容啦，期待一下！
官方文档：https://docs.anthropic.com/claude/docs/vision
