### ISSUE TITLE
[Bug]: gateway timeout504

### ISSUE THREAD

**Issue by kisara71** [RockChinQ/QChatGPT#624]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

 Ubuntu Server 22.04

### Python环境

Python3.10

### 异常情况

在请求长对话时会出现此错误。例如我问1+1等于几之类的可以正常回复，但是如果请求写一篇自我介绍之类的就会出现这个错误

### 报错信息

HTTP code 504 from API (<html>
<head><title>504 Gateway Time-out</title></head>
<body>
<center><h1>504 Gateway Time-out</h1></center>
<hr><center>openresty/1.19.9.1</center>
</body>
</html>
另外启动时也有问题，如下：[2023-12-02 20:09:36.225] host.py (84) - [ERROR] : 加载模块: plugins/randomimg/main.py 失败: (<class 'ModuleNotFoundError'>, ModuleNotFoundError("No module named 'lxml'"), <traceback object at 0x7fa05da2d740>)

**Comment by RockChinQ** [comment]
504是你反向代理的问题，去联系反向代理提供方。启动时报错是插件缺少依赖，自行安装依赖或者咨询插件作者。
