### ISSUE TITLE
如何修改请求地址为第三方网址来使用第三方的APIkey

### ISSUE THREAD

**Issue by Shadowshark996** [RockChinQ/QChatGPT#626]
新购入的API需要修改请求地址来使用，以下是该API的操作提示
使用方法：将原有程序中的请求地址替换为https://kkkc.net/ KEY改为本站生成的令牌即可 其他的无缝衔接官网请求

求教如何修改请求地址

**Comment by RockChinQ** [comment]
到`config.py`里，找到`openai_config`，根据注释说明修改反向代理地址（别忘了加`v1`)。

**Comment by Shadowshark996** [comment]
十分感谢您的快速回复，问题已解决
