### ISSUE TITLE
[BUG] 机器人在群聊中使用一段时间后，会出现“请求超时”的报错。

### ISSUE THREAD

**Issue by ShochanCPAS** [RockChinQ/QChatGPT#63]
![1](https://user-images.githubusercontent.com/61300794/209649516-6607f4c0-4ab6-4d33-bda5-c23f36fee363.png)
![2](https://user-images.githubusercontent.com/61300794/209649521-7ab5eaa1-3821-4285-9633-529e626f7a1f.png)
作者你好！
机器人在群聊中使用一段时间后，会出现“请求超时”的报错。

**Comment by RockChinQ** [comment]
截图中的“已过期”不是异常，是会话管理机制，详见文档“功能”部分以及配置文件中的相关设置；
若见到“请求超时”报错，则可能是网络较慢

**Comment by huming17** [comment]
代码是master最新, 此问题仍然存在，
`[bot]err:请求超时`
部署在服务器网络不慢，是否服务器需要部署到国外？

**Comment by RockChinQ** [comment]
> 代码是master最新, 此问题仍然存在， `[bot]err:请求超时` 部署在服务器网络不慢，是否服务器需要部署到国外？

这个是OpenAI的问题，近期OpenAI服务器响应较慢，只能重试或者将config.py中的超时时间改为更大数值以降低超时报错率
