### ISSUE TITLE
[Feature]: 希望能支持Bert-VITS2

### ISSUE THREAD

**Issue by Sprt98** [RockChinQ/QChatGPT#633]
### 这是一个？

新功能

### 详细描述

Bert-VITS2于2023年8月推出，现在已更新至2.2。
希望这边也整上这个功能（或者包含此功能的插件）。
我希望能支持Hugging Face上的Bert-VITS2模型、原神/星穹铁道语音合成在线推理网站（https://tts.ai-hobbyist.org/） 或者是本地推理。
然而，原神/星穹铁道语音合成在线推理网站（https://tts.ai-hobbyist.org/） 的API接口已失效，以后会推出新版API。

**Comment by RockChinQ** [comment]
这一个可以自己写个插件做一下吧，插件开发教程可以参考本仓库wiki

**Comment by RockChinQ** [comment]
这是应该由插件支持的功能，可以看看最近的：
https://github.com/the-lazy-me/RuiShengVoice
https://github.com/the-lazy-me/GenshinVoice
