### ISSUE TITLE
[Feature]: One-api更新支持了Google Gemini，不知道大佬有没有空也支持呢，感谢大佬。

### ISSUE THREAD

**Issue by DJonesT** [RockChinQ/QChatGPT#635]
### 这是一个？

新功能

### 详细描述

本人是个小白，要是提的issue不对，还请海涵，再次感谢。

**Comment by RockChinQ** [comment]
现已通过 One API 支持 Google Gemini Pro 模型；需要更新 One API 到 新版，创建 Gemini Pro 的渠道。更新 QChatGPT 到 v2.6.8 在 `config.py` 中修改 `completion_api_params` 的 `model` 为 `gemini-pro`。
