### ISSUE TITLE
[Bug]: gemini pro 报错

### ISSUE THREAD

**Issue by jsxupeng** [RockChinQ/QChatGPT#645]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

ubuntu

### Python环境

py310

### 异常情况

调用oneapi gemini pro返回数据有问题
Error code: 400 - {'error': {'message': "* GenerateContentRequest.contents[0].parts[0].data: required oneof field 'data' must have one initialized field\n (request id: 20231222105122808167575ttJofmwT)", 'type': '', 'param': '', 'code': 400}}

### 日志信息

stderr: [37m[2023-12-22 10:51:24.126] _client.py (1013) - [INFO] : HTTP Request: POST http://127.0.0.1:3005/v1/chat/completions "HTTP/1.1 400 Bad Request"[0m
stderr: [37m[2023-12-22 10:51:24.128] manager.py (392) - [INFO] : 通知管理员:person_840600000000API调用参数错误:Error code: 400 - {'error': {'message': "* GenerateContentRequest.contents[0].parts[0].data: required oneof field 'data' must have one initialized field\n (request id: 20231222105122808167575ttJofmwT)", 'type': '', 'param': '', 'code': 400}}
stderr: [0m

**Comment by RockChinQ** [comment]
#646  开一下调试模式，重试，然后把异常情况附近的输出都贴出来

**Comment by jsxupeng** [comment]
是不是我调用方式不对？

**Comment by RockChinQ** [comment]
不管你调用方式对不对，你都得把你详细日志给贴出来我才能给你排查啊

**Comment by jsxupeng** [comment]
贴在#646里了

**Comment by RockChinQ** [comment]
```

---------------------------
stderr: [37m[2023-12-22 11:02:00.988] message.py (27) - [INFO] : [person_840651001]发送消息:你好[0m
stderr: [32m[2023-12-22 11:02:00.988] host.py (445) - [DEBUG] : 触发事件: session_first_message_received (11)[0m
stderr: [32m[2023-12-22 11:02:00.988] host.py (487) - [DEBUG] : 事件 session_first_message_received (11) 处理完毕，返回值: {}[0m
stderr: [32m[2023-12-22 11:02:00.989] host.py (445) - [DEBUG] : 触发事件: prompt_pre_processing (12)[0m
stderr: [32m[2023-12-22 11:02:00.989] host.py (487) - [DEBUG] : 事件 prompt_pre_processing (12) 处理完毕，返回值: {}[0m
stderr: [32m[2023-12-22 11:02:00.989] session.py (409) - [DEBUG] : cut_out: [
stderr:     {
stderr:         "role": "system",
stderr:         "content": ""
stderr:     },
stderr:     {
stderr:         "role": "user",
stderr:         "content": "你好"
stderr:     }
stderr: ][0m
stderr: [32m[2023-12-22 11:02:01.515] model.py (25) - [DEBUG] : 请求接口参数: {'model': 'gemini-pro', 'messages': [{'role': 'system', 'content': ''}, {'role': 'user', 'content': '你好'}], 'temperature': 0.8}[0m
stderr: [32m[2023-12-22 11:02:01.523] _base_client.py (434) - [DEBUG] : Request options: {'method': 'post', 'url': '/chat/completions', 'files': None, 'json_data': {'messages': [{'role': 'system', 'content': ''}, {'role': 'user', 'content': '你好'}], 'model': 'gemini-pro', 'temperature': 0.8}}[0m
stderr: [32m[2023-12-22 11:02:01.528] _trace.py (45) - [DEBUG] : connect_tcp.started host='127.0.0.1' port=3005 local_address=None timeout=5.0 socket_options=None[0m
stderr: [32m[2023-12-22 11:02:01.529] _trace.py (45) - [DEBUG] : connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7ff4233a68c0>[0m
stderr: [32m[2023-12-22 11:02:01.529] _trace.py (45) - [DEBUG] : send_request_headers.started request=<Request [b'POST']>[0m
stderr: [32m[2023-12-22 11:02:01.530] _trace.py (45) - [DEBUG] : send_request_headers.complete[0m
stderr: [32m[2023-12-22 11:02:01.530] _trace.py (45) - [DEBUG] : send_request_body.started request=<Request [b'POST']>[0m
stderr: [32m[2023-12-22 11:02:01.530] _trace.py (45) - [DEBUG] : send_request_body.complete[0m
stderr: [32m[2023-12-22 11:02:01.530] _trace.py (45) - [DEBUG] : receive_response_headers.started request=<Request [b'POST']>[0m
stderr: [32m[2023-12-22 11:02:02.818] _trace.py (45) - [DEBUG] : receive_response_headers.complete return_value=(b'HTTP/1.1', 400, b'Bad Request', [(b'Content-Type', b'application/json; charset=utf-8'), (b'X-Oneapi-Request-Id', b'20231222110201530406978YXmSmp6T'), (b'Date', b'Fri, 22 Dec 2023 03:02:02 GMT'), (b'Content-Length', b'215')])[0m
stderr: [37m[2023-12-22 11:02:02.819] _client.py (1013) - [INFO] : HTTP Request: POST http://127.0.0.1:3005/v1/chat/completions "HTTP/1.1 400 Bad Request"[0m
stderr: [32m[2023-12-22 11:02:02.820] _trace.py (45) - [DEBUG] : receive_response_body.started request=<Request [b'POST']>[0m
stderr: [32m[2023-12-22 11:02:02.820] _trace.py (45) - [DEBUG] : receive_response_body.complete[0m
stderr: [32m[2023-12-22 11:02:02.820] _trace.py (45) - [DEBUG] : response_closed.started[0m
stderr: [32m[2023-12-22 11:02:02.820] _trace.py (45) - [DEBUG] : response_closed.complete[0m
stderr: [32m[2023-12-22 11:02:02.821] _base_client.py (907) - [DEBUG] : HTTP Request: POST http://127.0.0.1:3005/v1/chat/completions "400 Bad Request"[0m
stderr: [37m[2023-12-22 11:02:02.821] manager.py (392) - [INFO] : 通知管理员:person_840651001API调用参数错误:Error code: 400 - {'error': {'message': "* GenerateContentRequest.contents[0].parts[0].data: required oneof field 'data' must have one initialized field\n (request id: 20231222110201530406978YXmSmp6T)", 'type': '', 'param': '', 'code': 400}}
stderr: [0m
stderr: [32m[2023-12-22 11:02:02.822] selector_events.py (54) - [DEBUG] : Using selector: EpollSelector[0m
stderr: [32m[2023-12-22 11:02:02.826] network.py (15) - [DEBUG] : Network: requested url=http://127.0.0.1:8567/send_private_msg, by data_map={'user_id': 840651001, 'message': '[bot]person_840651001API调用参数错误:Error code: 400 - {\'error\': {\'message\': "* GenerateContentRequest.contents[0].parts[0].data: required oneof field \'data\' must have one initialized field\\n (request id: 20231222110201530406978YXmSmp6T)", \'type\': \'\', \'param\': \'\', \'code\': 400}}\n', 'auto_escape': False}, and status=200, data={"data":{"message_id":-93128849},"message":"","retcode":0,"status":"ok"}
stderr: [0m
stderr: [37m[2023-12-22 11:02:02.827] process.py (153) - [INFO] : 回复[person_840651001]文字消息:[bot]err:出错了，请稍后再试[0m
stderr: [32m[2023-12-22 11:02:02.827] session.py (132) - [DEBUG] : person_840651001,lock release,<locked _thread.lock object at 0x7ff487a65380>[0m
stderr: [32m[2023-12-22 11:02:02.827] session.py (134) - [DEBUG] : person_840651001,lock release successfully,<unlocked _thread.lock object at 0x7ff487a65380>[0m
stderr: [37m[2023-12-22 11:02:02.828] process.py (183) - [INFO] : [风控] 强制延迟0.53秒(如需关闭，请到config.py修改force_delay_range字段)[0m
stderr: [32m[2023-12-22 11:02:03.355] selector_events.py (54) - [DEBUG] : Using selector: EpollSelector[0m
```

**Comment by jsxupeng** [comment]
stderr: [37m[2023-12-22 11:02:00.988] message.py (27) - [INFO] : [person_840651001]发送消息:你好[0m
stderr: [32m[2023-12-22 11:02:00.988] host.py (445) - [DEBUG] : 触发事件: session_first_message_received (11)[0m
stderr: [32m[2023-12-22 11:02:00.988] host.py (487) - [DEBUG] : 事件 session_first_message_received (11) 处理完毕，返回值: {}[0m
stderr: [32m[2023-12-22 11:02:00.989] host.py (445) - [DEBUG] : 触发事件: prompt_pre_processing (12)[0m
stderr: [32m[2023-12-22 11:02:00.989] host.py (487) - [DEBUG] : 事件 prompt_pre_processing (12) 处理完毕，返回值: {}[0m
stderr: [32m[2023-12-22 11:02:00.989] session.py (409) - [DEBUG] : cut_out: [
stderr:     {
stderr:         "role": "system",
stderr:         "content": ""
stderr:     },
stderr:     {
stderr:         "role": "user",
stderr:         "content": "你好"
stderr:     }
stderr: ][0m
stderr: [32m[2023-12-22 11:02:01.515] model.py (25) - [DEBUG] : 请求接口参数: {'model': 'gemini-pro', 'messages': [{'role': 'system', 'content': ''}, {'role': 'user', 'content': '你好'}], 'temperature': 0.8}[0m
stderr: [32m[2023-12-22 11:02:01.523] _base_client.py (434) - [DEBUG] : Request options: {'method': 'post', 'url': '/chat/completions', 'files': None, 'json_data': {'messages': [{'role': 'system', 'content': ''}, {'role': 'user', 'content': '你好'}], 'model': 'gemini-pro', 'temperature': 0.8}}[0m
stderr: [32m[2023-12-22 11:02:01.528] _trace.py (45) - [DEBUG] : connect_tcp.started host='127.0.0.1' port=3005 local_address=None timeout=5.0 socket_options=None[0m
stderr: [32m[2023-12-22 11:02:01.529] _trace.py (45) - [DEBUG] : connect_tcp.complete return_value=<httpcore._backends.sync.SyncStream object at 0x7ff4233a68c0>[0m
stderr: [32m[2023-12-22 11:02:01.529] _trace.py (45) - [DEBUG] : send_request_headers.started request=<Request [b'POST']>[0m
stderr: [32m[2023-12-22 11:02:01.530] _trace.py (45) - [DEBUG] : send_request_headers.complete[0m
stderr: [32m[2023-12-22 11:02:01.530] _trace.py (45) - [DEBUG] : send_request_body.started request=<Request [b'POST']>[0m
stderr: [32m[2023-12-22 11:02:01.530] _trace.py (45) - [DEBUG] : send_request_body.complete[0m
stderr: [32m[2023-12-22 11:02:01.530] _trace.py (45) - [DEBUG] : receive_response_headers.started request=<Request [b'POST']>[0m
stderr: [32m[2023-12-22 11:02:02.818] _trace.py (45) - [DEBUG] : receive_response_headers.complete return_value=(b'HTTP/1.1', 400, b'Bad Request', [(b'Content-Type', b'application/json; charset=utf-8'), (b'X-Oneapi-Request-Id', b'20231222110201530406978YXmSmp6T'), (b'Date', b'Fri, 22 Dec 2023 03:02:02 GMT'), (b'Content-Length', b'215')])[0m
stderr: [37m[2023-12-22 11:02:02.819] _client.py (1013) - [INFO] : HTTP Request: POST http://127.0.0.1:3005/v1/chat/completions "HTTP/1.1 400 Bad Request"[0m
stderr: [32m[2023-12-22 11:02:02.820] _trace.py (45) - [DEBUG] : receive_response_body.started request=<Request [b'POST']>[0m
stderr: [32m[2023-12-22 11:02:02.820] _trace.py (45) - [DEBUG] : receive_response_body.complete[0m
stderr: [32m[2023-12-22 11:02:02.820] _trace.py (45) - [DEBUG] : response_closed.started[0m
stderr: [32m[2023-12-22 11:02:02.820] _trace.py (45) - [DEBUG] : response_closed.complete[0m
stderr: [32m[2023-12-22 11:02:02.821] _base_client.py (907) - [DEBUG] : HTTP Request: POST http://127.0.0.1:3005/v1/chat/completions "400 Bad Request"[0m
stderr: [37m[2023-12-22 11:02:02.821] manager.py (392) - [INFO] : 通知管理员:person_840651001API调用参数错误:Error code: 400 - {'error': {'message': "* GenerateContentRequest.contents[0].parts[0].data: required oneof field 'data' must have one initialized field\n (request id: 20231222110201530406978YXmSmp6T)", 'type': '', 'param': '', 'code': 400}}
stderr: [0m
stderr: [32m[2023-12-22 11:02:02.822] selector_events.py (54) - [DEBUG] : Using selector: EpollSelector[0m
stderr: [32m[2023-12-22 11:02:02.826] network.py (15) - [DEBUG] : Network: requested url=http://127.0.0.1:8567/send_private_msg, by data_map={'user_id': 840651001, 'message': '[bot]person_840651001API调用参数错误:Error code: 400 - {\'error\': {\'message\': "* GenerateContentRequest.contents[0].parts[0].data: required oneof field \'data\' must have one initialized field\\n (request id: 20231222110201530406978YXmSmp6T)", \'type\': \'\', \'param\': \'\', \'code\': 400}}\n', 'auto_escape': False}, and status=200, data={"data":{"message_id":-93128849},"message":"","retcode":0,"status":"ok"}
stderr: [0m
stderr: [37m[2023-12-22 11:02:02.827] process.py (153) - [INFO] : 回复[person_840651001]文字消息:[bot]err:出错了，请稍后再试[0m
stderr: [32m[2023-12-22 11:02:02.827] session.py (132) - [DEBUG] : person_840651001,lock release,<locked _thread.lock object at 0x7ff487a65380>[0m
stderr: [32m[2023-12-22 11:02:02.827] session.py (134) - [DEBUG] : person_840651001,lock release successfully,<unlocked _thread.lock object at 0x7ff487a65380>[0m
stderr: [37m[2023-12-22 11:02:02.828] process.py (183) - [INFO] : [风控] 强制延迟0.53秒(如需关闭，请到config.py修改force_delay_range字段)[0m
stderr: [32m[2023-12-22 11:02:03.355] selector_events.py (54) - [DEBUG] : Using selector: EpollSelector[0m

**Comment by RockChinQ** [comment]
One API 的问题。

1. 确认 One API 请求 Gemini 时不是在中国境内
2. 确认 One API 正常调用 Gemini
3. 找 [One API](https://github.com/songquanpeng/one-api/issues) 帮忙排查

**Comment by RockChinQ** [comment]
自己也遇到了，重试之后就可以了。参考 https://github.com/songquanpeng/one-api/issues/853 ，根据其中的信息，如果确定你的主机没有被 Google 封禁，可以尝试用英文提问。

**Comment by jsxupeng** [comment]
默认情况下qchatgpt怎么切换到使用gemini pro这个模型

**Comment by RockChinQ** [comment]
> 默认情况下qchatgpt怎么切换到使用gemini pro这个模型

要用哪个模型，在`config.py`中修改一下`completion_api_params`的model名称就可以了，需要在运行时修改模型可以通过:

- `!cfg` 命令，可以在[这里](https://qchatgpt.rockchin.top/posts/feature.html#%E6%9C%BA%E5%99%A8%E4%BA%BA%E5%91%BD%E4%BB%A4) 查看说明
- 使用[Swticher插件](https://github.com/RockChinQ/Switcher)，不过 Switcher 插件暂时还没有适配 Gemini Pro

**Comment by xupeng19881010** [comment]
我装了[revLibs](https://github.com/RockChinQ/revLibs/tree/master)这个插件后，切换不了默认了，启动后就直接进入这个参数reverse_lib = "acheong08/ChatGPT.V1" 设置的模型里，切换不了默认了

**Comment by RockChinQ** [comment]
> 我装了[revLibs](https://github.com/RockChinQ/revLibs/tree/master)这个插件后，切换不了默认了，启动后就直接进入这个参数reverse_lib = "acheong08/ChatGPT.V1" 设置的模型里，切换不了默认了

与本issue主题无关；插件问题单独提issue或者到插件仓库提issue
