### ISSUE TITLE
[Bug]: 使用OpenShamrock下群聊消息会导致程序崩溃

### ISSUE THREAD

**Issue by DDDD-zzz** [RockChinQ/QChatGPT#671]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

小米MIX4

### Python环境

Python3.10.12

### QChatGPT版本

v2.6.10 优化审计API调用逻辑

### 异常情况

私聊能够正常回复,在群聊里触发机器人后会异常

### 日志信息

![screenshot-20240124-183748](https://github.com/RockChinQ/QChatGPT/assets/46891488/4393c81e-9a79-487d-95fb-190ab19328ad)
![6555C1EB5AF1E1438E0D1CFD3B3DF4A3](https://github.com/RockChinQ/QChatGPT/assets/46891488/49f57a00-a98b-4007-aa88-75ff0b795738)

### 启用的插件

Switcher

**Comment by RockChinQ** [comment]
确实，目前未完美适配shamrock。预计过几个版本完善。

**Comment by RockChinQ** [comment]
将在 3.0 版本中正式支持
