### ISSUE TITLE
[Bug]: !cmd指令无法回应

### ISSUE THREAD

**Issue by bobandbrony** [RockChinQ/QChatGPT#676]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

Windows10 ltsc 中国四川

### Python环境

python 3.9

### QChatGPT版本

v2.6.10

### 异常情况

给机器人发送!cmd指令时，机器人无法发送相应信息，gocq报错

### 日志信息

goroutine 43521 [running]:
net/http.(*conn).serve.func1()
        net/http/server.go:1854 +0xbf
panic({0x6f3040, 0xc000376180})
        runtime/panic.go:890 +0x263
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).nextAddr(0x74d73?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/highway.go:227 +0xfd
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).selectConn(0x25910?)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/highway.go:248 +0xe5
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).uploadSingle(0xc0000d47e0, {0x1b, {0x843600, 0xc00048aa80}, {0xc0004145f0, 0x10,
 0x10}, 0x311, {0xc0002b40e0, 0x68, ...}, ...})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/bdh.go:39 +0x68
github.com/Mrs4s/MiraiGo/client/internal/highway.(*Session).Upload(0xc0000d47e0, {0x1b, {0x843600, 0xc00048aa80}, {0xc0004145f0, 0x10, 0x10}
, 0x311, {0xc0002b40e0, 0x68, ...}, ...})
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/internal/highway/bdh.go:117 +0x425
github.com/Mrs4s/MiraiGo/client.(*ForwardMessageBuilder).Main(0xc0003954f8, 0xc000466708)
        github.com/Mrs4s/MiraiGo@v0.0.0-20230823050531-a8213e127b2b/client/multimsg.go:316 +0x5b8
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).uploadForwardElement(0xc00013ca00, {0x5, {0xc0002ac024, 0x51a}, {0x0, 0x0}, 0x0, 0x24, {0x0, 0x0,
...}}, ...)
        github.com/Mrs4s/go-cqhttp/coolq/api.go:962 +0x1e5
github.com/Mrs4s/go-cqhttp/coolq.(*CQBot).CQSendGroupForwardMessage(0xc00013ca00, 0x25575d35?, {0x5, {0xc0002ac024, 0x51a}, {0x0, 0x0}, 0x0,
 0x24, {0x0, ...}})
        github.com/Mrs4s/go-cqhttp/coolq/api.go:978 +0x7d
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).call(0xc000353320, {0xc0002c62c6, 0x16}, 0xbf5620, {0x843e60, 0xc0004280c0})
        github.com/Mrs4s/go-cqhttp/modules/api/api.go:38 +0x1ac5
github.com/Mrs4s/go-cqhttp/modules/api.(*Caller).Call(0xc000353320, {0xc0002c62c6, 0x16}, 0x0?, {0x843e60, 0xc0004280c0})
        github.com/Mrs4s/go-cqhttp/modules/api/caller.go:35 +0xc5
github.com/Mrs4s/go-cqhttp/server.(*httpServer).ServeHTTP(0xc000353300, {0x847e70, 0xc0001ae1c0}, 0xc000092f00)
        github.com/Mrs4s/go-cqhttp/server/http.go:213 +0x8ba
net/http.serverHandler.ServeHTTP({0x8467b8?}, {0x847e70, 0xc0001ae1c0}, 0xc000092f00)
        net/http/server.go:2936 +0x316
net/http.(*conn).serve(0xc000132a20, {0x848360, 0xc0002e1b30})
        net/http/server.go:1995 +0x612
created by net/http.(*Server).Serve
        net/http/server.go:3089 +0x5ed

### 启用的插件

无

**Comment by RockChinQ** [comment]
你这个是 go-cqhttp 的问题。
