### ISSUE TITLE
[Feature]: 支持提示词变量

### ISSUE THREAD

**Issue by iyxddw** [RockChinQ/QChatGPT#683]
### 这是一个？

新功能

### 详细描述

在提示词中加入变量实现类似于{用户}问了{问题}的功能

**Comment by RockChinQ** [comment]
详细描述一下，提供一些案例什么的

**Comment by RockChinQ** [comment]
要不自己写个插件做这个吧，QChatGPT 提供了一个 PreProcess 的事件，可以看看文档，实现方式可以参考[预处理插件](https://github.com/RockChinQ/CommonPreprocess)
