### ISSUE TITLE
[Bug]: !default命令不能用（？）

### ISSUE THREAD

**Issue by youyi0218** [RockChinQ/QChatGPT#684]
### 部署方式

手动部署

### 登录框架

go-cqhttp

### 系统环境

win10专业版

### Python环境

3.10

### QChatGPT版本

2.6.10

### 异常情况

config.py中写道“# 也可以使用命令：
# !default <名称>
#   将指定的情景预设设置为默认情景预设”但是对机器人使用却返回“[bot]err:命令不存在：default.meimo”

### 日志信息

![image](https://github.com/RockChinQ/QChatGPT/assets/135406843/87d3e889-f45d-4f0c-9f4b-f4a6c345482f)

### 启用的插件

Webwlk

**Comment by RockChinQ** [comment]
哦现在是要用 `!default set <名称>`才可以
