### ISSUE TITLE
[Bug]: !default这个命令会直接说出所有系统提示词，这个命令不是只有主人能输入，其他人也可以输入

### ISSUE THREAD

**Issue by lueluelue2006** [RockChinQ/QChatGPT#686]
### 这是一个？

现有功能优化

### 详细描述

!default这个命令会直接说出所有系统提示词，这个命令不是只有主人能输入，其他人也可以输入

**Comment by RockChinQ** [comment]
你可以在 cmdpriv.json 中修改命令的最低权限级别，详情查看：https://qchatgpt.rockchin.top/posts/feature.html#%E5%91%BD%E4%BB%A4%E6%9D%83%E9%99%90%E6%8E%A7%E5%88%B6
