### ISSUE TITLE
请问如何自定义模型名？例如gpt-4-all

### ISSUE THREAD

**Issue by lueluelue2006** [RockChinQ/QChatGPT#687]
### 这是一个？

新功能

### 详细描述

请问如何自定义模型名？例如gpt-4-all

**Comment by RockChinQ** [comment]
暂时不支持，这个需求是从何而来？

**Comment by lueluelue2006** [comment]
> 暂时不支持，这个需求是从何而来？

有很多OneAPI站点有自定义名字的模型，比如说gpt-4-all来表示plus。还有一些比如说deepseek，Kimi等模型
