### ISSUE TITLE
[Feature]: 希望在内容审核能力侧可以支持扩展，方便增加自定义增加安全过滤的能力

### ISSUE THREAD

**Issue by samzong** [RockChinQ/QChatGPT#689]
### 这是一个？

新功能

### 详细描述

需要的几件事情：

* 基于内容做脱敏替换
* 内容安全审核、广告识别
* 增加自动化路由的内部私有模型（特定场景）

**Comment by RockChinQ** [comment]
已支持组件扩展，请等待 v3.1 发布后查看文档中的组件扩展方式。
