### ISSUE TITLE
[Bug]: 处理对话时尝试访问“openaipublic.blob.core.windows.net”并失败

### ISSUE THREAD

**Issue by a86296007** [RockChinQ/QChatGPT#691]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Windows Server 2022 中国大陆-宿迁

### Python环境

Python 3.11

### QChatGPT版本

v3.0.0

### 异常情况

部署使用的云服务器所在的网络环境比较奇怪，无法直连github等大多数不那么稳定的国外网站，不过反代此前一直可以正常使用。

在部署新版本QCG之后，第一次测试对话弹出错误并反复发生（具体内容参考日志信息）。

之后用科学上网并移除反代连接了一次，成功；随后再断开科学上网恢复使用反代地址，就可以正常对话，短期内并没有再次触发这个错误（即使重启bot也不会触发）。

### 日志信息

[
[qcg-2024-02-19-23-22-34.log](https://github.com/RockChinQ/QChatGPT/files/14334455/qcg-2024-02-19-23-22-34.log)
](url)

### 启用的插件

无

**Comment by RockChinQ** [comment]
这个是计算token数时访问openai服务器失败导致的，可以尝试在 `data/config/system.json`里设置一个正向代理试试看

**Comment by a86296007** [comment]
> 这个是计算token数时访问openai服务器失败导致的，可以尝试在 `data/config/system.json`里设置一个正向代理试试看

我这边大概没有长时间使用正向代理的条件，不知能否添加一个跳过此步骤的设置呢

**Comment by RockChinQ** [comment]
已删除 分词器 ，不再进行分词分割上文阶段：
commit 1d963d0f0c3335a36a78b6c66bde1cf010a5ad29
