### ISSUE TITLE
[Bug]: 下载的插件指令使用时均为未知指令

### ISSUE THREAD

**Issue by RWFYS** [RockChinQ/QChatGPT#713]
### 部署方式

手动部署

### 登录框架

Mirai

### 系统环境

Windows 10 专业版 22H2 中国

### Python环境

Python 3.9.13 (tags/v3.9.13:6de2ca5, May 17 2022, 16:36:42)

### QChatGPT版本

当前版本:  v3.0.2

### 异常情况

刚下下来就有的问题，问题：任何附加插件的指令都无法识别（包括官方提供插件目录下的），这两天在研究自制插件实在是解决不了这个问题所以才来问

### 日志信息

[qcg-2024-03-08-20-45-58.log](https://github.com/RockChinQ/QChatGPT/files/14538288/qcg-2024-03-08-20-45-58.log)

### 启用的插件

启用[SysStatPlugin]
启用了Hello world
启用了Server MC(这个是自己写的删了和不删没有区别）

**Comment by RockChinQ** [comment]
3.x 触发命令事件时，传入的 `command` 参数本应为 删除 `!` 第一段字符串（`sys`)，但遗漏了删除 `!` 的步骤（错误地传入 `!sys`），现已在 最新代码修复，下一版本发布后，将恢复为 删除了 `!` 的第一节命令（`sys`)。

**Comment by RWFYS** [comment]
谢谢，已解决问题
