### ISSUE TITLE
[Bug]: 回复bot时会给api提供额外的@{qq} 信息

### ISSUE THREAD

**Issue by murasamme** [RockChinQ/QChatGPT#716]
### 部署方式

手动部署

### 登录框架

None

### 系统环境

Ubuntu

### Python环境

Python 3.10.12

### QChatGPT版本

v3.0.2

### 异常情况

在群里做回复操作时，

**Comment by murasamme** [comment]
设置at响应，回复机器人时候会把@[机器人qq] 也给送到api里，某些语境下会干扰回答

回复机器人：
![EAB45AF26E4273C39E2D4B114FFF39AB](https://github.com/RockChinQ/QChatGPT/assets/52225526/c9a20922-9b3c-4dc6-9171-05d473ff4a6d)

机器人回复：
![F1625ED015F3936F16EDD09C0051BC89](https://github.com/RockChinQ/QChatGPT/assets/52225526/d93e455c-fe5f-4974-b78a-525c62a0aa62)

后台日志：
![ECF5FEFE45392759A185763F3CCA01DD](https://github.com/RockChinQ/QChatGPT/assets/52225526/422242ce-7ff8-4faf-9f6c-2806a930cf86)


使用的aiocqhttp适配器

**Comment by murasamme** [comment]
使用插件：无
登陆框架：Lagrange

**Comment by murasamme** [comment]
设置at触发的条件下，仅回复bot信息不进行at也会触发消息。也就是当回复+at时触发bot的应该是回复事件，而at则作为消息内容传递出去了。这部分可以做一下区分
![{E2DFC838-C216-4146-8BEB-E448526D298A}](https://github.com/RockChinQ/QChatGPT/assets/52225526/c4376d4c-6908-4abe-80ef-17cd3d8f7086)
![QQ截图20240312154651](https://github.com/RockChinQ/QChatGPT/assets/52225526/719d94cb-37aa-4733-87d6-060783a58a5f)

**Comment by RockChinQ** [comment]
用的什么消息框架登录的？

**Comment by RockChinQ** [comment]
已修复。
