### ISSUE TITLE
[Feature]: 希望添加私聊响应规则或私聊响应开关

### ISSUE THREAD

**Issue by murasamme** [RockChinQ/QChatGPT#717]
### 这是一个？

新功能

### 详细描述

目前只有群聊响应规则和忽略规则，私聊则是必定响应，在双开bot和某些情况下影响私聊调试，可否添加一个私聊响应规则或者私聊响应开关？

另外可能还需要用到私聊白名单和黑名单，对bot的好友使用进行管控

example：
![04BFAA62EF6EF9FCBF79E7445BF71991](https://github.com/RockChinQ/QChatGPT/assets/52225526/7e513762-29f4-4f6d-ad0c-413a50f1184b)

**Comment by RockChinQ** [comment]
黑白名单现在支持的: https://qchatgpt.rockchin.top/posts/config/pipeline.html#%E8%AE%BF%E9%97%AE%E6%8E%A7%E5%88%B6-access-control

私聊响应规则就不做了，可以自己写一个 内容过滤器 来实现：https://qchatgpt.rockchin.top/posts/plugin/extension.html#%E5%86%85%E5%AE%B9%E8%BF%87%E6%BB%A4%E5%99%A8
