### ISSUE TITLE
[Plugin]: 请求登记新插件

### ISSUE THREAD

**Issue by Yuumi0221** [RockChinQ/QChatGPT#720]
### 插件名称

URLMaskerPlugin

### 插件代码库地址

https://github.com/Yuumi0221/URLMaskerPlugin

### 插件简介

URL打码功能插件，关联：#715

**Comment by RockChinQ** [comment]
感谢贡献，已添加到：

- https://qchatgpt.rockchin.top/posts/plugin/list.html
- https://github.com/stars/RockChinQ/lists/qchatgpt-%E6%8F%92%E4%BB%B6
