### ISSUE TITLE
[ENHANCE]希望增强回复的方式

### ISSUE THREAD

**Issue by Almightly** [RockChinQ/QChatGPT#73]
希望ai回复的时候表明是回复的哪一句话，同时表明自己是机器人

**Comment by RockChinQ** [comment]
目前暂无引用回复功能，您可以在config.py中设置以下字段来使机器人的回复文字加上`[GPT]`前缀：
```
# 回复消息时是否显示[GPT]前缀
show_prefix = False
```

**Comment by RockChinQ** [comment]
已新增此功能，要在已部署的程序上启用此功能，请先使用`git pull`拉取最新代码，并在`config.py`中添加以下内容
```
# 回复消息时是否引用原消息
quote_origin = True
```
