### ISSUE TITLE
[Bug]: 访问控制 access-control配置项blacklist和whitelist均无效无效

### ISSUE THREAD

**Issue by bright141** [RockChinQ/QChatGPT#736]
### 部署方式

Docker部署

### 消息平台适配器

yiri-mirai（Mirai）

### 系统环境

debian 11 arm64

### Python环境

使用的容器环境

### QChatGPT版本

3.10

### 异常情况

正确配置访问控制 access-control配置项blacklist和whitelist后，在blacklist下无论在不在列表内均会触发ai聊天。whitelist下与blacklist一致

**Comment by RockChinQ** [comment]
已修复，等待发版
