### ISSUE TITLE
接受QQ自带的表情包请求失败

### ISSUE THREAD

**Issue by coolbeiyu1** [RockChinQ/QChatGPT#737]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

window10

### Python环境

python10

### QChatGPT版本

3.1.0

### 异常情况

[Bug]: 一接受QQ自带的表情包就请求失败，然后怎么聊天都请求失败

### 日志信息

<img width="718" alt="04FE6FBDFB595099BDE43C5214C51FE0" src="https://github.com/RockChinQ/QChatGPT/assets/163013919/3450ff55-b8f1-4b96-8f05-14f556f4870d">

### 启用的插件

[2024-03-23 14:31:29.517] C:\Users\Administrator\Desktop\ai\QChatGPT-3.1.0\QChatGPT-3.1.0\pkg\pipeline\process\handlers\chat.py (97) - [ERROR] :
    对话(1)请求失败: 模型请求失败: 请求参数错误: Error code: 400 - {'error': {'message': "* GenerateContentRequest.contents[4].parts[0].data: required oneof field 'data' must have one initialized field\n (request id: 20240323143144397036627ZRyc73Tm) (request id: )", 'type': '', 'param': '', 'code': 400}}
[2024-03-23 14:31:29.947] C:\Users\Administrator\Desktop\ai\QChatGPT-3.1.0\QChatGPT-3.1.0\pkg\pipeline\controller.py (81) - [ERROR] :
    模型请求失败: 请求参数错误: Error code: 400 - {'error': {'message': "* GenerateContentRequest.contents[4].parts[0].data: required oneof field 'data' must have one initialized field\n (request id: 20240323143144397036627ZRyc73Tm) (request id: )", 'type': '', 'param': '', 'code': 400}}

**Comment by RockChinQ** [comment]
怎么复现？用的什么模型？发什么消息
