### ISSUE TITLE
[Bug]: 群聊内命令无法使用

### ISSUE THREAD

**Issue by bright141** [RockChinQ/QChatGPT#739]
### 部署方式

Docker部署

### 消息平台适配器

yiri-mirai（Mirai）

### 系统环境

debian 11 arm64

### Python环境

使用的容器环境

### QChatGPT版本

3.1.0.1

### 异常情况

群聊在管理员会话 admin-sessions中且不在访问控制 access-control排除名单。发送命令机器人和后台均无响应

**Comment by RockChinQ** [comment]
发一下命令截图和相关配置信息

**Comment by bright141** [comment]
群聊发送命令后qchatgpt后台没有反应，所以我就没截
![7dd83f19f10fffdc5a9bd275cc4d5f81](https://github.com/RockChinQ/QChatGPT/assets/123460862/5eeeb98e-dafa-432c-9e21-1e167427f0e1)
![a27f1e39f5c41a293f6e2cb568c6369e](https://github.com/RockChinQ/QChatGPT/assets/123460862/c61855cc-9e79-4845-b2e4-dba1e774d307)
![7fb972238d99d88fb9e946d97983eef9](https://github.com/RockChinQ/QChatGPT/assets/123460862/34e46625-c5a7-4167-b1d7-530f02c47dcd)
![ef546f702b2c8a5c4afa14b361196487](https://github.com/RockChinQ/QChatGPT/assets/123460862/f259310f-2c63-4291-9cdd-20aedb017a0c)
![d2f94b87641fcee3940149dfe2c1ac39](https://github.com/RockChinQ/QChatGPT/assets/123460862/4e961004-e0ce-4c57-a73a-ebdf14efdb6a)

**Comment by RockChinQ** [comment]
你这没响应啊，你要at机器人啊

**Comment by bright141** [comment]
az，还以为at只是触发ai聊天设置
