### ISSUE TITLE
插件返回错误

### ISSUE THREAD

**Issue by SkyFutu** [RockChinQ/QChatGPT#741]
### 部署方式

手动部署

### 消息平台适配器

yiri-mirai（Mirai）

### 系统环境

windows  server 2019 江苏

### Python环境

py 3.10.9

### QChatGPT版本

v3.1

### 异常情况

两个问题，一个是群聊合并转发名字不是2.x版本的bot，而是叫“qq用户”
第二个是插件返回图片中，v2.6版本正常，v3.1版本返回“[图片]”代码如下
        while True:
            try:
                # 转base64返回
                resp = requests.get(url="",
                img_base64 = base64.b64encode(resp.content).decode()

                image_msg = mirai.Image(base64=img_base64)
                return [image_msg]
 前两个issue我好像写错了closed看这个吧
![%7BAE77EE24-79C2-49eb-8DD2-FA301A966BF0%7D](https://github.com/RockChinQ/QChatGPT/assets/119418823/ed19e151-17e1-4d02-9760-b1a76b84fe3c)
![%7B004454E4-9838-4778-98FB-EC084300F0CE%7D](https://github.com/RockChinQ/QChatGPT/assets/119418823/61b1b180-1ad5-4278-9df9-5e8e7568bd2b)

### 日志信息

![%7B2E830823-2275-487c-B665-4DCAEA13C0D1%7D](https://github.com/RockChinQ/QChatGPT/assets/119418823/f391df00-8ded-477a-ac97-0a2ccd14e0f4)

**Comment by RockChinQ** [comment]
转发消息就是专门改成 QQ用户 的，降低风控概率。

复现这个问题的插件代码发一下我看看

**Comment by SkyFutu** [comment]
`#基本上是复制文档的模板，通过request来请求图床，然后转成base64后就return了
from pkg.plugin.models import *
from pkg.plugin.host import EventContext, PluginHost
import requests
import base64
import mirai


# 注册插件
@register(name="", description="", version="1", author="SkyFuture")
class PixivImagePlugin(Plugin):

    def __init__(self, plugin_host: PluginHost):
        pass

    @on(PersonNormalMessageReceived)
    def person_normal_message_received(self, event: EventContext, **kwargs):
        msg = kwargs['text_message']
        if msg == "ba":
            reply = self.api_img()
            event.add_return("reply", reply)
            event.prevent_default()

    @on(GroupNormalMessageReceived)
    def group_normal_message_received(self, event: EventContext, **kwargs):
        msg = kwargs['text_message']
        if msg == "ba":
            reply = self.api_img()
            event.add_return("reply", reply)
            event.prevent_default()

    def api_img(self):

        while True:
            try:
                resp = requests.get(url="图床地址")
                img_base64 = base64.b64encode(resp.content).decode()
                image_msg = mirai.Image(base64=img_base64)
                return [image_msg]

`

**Comment by SkyFutu** [comment]
#基本上是复制文档的模板，通过request来请求图床，然后转成base64后就return了
from pkg.plugin.models import *
from pkg.plugin.host import EventContext, PluginHost
import requests
import base64
import mirai


# 注册插件
@register(name="", description="", version="1", author="SkyFuture")
class PixivImagePlugin(Plugin):

    def __init__(self, plugin_host: PluginHost):
        pass

    @on(PersonNormalMessageReceived)
    def person_normal_message_received(self, event: EventContext, **kwargs):
        msg = kwargs['text_message']
        if msg == "ba":
            reply = self.api_img()
            event.add_return("reply", reply)
            event.prevent_default()

    @on(GroupNormalMessageReceived)
    def group_normal_message_received(self, event: EventContext, **kwargs):
        msg = kwargs['text_message']
        if msg == "ba":
            reply = self.api_img()
            event.add_return("reply", reply)
            event.prevent_default()

    def api_img(self):

        while True:
            try:
                resp = requests.get(url="图床地址")
                img_base64 = base64.b64encode(resp.content).decode()
                image_msg = mirai.Image(base64=img_base64)
                return [image_msg]

**Comment by RockChinQ** [comment]
修复了，将在 v3.1.0.2 包含。

测试代码：

```python
from pkg.plugin.context import register, handler, llm_func, BasePlugin, APIHost, EventContext
from pkg.plugin.events import *  # 导入事件类

import mirai


"""
在收到私聊或群聊消息"hello"时，回复"hello, <发送者id>!"或"hello, everyone!"
"""


# 注册插件
@register(name="Hello", description="hello world", version="0.1", author="RockChinQ")
class HelloPlugin(BasePlugin):

    # 插件加载时触发
    # plugin_host (pkg.plugin.host.PluginHost) 提供了与主程序交互的一些方法，详细请查看其源码
    def __init__(self, host: APIHost):
        pass
    # 当收到群消息时触发
    @handler(GroupNormalMessageReceived)
    async def group_normal_message_received(self, ctx: EventContext):
        print(ctx.event.text_message)
        msg = ctx.event.text_message
        if msg == "hello":  # 如果消息为hello

            # 输出调试信息
            self.ap.logger.debug("hello, {}".format(ctx.event.sender_id))

            # 回复消息 "hello, everyone!"
            # ctx.add_return("reply", ["hello, everyone!"])
            ctx.add_return("reply", [
                mirai.Image(
                    url="https://user-images.githubusercontent.com/45992437/221341503-34ab9cdd-21d4-40c4-9cc5-b578451a2a0b.jpg"
                )
            ])

            # 阻止该事件默认行为（向接口获取回复）
            ctx.prevent_default()

    # 插件卸载时触发
    def __del__(self):
        pass
```

需要在群里对机器人发送 `hello` 进行测试。

提醒：插件 注册风格在 3.1 版本已修改，请参考：https://qchatgpt.rockchin.top/posts/plugin/develop.html  使用新格式编写。
