### ISSUE TITLE
[Bug]: 传入消息忽略规则失效

### ISSUE THREAD

**Issue by WineTer** [RockChinQ/QChatGPT#743]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

Windows10 中国大陆

### Python环境

python 3.11.5

### QChatGPT版本

v3.1.0.1

### 异常情况

pipeline中设置私聊传入消息忽略规则无法生效，正则和prefix都不行，匹配的消息会在控制台直接响应

### 日志信息

![{006D87FF-C950-4621-88BD-34DFCCD3B90C}](https://github.com/RockChinQ/QChatGPT/assets/28557147/80ef5ea2-1c20-406b-867e-11c4bf36821d)

**Comment by RockChinQ** [comment]
已修复，将在 `v3.1.0.2` 包含，但是提醒你，你的 regexp 规则(`""`)会忽略所有消息。

**Comment by WineTer** [comment]
> 已修复，将在 `v3.1.0.2` 包含，但是提醒你，你的 regexp 规则(`""`)会忽略所有消息。

感谢大佬 辛苦了
