### ISSUE TITLE
[Bug]: 程序使用gemini-pro时报错

### ISSUE THREAD

**Issue by LAN-Cliv** [RockChinQ/QChatGPT#744]
### 部署方式

Docker部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

docker 

### Python环境

Python 3.10.13

### QChatGPT版本

v3.1.0.1

### 异常情况

# 程序使用OneAPI接入的gemini-pro报错
### 环境2：OneAPI环境 美西VPS，docker-compose部署，接入gemini-pro

测试curl https://generativelanguage.googleapis.com/v1beta/models/gemini-pro?key=$API_KEY  回报正常

{
  "name": "models/gemini-pro",
  "version": "001",
  "displayName": "Gemini 1.0 Pro",
  "description": "The best model for scaling across a wide range of tasks",
  "inputTokenLimit": 30720,
  "outputTokenLimit": 2048,
  "supportedGenerationMethods": [
    "generateContent",
    "countTokens"
  ],
  "temperature": 0.9,
  "topP": 1,
  "topK": 1
}

确定IP未被谷歌拉黑

# 程序报错内容

     qchat  | [2024-03-26 15:11:05.506] /app/pkg/pipeline/process/handlers/chat.py (97) - [ERROR] :
     qchat  |     对话(0)请求失败: 模型请求失败: 请求参数错误: Error code: 400 - {'error': {'message': "* 
     GenerateContentRequest.contents[0].parts[0].data: required oneof field 'data' must have one initialized field
     \n (request id: 202403262311052850525336600142)", 'type': '', 'param': '', 'code': 400}}

### 查询过issues同类型报错，但并不能解决

#645 

## 使用另外的程序调用OneAPI的gemini-pro则正常
感觉似乎并不是OneAPI方面的问题
![测试](https://github.com/RockChinQ/QChatGPT/assets/18377783/d83ea6fe-2698-45c3-9fc3-2b4d75b9ff0f)

### 日志信息

# 报错的完整日志文件
[qcg-2024-03-26-15-10-56.log](https://github.com/RockChinQ/QChatGPT/files/14760634/qcg-2024-03-26-15-10-56.log)

### 启用的插件

无插件

**Comment by RockChinQ** [comment]
可能是默认prompt为空导致的参数错误，可以尝试在 [配置文件provider.json](https://qchatgpt.rockchin.top/posts/config/provider.html) 设置一个不为空的 prompt试试看

**Comment by LAN-Cliv** [comment]
> 可能是默认prompt为空导致的参数错误，可以尝试在 [配置文件provider.json](https://qchatgpt.rockchin.top/posts/config/provider.html) 设置一个不为空的 prompt试试看

正常了，非常感谢🤞
