### ISSUE TITLE
[BUG]请求超时问题

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/QChatGPT#75]

**Comment by RockChinQ** [comment]
目前此问题仍未复现，请有此问题的用户在`config.py`中编辑
```
# 日志级别
logging_level = logging.DEBUG
```
已跟踪此问题，并将请求超时问题发生时段的相关输出回复此issue，可在命令行界面或`qchatgpt.log`文件中查看到日志

**Comment by RockChinQ** [comment]
初步查明是意外请求超时导致的群会话死锁，已在`hot-reload`分支修复，请等待合并

**Comment by huming17** [comment]
代码是master最新, 此问题仍然存在，
[bot]err:请求超时
部署在服务器网络不慢，是否服务器需要部署到国外可以加快速度或购买什么服务？

**Comment by RockChinQ** [comment]
> 代码是master最新, 此问题仍然存在， [bot]err:请求超时 部署在服务器网络不慢，是否服务器需要部署到国外可以加快速度或购买什么服务？

已回复
