### ISSUE TITLE
[Bug]: 安装虚拟环境和依赖后，在虚拟环境中python main.py提示在命令行中运行

### ISSUE THREAD

**Issue by mengluo04** [RockChinQ/QChatGPT#750]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

win10 中国

### Python环境

3.10

### QChatGPT版本

仓库最新

### 异常情况

![image](https://github.com/RockChinQ/QChatGPT/assets/32565940/371bbfa2-ec26-4cc6-9d8f-1cb76189e602)

**Comment by mengluo04** [comment]
虚拟环境会被psutil识别为python.exe

**Comment by RockChinQ** [comment]
最新版删了这个判断了。
