### ISSUE TITLE
报错插件 GenshinVoice 触发事件 NormalMessageResponded 时发生错误: name 'logging' is not defined

### ISSUE THREAD

**Issue by muzewei3** [RockChinQ/QChatGPT#752]
### 部署方式

手动部署

### 消息平台适配器

None

### 系统环境

centos7

### Python环境

3.10.9

### QChatGPT版本

v2.6.0

### 异常情况

插件 GenshinVoice 触发事件 NormalMessageResponded 时发生错误: name 'logging' is not defined
![image](https://github.com/RockChinQ/QChatGPT/assets/148668561/d3370526-a1ec-4f85-92e7-5302dd03eba8)

**Comment by RockChinQ** [comment]
插件的问题去目标插件仓库去提
