### ISSUE TITLE
[Bug]: 没有生成配置文件config.py

### ISSUE THREAD

**Issue by lq204710475** [RockChinQ/QChatGPT#756]
### 部署方式

手动部署

### 消息平台适配器

Nakuru（go-cqhttp）

### 系统环境

ubuntu20.04 日本

### Python环境

3.10.0

### QChatGPT版本

v3.1.04

### 异常情况

运行了main.py后，没有生成config.py

### 日志信息

root@GreenCloud:~/QChatGPT# python3 main.py

  ___   ___ _         _    ___ ___ _____ 
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |  
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|  

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

以下文件不存在，已自动生成，请按需修改配置文件后重启：
- plugins/__init__.py
- plugins/plugins.json
- data/config/command.json
- data/config/pipeline.json
- data/config/platform.json
- data/config/provider.json
- data/config/system.json
- data/scenario/default.json
root@GreenCloud:~/QChatGPT# python3 main.py

  ___   ___ _         _    ___ ___ _____ 
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |  
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|  

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
📖文档地址: https://q.rkcn.top

[2024-04-10 23:18:26.640] /root/QChatGPT/pkg/utils/announce.py (115) - [INFO] :
    [公告] 2024-03-08 22:30:00: QChatGPT 3.x 已发布，若您仍在使用不再维护的 2.x 版本，请尽快迁移至 3.x 版本：https://github.com/RockChinQ/QChatGPT/discussions/690
Traceback (most recent call last):
  File "/root/QChatGPT/main.py", line 72, in <module>
    asyncio.run(main_entry())
  File "/www/server/pyporject_evn/versions/3.10.0/lib/python3.10/asyncio/runners.py", line 44, in run
    return loop.run_until_complete(main)
  File "/www/server/pyporject_evn/versions/3.10.0/lib/python3.10/asyncio/base_events.py", line 641, in run_until_complete
    return future.result()
  File "/root/QChatGPT/main.py", line 49, in main_entry
    await boot.main()
  File "/root/QChatGPT/pkg/core/boot.py", line 38, in main
    app_inst = await make_app()
  File "/root/QChatGPT/pkg/core/boot.py", line 30, in make_app
    await stage_inst.run(ap)
  File "/root/QChatGPT/pkg/core/stages/build_app.py", line 58, in run
    ap.query_pool = pool.QueryPool()
  File "/root/QChatGPT/pkg/pipeline/pool.py", line 26, in __init__
    self.condition = asyncio.Condition(self.pool_lock)
  File "/www/server/pyporject_evn/versions/3.10.0/lib/python3.10/asyncio/locks.py", line 234, in __init__
    raise ValueError("loop argument must agree with lock")
ValueError: loop argument must agree with lock

运行主程序后的文件：
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/85c0694d-9e6d-42c0-93fd-38cbf789d947)

**Comment by RockChinQ** [comment]
config.py 是 2.x 的配置文件，现在的配置文件都是在 data/config/ 目录下，具体配置方法查看 https://qchatgpt.rockchin.top 

还有，python 3.10.0 有bug，没法正常启动，换成 3.10.4 之类的版本

**Comment by lq204710475** [comment]
> config.py 是 2.x 的配置文件，现在的配置文件都是在 data/config/ 目录下，具体配置方法查看 https://qchatgpt.rockchin.top
> 
> 还有，python 3.10.0 有bug，没法正常启动，换成 3.10.4 之类的版本

谢谢谢谢，机器人已经跑起来了，但是文档中的配置和config里面的配置还是不太一样呀，有点不太会填写配置，比如管理员QQ该如何设置

**Comment by RockChinQ** [comment]
哪里不一样？

**Comment by lq204710475** [comment]
> 哪里不一样？

文档中是这个样子
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/09714db9-2221-450e-8279-f81bab306748)

但是config文件夹中是这个样子
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/9e2e01b2-123c-4951-9136-ef8dd2b53c8f)
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/588c2091-e4e5-414e-880c-dca2e4e697a4)
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/b60b9504-5d9b-47d3-9bd7-9d943844dff8)
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/442bd902-94f2-4f2a-b7fa-fc830f18141d)

**Comment by RockChinQ** [comment]
你这里缓存了以前的文档，换个浏览器看看

**Comment by lq204710475** [comment]
> 你这里缓存了以前的文档，换个浏览器看看

谢谢谢谢，解决了，原来如此
