### ISSUE TITLE
[Bug]: 长消息处理策略不生效

### ISSUE THREAD

**Issue by lq204710475** [RockChinQ/QChatGPT#760]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

ubuntu20.04 日本

### Python环境

3.11

### QChatGPT版本

v3.1.04

### 异常情况

配置如下：
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/73e10b1e-1340-4530-b474-a744827337fe)
长消息处理没起作用：
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/574fa331-abe0-4e15-9c44-a6eef6ccf3ba)
日志无报错

好像是在打开了群消息@之后，就这样了，关掉了群消息@后，还是这样，无论是群消息还是个人消息回复，都没有处理长消息

### 日志信息

![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/2c5a00eb-51af-4d72-b088-c8b6f7898924)

### 启用的插件

无

**Comment by lq204710475** [comment]
配置发错了，填的是forward
![image](https://github.com/RockChinQ/QChatGPT/assets/133567918/0de11bfd-bb5a-4795-a1e6-d5143566f58e)

**Comment by RockChinQ** [comment]
aiocqhttp是暂时不支持转发消息的
