### ISSUE TITLE
[Bug]: 卡在"未运行平台适配器，请根据文档配置并启用平台适配器。"

### ISSUE THREAD

**Issue by bobandbrony** [RockChinQ/QChatGPT#774]
### 部署方式

手动部署

### 消息平台适配器

Nakuru（go-cqhttp）

### 系统环境

Windows10 ltsc 中国四川

### Python环境

python 3.10.9

### QChatGPT版本

v3.2.0

### 异常情况

之前2.6.0的版本可正常用，升级到最新版就报错

### 日志信息

  ___   ___ _         _    ___ ___ _____
 / _ \ / __| |_  __ _| |_ / __| _ \_   _|
| (_) | (__| ' \/ _` |  _| (_ |  _/ | |
 \__\_\\___|_||_\__,_|\__|\___|_|   |_|

⭐️开源地址: https://github.com/RockChinQ/QChatGPT
�文档地址: https://q.rkcn.top

[2024-05-17 00:04:32.892] D:\chatbot\317---\QChatGPT-3.2.0\pkg\platform\manager.py (147) - [WARNING] :
    未运行平台适配器，请根据文档配置并启用平台适配器。

**Comment by RockChinQ** [comment]
看文档进行配置 https://q.rkcn.top

**Comment by bobandbrony** [comment]
> 看文档进行配置 https://q.rkcn.top

未生成配置文件，需要自己新建一个吗？

**Comment by RockChinQ** [comment]
配置文件都在 data/config 目录下，如果你看的文档中说你配置文件是 config.py 。换个浏览器打开文档。

**Comment by bobandbrony** [comment]
> 配置文件都在 data/config 目录下，如果你看的文档中说你配置文件是 config.py 。换个浏览器打开文档。

原来文档更新了，谢谢
