### ISSUE TITLE
[Bug]: 更新到最新版本后报错'ContentElement' object has no attribute 'get'

### ISSUE THREAD

**Issue by Tigrex-Dai** [RockChinQ/QChatGPT#775]
### 部署方式

一键安装包部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

Windows 11 法国

### Python环境

Python 3.11

### QChatGPT版本

v3.2.0

### 异常情况

今天更新了新版本后私聊突然报错'ContentElement' object has no attribute 'get'，请求失败

### 日志信息

![image](https://github.com/RockChinQ/QChatGPT/assets/26639371/5a9b8515-6216-4052-81f6-64b474a61623)

**Comment by Tigrex-Dai** [comment]
我用的模型是Claude3 haiku

**Comment by RockChinQ** [comment]
v3.2.0.1 修复了
