### ISSUE TITLE
[Bug]: 联网插件报错

### ISSUE THREAD

**Issue by satan170** [RockChinQ/QChatGPT#777]
### 部署方式

手动部署

### 消息平台适配器

yiri-mirai（Mirai）

### 系统环境

Windows10

### Python环境

3.10.9

### QChatGPT版本

3.2.0.1

### 异常情况

无法识别链接，显示请求错误

### 日志信息

[2024-05-17 14:20:16.482] E:\QQ群gpt机器人\QChatGPT 3.x+原神星铁语音整合包\qqbot(mirai)\qqbot\QChatGPT\pkg\pipeline\process\handlers\chat.py (97) - [ERROR] :
    对话(0)请求失败: 模型请求失败: 请求参数错误: Error code: 400 - {'error': {'message': "Missing parameter 'tool_call_id': messages with role 'tool' must have a 'tool_call_id'. (request id: 202405171420156605031359gDqNaC6) (request id: 2024051706201581129827680406279) (request id: 2024051714201579699440043906896)", 'type': 'invalid_request_error', 'param': 'messages.[3].tool_call_id', 'code': None}}
[2024-05-17 14:20:17.221] E:\QQ群gpt机器人\QChatGPT 3.x+原神星铁语音整合包\qqbot(mirai)\qqbot\QChatGPT\pkg\pipeline\controller.py (81) - [ERROR] :
    模型请求失败: 请求参数错误: Error code: 400 - {'error': {'message': "Missing parameter 'tool_call_id': messages with role 'tool' must have a 'tool_call_id'. (request id: 202405171420156605031359gDqNaC6) (request id: 2024051706201581129827680406279) (request id: 2024051714201579699440043906896)", 'type': 'invalid_request_error', 'param': 'messages.[3].tool_call_id', 'code': None}}

### 启用的插件

WebwlkrPlugin

**Comment by RockChinQ** [comment]
你问了什么内容也发一下

**Comment by satan170** [comment]
> 
![QDCH(3 @E1YP{L3X _MQYND](https://github.com/RockChinQ/QChatGPT/assets/63832816/0a258413-ac96-42bc-8cd6-42e84dca5cfc)
你问了什么内容也发一下

无法识别链接，直接提示请求失败

**Comment by satan170** [comment]
> 你问了什么内容也发一下

好的好的，抱歉理解错了，稍等一下

**Comment by satan170** [comment]
> 你问了什么内容也发一下

![KA~DZ_B ~N4R0G{98G0%K}K](https://github.com/RockChinQ/QChatGPT/assets/63832816/da17c1e9-71e3-4a85-9490-8e801cd34d06)
问了这个

**Comment by RockChinQ** [comment]
<img width="1240" alt="image" src="https://github.com/RockChinQ/QChatGPT/assets/45992437/763a4484-92dd-4597-8ade-dc26d3e40cf0">

群里已经确认是你API站问题了
