### ISSUE TITLE
QQ版本太低，登不进去

### ISSUE THREAD

**Issue by CXY666CXY** [RockChinQ/QChatGPT#78]
**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
    例如： Centos x64
- Python环境（仅手动部署填写）：
    例如： Python 3.10.9

**描述漏洞**  
什么时候发生的，mirai还是主程序，越详细越好

**完整报错信息**  
完整的报错信息

**Comment by RockChinQ** [comment]
#38
