### ISSUE TITLE
[Bug]: 插件安装失败: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by hhhhhge** [RockChinQ/QChatGPT#790]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

Win10 上海

### Python环境

Python 3.11

### QChatGPT版本

v3.2.1

### 异常情况

[bot] 插件安装失败: 'NoneType' object is not subscriptable

### 日志信息

[2024-05-25 18:32:01.782] D:\QChatGPT\pkg\pipeline\process\handlers\command.py (112) - [INFO] :
    命令返回: 正在安装插件...
Traceback (most recent call last):
  File "D:\QChatGPT\pkg\command\operators\plugin.py", line 59, in execute
    await self.ap.plugin_mgr.install_plugin(repo)
  File "D:\QChatGPT\pkg\plugin\manager.py", line 69, in install_plugin
    await self.installer.install_plugin(plugin_source)
  File "D:\QChatGPT\pkg\plugin\installers\github.py", line 100, in install_plugin
    repo_label = await self.download_plugin_source_code(plugin_source, "plugins/")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\QChatGPT\pkg\plugin\installers\github.py", line 39, in download_plugin_source_code
    target_path += repo[1]
                   ~~~~^^^
TypeError: 'NoneType' object is not subscriptable
[2024-05-25 18:32:02.313] D:\QChatGPT\pkg\pipeline\process\handlers\command.py (85) - [INFO] :
    命令(9)报错: 插件安装失败: 'NoneType' o...

### 启用的插件

_No response_

**Comment by hhhhhge** [comment]
怎么正则匹配还不匹配gitee或者其他的呢，还有我的git下载的镜像地址

**Comment by RockChinQ** [comment]
这个是用GitHub api下载的，不是clone，所以不支持gitee和其他镜像。建议你到plugins/目录下直接自己clone插件代码。别忘了安装插件的依赖

**Comment by hhhhhge** [comment]
from git import Repo

# 目标克隆目录
clone_dir = '/path/to/clone/directory'
# Git 仓库 URL
repo_url = 'https://github.com/user/repo.git'

# 克隆仓库
Repo.clone_from(repo_url, clone_dir)

print(f"Repository cloned to {clone_dir}")

**Comment by hhhhhge** [comment]
不知道gpt给的这个好不好用

**Comment by hhhhhge** [comment]
没毛病

**Comment by hhhhhge** [comment]
可以

**Comment by hhhhhge** [comment]
和普通git没区别，大佬可以改改了

**Comment by hhhhhge** [comment]
pip install gitpython

**Comment by hhhhhge** [comment]
import os
from git import Repo, GitCommandError

def clone_repository(repo_url, clone_dir):
    if os.path.exists(clone_dir):
        print(f"Error: Directory '{clone_dir}' already exists.")
        return

    try:
        print(f"Cloning repository from {repo_url} to {clone_dir}...")
        Repo.clone_from(repo_url, clone_dir)
        print("Repository successfully cloned.")
    except GitCommandError as e:
        print(f"Error: Failed to clone repository. {e}")

# 目标克隆目录
clone_dir = 'temp/temp'
# Git 仓库 URL
repo_url = 'https://gitee.com/RockChin/revLibs'

# 克隆仓库
clone_repository(repo_url, clone_dir)

**Comment by RockChinQ** [comment]
代码很简单实现，但如何确保所有用户的主机上都有安装Git呢？

如果有需求建议请提到新issue。
