### ISSUE TITLE
[Feature]: 读取群聊历史记录

### ISSUE THREAD

**Issue by HUSTerAIA** [RockChinQ/QChatGPT#800]
### 这是一个？

现有功能优化

### 详细描述

开启新一轮对话时，附带群聊当中最近的指定数目条历史信息，而不仅仅是@机器人进行的历史对话，该功能有助于使用random随机模式时使得机器人对话更符合群聊的整体语境。

**Comment by RockChinQ** [comment]
这个做个插件实现就好了，主项目就不做了。
