### ISSUE TITLE
[Bug]: 插件修改用户发言无效果

### ISSUE THREAD

**Issue by by123456by** [RockChinQ/QChatGPT#803]
### 部署方式

Docker部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

CentOS 7 美国

### Python环境

docker部署

### QChatGPT版本

3.2.1

### 异常情况

![image](https://github.com/RockChinQ/QChatGPT/assets/15666692/d14ca16f-883b-4086-84e7-846cd95bedcd)
修改代码如上，无效果，直接打印可以确定插件正常执行

### 启用的插件

仅自己写的插件

**Comment by RockChinQ** [comment]
已修复，等待 3.2.4 发布。
