### ISSUE TITLE
[Bug]: !update升级至最新版用不了

### ISSUE THREAD

**Issue by bobandbrony** [RockChinQ/QChatGPT#805]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

Windows10 ltsc 中国四川

### Python环境

python 3.10.9

### QChatGPT版本

v3.2.0.1

### 异常情况

我从v3.2.0.1升级到了3.2.2，再次使用遇到报错'str' object has no attribute 'choices'

### 日志信息

    处理 person_30431*** 的请求(6): 你好
[2024-06-03 00:04:33.073] D:\chatbot\4494***\QChatGPT-3.2.0.1\pkg\pipeline\process\handlers\chat.py (92) - [ERROR] :
    对话(6)请求失败: 'str' object has no attribute 'choices'
[2024-06-03 00:04:33.596] D:\chatbot\449***\QChatGPT-3.2.0.1\pkg\pipeline\controller.py (81) - [ERROR] :
    'str' object has no attribute 'choices'

### 启用的插件

无

**Comment by bobandbrony** [comment]
好吧，是我中转地址填错了

**Comment by S-R-Afraid** [comment]
可以详细说明一下吗？我也遇到这个问题了，具体是改哪个文件的配置呢？谢谢！

**Comment by RockChinQ** [comment]
> 可以详细说明一下吗？我也遇到这个问题了，具体是改哪个文件的配置呢？谢谢！

可以看一下文档的 常见问题 页

**Comment by S-R-Afraid** [comment]
好的！感谢您的回答！
