### ISSUE TITLE
[Plugin]: 请求登记新插件

### ISSUE THREAD

**Issue by logos000** [RockChinQ/QChatGPT#807]
### 插件名称

gpt-vits

### 插件代码库地址

https://github.com/logos000/vits.git

### 插件简介

通过本地gpts-vits 的api接口提供本地语音推理

**Comment by RockChinQ** [comment]
感谢贡献！已加到星标集：https://github.com/stars/RockChinQ/lists/qchatgpt-%E6%8F%92%E4%BB%B6
