### ISSUE TITLE
[Bug]: 无任何插件，提示role none is not an allowed value

### ISSUE THREAD

**Issue by vansmart521** [RockChinQ/QChatGPT#811]
### 部署方式

手动部署

### 消息平台适配器

None

### 系统环境

Winserver

### Python环境

python 3.12

### QChatGPT版本

v3.2.2

### 异常情况

查看api后发现，机器人收到的我的消息并且发送给了openai，openai返回的信息似乎不能正确被机器人接受。将api部署至别的应用例如chatgpt-web发现是可以正常使用的，但是应用在机器人上却无法使用。

### 日志信息

![image](https://github.com/RockChinQ/QChatGPT/assets/111718628/87fabd2a-a8ea-45f7-9793-2d1bc686fa85)

### 启用的插件

无

**Comment by RockChinQ** [comment]
最新版再试一下。
