### ISSUE TITLE
[Feature]: 随机匹配可不可以将历史消息一并发给gpt？

### ISSUE THREAD

**Issue by pplokijuhyg** [RockChinQ/QChatGPT#812]
### 这是一个？

新功能

### 详细描述

![59ed73f856f86b7615a8306f9e67cc4d](https://github.com/RockChinQ/QChatGPT/assets/31347252/06227b0f-bf34-4ba6-a9c1-955f8fdc38ea)

比如这里我设置为0.1，他现在只回答匹配到的那条，有没有办法让他把上次回复到这次回复之间的所有对话都一起塞进去？

**Comment by RockChinQ** [comment]
这个做个插件实现就好了，主项目就不做了。
