### ISSUE TITLE
[Plugin]: 请求登记新插件

### ISSUE THREAD

**Issue by ElvisChenML** [RockChinQ/QChatGPT#814]
### 插件名称

Waifu

### 插件代码库地址

https://github.com/ElvisChenML/Waifu

### 插件简介

用于创建真实感聊天机器人，探索真实的聊天体验。

**Comment by RockChinQ** [comment]
感谢贡献！已加到星标集：https://github.com/stars/RockChinQ/lists/qchatgpt-%E6%8F%92%E4%BB%B6
