### ISSUE TITLE
[Bug]: 删掉遥测服务器导致启动失败

### ISSUE THREAD

**Issue by bobandbrony** [RockChinQ/QChatGPT#816]
### 部署方式

手动部署

### 消息平台适配器

None

### 系统环境

Windows10 ltsc 中国四川

### Python环境

python 3.10.9

### QChatGPT版本

v3.2.2

### 异常情况

我把"qcg-center-url": "https://api.qchatgpt.rockchin.top/api/v2"改成"qcg-center-url": null。启动报错
![f31c02d1612ae6c356a51de89373971d](https://github.com/RockChinQ/QChatGPT/assets/129247570/2a9204f3-1c55-4982-9723-e3f032ccf88a)

**Comment by RockChinQ** [comment]
所以结果就是不能删，你要是想避免发送遥测数据，把`"report-usage": true,`就可以了
