### ISSUE TITLE
[Bug]: GPT-4o的视觉功能在私聊中正常工作，但在群聊中无法处理图片，调试后发现群聊中接收到的是字符串"[图片]"

### ISSUE THREAD

**Issue by Huoyuuu** [RockChinQ/QChatGPT#820]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

Ubuntu22.04

### Python环境

Python 3.10.12

### QChatGPT版本

v3.2.2

### 问题描述：

各位，

我在使用GPT-4o的视觉功能时遇到了一个问题：它在私聊中工作正常，但在群聊中无法处理图片。以下是具体情况：

**私聊：**
- 当我在私聊中发送图片时，GPT-4o的视觉功能可以正确处理并给出反馈。
- 示例： ![私聊图片](https://github.com/RockChinQ/QChatGPT/assets/86390123/aa5dfb49-15df-4825-8d37-aaac2ce8f057)

**群聊：**
- 当我在群聊中发送图片时，GPT-4o的视觉功能只接收到一个字符串“[图片]”，而不是实际的图片。
- 示例： ![群聊图片](https://github.com/RockChinQ/QChatGPT/assets/86390123/db88819b-16ce-4068-bbf7-cd432843d52e)

**观察到的现象：**
- 问题仅出现在群聊中。
- 我已确保按照多模态文档中提到的打开了`enable-vision`设置。
- `pipeline.json`中的response-rules设置也按照前缀或@信号配置了机器人回复消息，但问题仍未解决。
- 在`pkg/provider/modelmgr/apis/chatcmpl.py`文件的 `_req` 函数体内部进行调试时，发现群聊中的图片消息在API调用前已经变成了字符串“[图片]”，这表明问题与网络或API地址无关。

**调试信息：**
- ![调试信息](https://github.com/RockChinQ/QChatGPT/assets/86390123/f89febab-46c6-412c-bcb6-98caee53a0fb)

**总结：**
- 问题似乎与私聊和群聊消息处理方式的差异有关。尽管我已按照文档进行配置，但仍无法解决此问题。我使用的是Lagrange消息平台，不知道群聊私聊中图片的不同处理方式是否和它有关。

请问可以提供一些指导来解决或进一步排查这个问题吗？

谢谢大家的帮助。

### 日志信息

私聊消息：
```
[2024-06-21 00:05:25.687] /root/Git/QChatGPT/pkg/pipeline/process/process.py (42) - [INFO] :
    处理 person_xxxxxxxxx 的请求(2): [图片]
Msg: [{'role': 'system', 'content': 'You are a helpful AI assistant.'}, {'role': 'user', 'content': [{'type': 'image_url', 'image_url': {'url': 'http://gchat.qpic.cn/offpic_new/xxxxxxxxx//xxxxxxxxx-xxxxxxxxx-CE5CCEB705BA0427AB278B921D6C8BE3/0?term=255&is_origin=0'}}]}]
Request args: {
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful AI assistant."
    },
    {
      "role": "user",
      "content": [
        {
          "type": "image_url",
          "image_url": {
            "url": "data:image/jpeg;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAcBAMAAACjeJNyAAAAAXNSR0IArs4c6QAAACdQTFRFAAAA5eXlo1wAADKBxeXlo+XlAABcgaPF5eXFADJc5aNcXKPlgVwyI+tn1gAAACpJREFUCNdjYCAAUgUFhZBpBgYTOtOpUhCaW+IAmGZ2FBRUADGmQ2l8AAAt8gfI56R0iQAAAABJRU5ErkJggg=="
          }
        }
      ]
    }
  ]
}
Response: ChatCompletion(id='chatcmpl-9cEZtPve7i5iwpswgavnraQCAxnXQ', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='The image shows an uppercase letter "L" from the Armenian alphabet. The Armenian script is used to write the Armenian language, and the character displayed is "Լ," which corresponds to the sound [l].', role='assistant', function_call=None, tool_calls=None))], created=1718899529, model='gpt-4o-2024-05-13', object='chat.completion', system_fingerprint='fp_9cb5d38cf7', usage=CompletionUsage(completion_tokens=41, prompt_tokens=273, total_tokens=314))
```

群聊消息：
```
[2024-06-21 00:00:35.471] /root/Git/QChatGPT/pkg/pipeline/process/process.py (42) - [INFO] :
分析图片内容。_xxxxxxxxx 的请求(3): [图片]
Request args: {
  "model": "gpt-4o",
  "messages": [
    {
      "role": "system",
      "content": "You are a helpful AI assistant."
    },
    {
      "role": "user",
      "content": [
        {
          "type": "text",
          "text": "[\u56fe\u7247]\r\u5206\u6790\u56fe\u7247\u5185\u5bb9\u3002"
        }
      ]
    }
  ]
}
Response: ChatCompletion(id='chatcmpl-9cEVBOYkRLtIAQiviApk2hBM6DwYU', choices=[Choice(finish_reason='stop', index=0, logprobs=None, message=ChatCompletionMessage(content='很抱歉，我目前无法查看图片。但你可以描述图片的内容，我会尽力帮你分析和解答。请告诉我图片中有哪些元素或细节，这样我就可以提供更准确的帮助。', role='assistant', function_call=None, tool_calls=None))], created=1718899237, model='gpt-4o-2024-05-13', object='chat.completion', system_fingerprint='fp_f4e629d0a5', usage=CompletionUsage(completion_tokens=47, prompt_tokens=26, total_tokens=73))
```

### 启用的插件

无

**Comment by Huoyuuu** [comment]
尝试了将qchatgpt库删掉，重新下载，重新配置，重新启动
将Lagrange消息平台删掉，下载build的最新版本，重新开跑
尝试从linux平台切换到win平台

私聊识图功能自始至终都能跑通
群聊识图功能自始至终传入的都是**字符串"图片"**

![3 L3HPQ}4TC`Y2 EFN0M`31](https://github.com/RockChinQ/QChatGPT/assets/86390123/4374af53-695e-4ebf-a5a1-2063021a7fd4)

**Comment by Huoyuuu** [comment]
### 问题描述与分析

群聊中的图片信息无法被正确处理。经过调查，确定这是由于项目代码与本地环境不兼容所致。虽然其他用户反馈系统可以正常运行，但在我的环境中问题依然存在，即使在不同操作系统和平台上也能复现。

### 问题定位

通过设置环境变量 `DEBUG=true` 进行调试，发现问题出现在 `Stage PreProcessor` 阶段。具体表现为 `user_message` 变量中的消息链错误地处理了图片部分，把图片链接处理成了字符串"图片"，而 `GroupMessage` 中的消息链却是正确的。
![image](https://github.com/RockChinQ/QChatGPT/assets/86390123/02e4205b-0ef1-460e-be3e-2f173c519987)

### 解决方案

考虑到问题的特殊性，决定对代码进行小幅修改以解决这一问题。主要修改集中在 `pkg/pipeline/preproc/preproc.py` 文件中，目的是确保 `user_message` 包含正确的消息链。

修改内容如下：

1. 移除消息中多余的 "Source" 时间信息。
2. 去除可能存在的前缀匹配文本（如 "/ai"）。
3. 保留图片等其他重要信息。

### 具体实现

在 preproc.py 文件的如图位置添加以下代码：
```python
def process_message_chain(message_chain):
            # 首先移除 Source
            if message_chain and isinstance(message_chain[0], mirai.models.message.Source):
                message_chain = message_chain[1:]

            # 检查并移除 "/ai" 前缀
            if message_chain and isinstance(message_chain[0], mirai.Plain):
                text = message_chain[0].text
                if text.startswith("/ai"):
                    message_chain[0].text = text[3:].lstrip()  # 移除 "/ai" 并清理左侧空白
                    if not message_chain[0].text:
                        message_chain = message_chain[1:]  # 如果文本为空，则完全移除这个 Plain 元素

            return message_chain
        
        query.message_chain = query.message_event.message_chain
        query.message_chain = process_message_chain(query.message_chain)
```
![image](https://github.com/RockChinQ/QChatGPT/assets/86390123/2d887331-bd71-47f7-a327-b0e807336ddf)

### 修改效果

实施上述修改后，系统能够正确处理私聊中的图片信息，功能恢复正常。
![image](https://github.com/RockChinQ/QChatGPT/assets/86390123/da4eec6a-514c-419f-be76-f99b0332e9b3)

### 注意事项

1. 此解决方案属于临时性修复，可能会因项目后续更新而失效。
2. 使用此方法可能会引入新的兼容性问题，特别是在项目结构变化后。
3. 如果采用此方案后遇到新问题，请在向项目提交 issue 时确保已移除这些修改。
4. 由于其他用户反馈系统可正常运行，此问题可能源于个人环境配置，因此暂不考虑向项目提交 PR。

### 建议

1. 持续关注项目更新，以获取官方的修复或改进。
2. 考虑检查本地环境配置，确保与项目要求一致。
3. 如果问题持续存在，可以在项目的 issue 区详细描述情况，以获得更多社区支持。

**Comment by RockChinQ** [comment]
已在 https://github.com/RockChinQ/QChatGPT/commit/4ffa773facd578ed9b75630b9014415c0b1d1c84 修复。是群内响应(resprule)匹配前缀响应时，错误地把message_chain的纯文本用于结果输出导致的。
