### ISSUE TITLE
[Feature]: 希望添加类似于Spit_chatBot这个项目的 消息分段 随机截断 的功能

### ISSUE THREAD

**Issue by SpiritHerb** [RockChinQ/QChatGPT#831]
### 这是一个？

新功能

### 详细描述

去年在小破站看到一个很有意思的仿人类聊天的QQ机器人视频，让我对这个插件的神奇工作方式暂不绝口，能记录聊天记录，然后像普通群员一样截段输出，无奈go-cqhttp不好使哦，自己又不会折腾，这个功能自己到现在也没体验上
[**我用ChatGPT创造了一个数字生命，在QQ群里伪装人类**](https://www.bilibili.com/video/BV1gm4y1C7oY/?spm_id_from=333.999.0.0)
[**项目地址**](https://github.com/LUMOXu/Spit_chatBot)
我希望贵项目也能拥有类似于spit这样类似的功能

**Comment by HUSTerAIA** [comment]
附议，理想形态

**Comment by ElvisChenML** [comment]
看到你们的issue，来试试插件[Waifu](https://github.com/ElvisChenML/Waifu)吧，我新增了Spit_chatBot类似的功能

**Comment by RockChinQ** [comment]
这个功能会使程序行为不可控，暂时不考虑在主线实现，可以使用 @ElvisChenML 实现的插件。
