### ISSUE TITLE
[Bug]: 群聊发送的指令插件不响应

### ISSUE THREAD

**Issue by SkyFutu** [RockChinQ/QChatGPT#835]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

windows  server 2019 江苏

### Python环境

py 3.10.9

### QChatGPT版本

v3.2.3

### 异常情况

刚从2.x升级到3.x，然后按照文档部署完后把文档里的开发模板（hello插件）放到plugin然后启动机器人，但是私聊发送指令hello就能响应，群聊发送就不会响应，后台是可以看到显示处理group的消息：hello的

### 启用的插件

bot] 所有插件(1):

#1 Hello 
hello world
v0.1
作者: RockChinQ

**Comment by RockChinQ** [comment]
发发你的插件代码

**Comment by SkyFutu** [comment]
> 发发你的插件代码

from pkg.plugin.context import register, handler, llm_func, BasePlugin, APIHost, EventContext
from pkg.plugin.events import *  # 导入事件类


"""
在收到私聊或群聊消息"hello"时，回复"hello, <发送者id>!"或"hello, everyone!"
"""


# 注册插件
@register(name="Hello", description="hello world", version="0.1", author="RockChinQ")
class HelloPlugin(BasePlugin):

    # 插件加载时触发
    def __init__(self, host: APIHost):
        pass

    # 异步初始化
    async def initialize(self):
        pass

    # 当收到个人消息时触发
    @handler(PersonNormalMessageReceived)
    async def person_normal_message_received(self, ctx: EventContext):
        msg = ctx.event.text_message  # 这里的 event 即为 PersonNormalMessageReceived 的对象
        if msg == "hello":  # 如果消息为hello

            # 输出调试信息
            self.ap.logger.debug("hello, {}".format(ctx.event.sender_id))

            # 回复消息 "hello, <发送者id>!"
            ctx.add_return("reply", ["hello, {}!".format(ctx.event.sender_id)])

            # 阻止该事件默认行为（向接口获取回复）
            ctx.prevent_default()

    # 当收到群消息时触发
    @handler(GroupNormalMessageReceived)
    async def group_normal_message_received(self, ctx: EventContext):
        msg = ctx.event.text_message  # 这里的 event 即为 GroupNormalMessageReceived 的对象
        if msg == "hello":  # 如果消息为hello

            # 输出调试信息
            self.ap.logger.debug("hello, {}".format(ctx.event.sender_id))

            # 回复消息 "hello, everyone!"
            ctx.add_return("reply", ["hello, everyone!"])

            # 阻止该事件默认行为（向接口获取回复）
            ctx.prevent_default()

    # 插件卸载时触发
    def __del__(self):
        pass

我用的就是文档里的示例，然后这个bug好像只在3.2.3出现，3.2.2就好了

**Comment by RockChinQ** [comment]
<img width="527" alt="image" src="https://github.com/RockChinQ/QChatGPT/assets/45992437/9733b6da-b2fe-49bd-8504-583592983add">

首先是得符合群内响应规则，才会进入这个 GroupNormalMessageReceived 实践。其次是，at 机器人的话，后面会自动添加一个空格，你要么改成 `msg == " hello"` 要么对 `msg = msg.strip()` 再去判断。

**Comment by SkyFutu** [comment]
> <img alt="image" width="527" src="https://private-user-images.githubusercontent.com/45992437/345997463-9733b6da-b2fe-49bd-8504-583592983add.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTgyMDAsIm5iZiI6MTcyMDE1NzkwMCwicGF0aCI6Ii80NTk5MjQzNy8zNDU5OTc0NjMtOTczM2I2ZGEtYjJmZS00OWJkLTg1MDQtNTgzNTkyOTgzYWRkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1MzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhZWJjOGJmM2ZmMjZlNGVhNmJiOGY3OTdmNzAxYzIyZjFmYjE4NjhhNDM3ZjJkOTVhODJkNTNiODk5ZWRiNDQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.PIqF_54LbPsZcwKKk-4kiFCVHI6S2eC60KOn9mamG5Y">
> 首先是得符合群内响应规则，才会进入这个 GroupNormalMessageReceived 事件。其次是，at 机器人的话，后面会自动添加一个空格，你要么改成 `msg == " hello"` 要么对 `msg = msg.strip()` 再去判断。
> 
> 如果用的是前缀规则，这样是可以被响应的（前缀规则识别`ai`）： <img alt="image" width="504" src="https://private-user-images.githubusercontent.com/45992437/345997921-ba519102-8e4e-4fa2-ad47-2205cb3ac39c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjAxNTgyMDAsIm5iZiI6MTcyMDE1NzkwMCwicGF0aCI6Ii80NTk5MjQzNy8zNDU5OTc5MjEtYmE1MTkxMDItOGU0ZS00ZmEyLWFkNDctMjIwNWNiM2FjMzljLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzA1VDA1MzgyMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWQ4NTYwZTNjNGE3MzgxZmFjOTI0ZWZiMGM4NTRkOTE5YjViNjg2NzU0NjU4ZTUzMTk3ZGJmYTg5MDRkMzRkYWEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.paVO-TyBVxiBgKf3LIBwNvZ8gn_u0N2--1KB1JtKR80">
好的谢谢，我看了下，写成了msg=="hello"绷不住了，谢谢解答qwq
