### ISSUE TITLE
[Bug]: GroupNormalMessageReceived中无法正确查询到At Bot信息

### ISSUE THREAD

**Issue by ElvisChenML** [RockChinQ/QChatGPT#837]
### 部署方式

Docker部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

Linux Docker部署

### Python环境

Python 3.10.13

### QChatGPT版本

v3.2.3

### 异常情况

![c61b3b64626bf39ffa4a032bcbc81c75](https://github.com/RockChinQ/QChatGPT/assets/42546145/2a7de393-3fde-41e9-a94d-790057ce55bd)
![e25233414d641360bab29b0e1d8390be](https://github.com/RockChinQ/QChatGPT/assets/42546145/e724fa00-8d22-430b-bd9b-1a12816b50ec)
message_chain中没有At消息，无法获取Bot是否被At

**Comment by ElvisChenML** [comment]
![image](https://github.com/RockChinQ/QChatGPT/assets/42546145/4154fb9b-a7e0-413e-9e9c-c1bafc7e932c)
这个issue如果不好处理或是不处理也行，直接关闭就好了，虽然GroupNormalMessageReceived没了，但我可以在GroupMessageReceived阶段拿一下。

**Comment by RockChinQ** [comment]
最近还在帮我爸写小程序。每天处理开源项目最多花两小时。issue基本上都会处理的，只是顺序问题。

**Comment by RockChinQ** [comment]
在 #757 跟踪
