### ISSUE TITLE
[Bug]: 官方qq机器人在群聊内不能识别出管理员账号，使用管理员账号在群聊内发送安装插件命令以及update命令，机器人回复权限不足

### ISSUE THREAD

**Issue by huxiaotao0620** [RockChinQ/QChatGPT#840]
### 部署方式

Docker部署

### 消息平台适配器

qq-botpy（QQ官方API）

### 系统环境

ubuntu22.04

### Python环境

无

### QChatGPT版本

v3.2.4

### 异常情况

最近新说官方qq机器人个人账号配置沙箱环境可以选择群聊，就试了一下，聊天功能可以正常使用，但是已经在system.json内配置管理员账号后，发送管理员命令，机器人回复权限不足

**Comment by RockChinQ** [comment]
1. 管理员设置的单位是“会话”：如果设置为`person_123456`，那么用户 123456 私聊机器人时是管理员会话；如果设置 `group_654321`，那么群聊 654321 里所有消息都具有管理员权限。
2. 使用官方api时，目前只能把整个群设为管理员会话（因为qq-botpy库还没适配私聊场景）。qq-botpy 由于兼容性问题，操作的群号是映射序号，不是实际群号。可以到元数据中查看映射出的纯数字群号，也可以在发消息引起机器人响应时，查看控制台输出的会话名称。

**Comment by huxiaotao0620** [comment]
感谢解答！

**Comment by shantuzi1** [comment]
追问一下佬，我是使用个人qq，但在私聊bot时发送安装插件命令以及update命令也会提示权限不足

![Image](https://github.com/user-attachments/assets/4a009799-0009-4d89-9580-3bb25b019443)
