### ISSUE TITLE
[Feature]: Ollama平台集成-pr前沟通

### ISSUE THREAD

**Issue by canyuan0801** [RockChinQ/QChatGPT#842]
### 这是一个？

新功能

### 详细描述

参考ollama的[API文档](https://ollama.fan/reference/api/), 实现了对Ollama平台的集成:
+ 引入[ollama-python](https://github.com/ollama/ollama-python)库, 在pkg/provider/modelmgr/apis目录下新增了ollamachatcmpl.py文件,  参考`OpenAIChatCompletions`新增`OllamaChatCompletions`类, 利用`ollama-python`提供的API, 实现对话补全(非流式)的功能；
+ 在metadata/llm_models.json配置ollama支持的大模型元数据;
+ 在data/conifg/provider.json配置requester:`ollama-chat-completions`,更改model为`llm_models.json`中的模型名称, 启动程序后即可与本地ollama大模型对话.

新增4个ollama相关命令:
+ ollama_list: ollama模型列表
+ ollama_show: ollama模型详情
+ ollama_pull: ollama模型拉取
+ ollama_del: ollama模型删除

总共2个commit, 作者大大看看这些实现可以提交pr吗?

**Comment by RockChinQ** [comment]
没有问题，欢迎贡献！

命令这块儿弄成单个命令吧 !ollama，那几个命令作为此命令的子命令，实现上可以参考现有的命令实现模式。

**Comment by canyuan0801** [comment]
好，我弄成单个命令试试

**Comment by canyuan0801** [comment]
使用方法(以qwen2模型为例):
1. 本地安装好Ollama后, 然后使用命令拉取qwen2模型: `!ollama pull qwen2`;
2. 使用`!ollama`命令查看模型名称, `llm-models.json`添加如下配置:
    ```json
    {
          "name": "qwen2:latest",
          "requester": "ollama-chat-completions"
    }
    ```
3. `provider.json`添加requester:
    ```json
    "ollama-chat-completions": {
          "base-url": "http://127.0.0.1:11434",
          "args": {},
          "timeout": 1200
     }
    ```
    并将model改为`qwen2:latest`;
5. 重启程序,  与机器人对话;
