### ISSUE TITLE
[Bug？]: 使用qq官方机器人，但是 平台适配器运行出错: Cannot connect to host bots.qq.com:443 ssl:default [getaddrinfo failed]

### ISSUE THREAD

**Issue by ShanJianSoda** [RockChinQ/QChatGPT#850]
### 部署方式

手动部署

### 消息平台适配器

qq-botpy（QQ官方API）

### 系统环境

Windows 11 中国

### Python环境

Python 3.12.4

### QChatGPT版本

v3.2.4

### 异常情况

根据文档部署，配置好后`python main.py`启动

QQ机器人是注册好了的，不过没有通过审核（处于沙箱测试阶段）
![image](https://github.com/RockChinQ/QChatGPT/assets/128208553/9794bf2f-5846-4c92-84a8-4a36343ca7a7)

报错
```
G:\PycharmProjects\QChatGPT\pkg\platform\manager.py (174) - [ERROR] :
    平台适配器运行出错: Cannot connect to host bots.qq.com:443 ssl:default [getaddrinfo failed]
```

**Comment by RockChinQ** [comment]
你的主机没法正常访问 QQ API 的地址。

尝试：

1. 关闭 代理
2. 更换网络
3. 检查 DNS 是否正常
