### ISSUE TITLE
[Bug]: 艾特机器人没反应

### ISSUE THREAD

**Issue by KimiFT** [RockChinQ/QChatGPT#851]
### 部署方式

手动部署

### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 系统环境

win 11

### Python环境

python 3.10

### QChatGPT版本

v3.2.4

### 异常情况

![image](https://github.com/user-attachments/assets/5a6f30d0-1a7c-41e5-aae0-d400b6afbcfb)
![image](https://github.com/user-attachments/assets/a6bf8da5-bbd1-4836-b47f-f3163422159b)
艾特机器人后台没有任何动静，但是直接发响应前缀会回复

### 启用的插件

Webwlkr 
miHoYoVoice

**Comment by RockChinQ** [comment]
机器人控制台的输出贴一下
