### ISSUE TITLE
[Plugin]: 请求登记新插件

### ISSUE THREAD

**Issue by inkOrCloud** [RockChinQ/QChatGPT#852]
### 插件名称

Markdown2IMG

### 插件代码库地址

https://github.com/inkOrCloud/Markdown2IMG.git

### 插件简介

将markdown文本转为图片输出,适用于3.x

**Comment by RockChinQ** [comment]
感谢贡献！已添加到[插件集合](https://github.com/stars/RockChinQ/lists/qchatgpt-%E6%8F%92%E4%BB%B6)
