### ISSUE TITLE
[Bug]: 正则表达式似乎不可用？

### ISSUE THREAD

**Issue by bright141** [RockChinQ/QChatGPT#859]
### 消息平台适配器

yiri-mirai（Mirai）

### 运行环境

python3.10.9

### QChatGPT版本

3.3.0.1

### 异常情况

在default下的regexp填写正则表达式，启动也没有发生报错，但是私聊或者群聊均没有作用

### 启用的插件

Waifu

**Comment by RockChinQ** [comment]
配置文件和你的需求填上来
