### ISSUE TITLE
[BUG]报错 捕捉到未知异常:set_wakeup_fd only works in main thread,

### ISSUE THREAD

**Issue by laokeaime** [RockChinQ/QChatGPT#86]
**运行环境**
- 部署方式：
    手动部署/自动部署/Docker部署
- 系统环境：
   Ubuntu

**描述漏洞**  
什么时候发生的，mirai还是主程序，越详细越好
![W8J8_P$XVOF@9HC@%2`AVJU](https://user-images.githubusercontent.com/50368622/210730007-de12f546-80fb-4451-97c9-ec0ffbe359f0.png)

**完整报错信息**  
完整的报错信息

**Comment by RockChinQ** [comment]
**原因**
未按照文档说明**不安装**hypercorn

**解决办法**
卸载hypercorn  

```
pip uninstall hypercorn
```
