### ISSUE TITLE
关于回复模板重复

### ISSUE THREAD

**Issue by YSL-Feling** [RockChinQ/QChatGPT#87]
比如我要写一篇，某人和某人的爱情故事，如果是网页版重复了会有Regenerate response按钮，这样他会从新刷新一篇新的回复。
可是QQbot当写一篇，某人和某人的爱情故事时，他就没有Regenerate response按钮，就导致模板极其容易重复，比如
![image](https://user-images.githubusercontent.com/122018468/210762135-9b74ed46-c9a9-4417-9d58-0d415d2d1aa8.png)
但是如果是网页版就可以
![image](https://user-images.githubusercontent.com/122018468/210761502-dd8ff338-d1bb-4797-98a2-b1a1c0f39123.png)
希望大佬可以解决一下这个问题，膜拜大佬.JPG

**Comment by YSL-Feling** [comment]
> 比如我要写一篇，某人和某人的爱情故事，如果是网页版重复了会有Regenerate response按钮，这样他会从新刷新一篇新的回复。 可是QQbot当写一篇**和**的爱情故事时，他就没有Regenerate response按钮，就导致模板极其容易重复，比如 ![image](https://user-images.githubusercontent.com/122018468/210762135-9b74ed46-c9a9-4417-9d58-0d415d2d1aa8.png) 但是如果是网页版就可以 ![image](https://user-images.githubusercontent.com/122018468/210761502-dd8ff338-d1bb-4797-98a2-b1a1c0f39123.png) 希望大佬可以解决一下这个问题，膜拜大佬.JPG

**Comment by RockChinQ** [comment]
查看[wiki](https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E4%BD%BF%E7%94%A8#%E7%94%A8%E6%88%B7%E7%BA%A7%E5%88%AB%E6%8C%87%E4%BB%A4) 中的`!resend`指令
