### ISSUE TITLE
[Bug]: 处理请求时出错 query_id=10 stage=MessageProcessor : list index out of range

### ISSUE THREAD

**Issue by icelly-QAQ** [RockChinQ/QChatGPT#874]
### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 运行环境

ubuntu 24.40 LTS x86_64 python3.2 

### QChatGPT版本

v3.3.0.2

### 异常情况

以管理员身份发送命令：!model show 会报错：处理请求时出错 query_id=10 stage=MessageProcessor : list index out of range

**Comment by RockChinQ** [comment]
需要控制台输出
