### ISSUE TITLE
[Feature]: 在回复群聊信息的时候,最好同时艾特提问的人

### ISSUE THREAD

**Issue by xiaxiaomo-debug** [RockChinQ/QChatGPT#876]
### 这是一个？

现有功能优化

### 详细描述

群里多个人在提问的时候, 经常很难分清楚哪一条是回复自己的,机器人在回复的同时加一个@提问人 这样会更直观

**Comment by RockChinQ** [comment]
配置文件 data/platform.json 有个 at_sender 可以设置，详细说明看文档。
