### ISSUE TITLE
[Feature]: 优化换行

### ISSUE THREAD

**Issue by xiaxiaomo-debug** [RockChinQ/QChatGPT#878]
### 这是一个？

现有功能优化

### 详细描述

gpt回复内容里会有换行需要处理 这里特指比如智普的AI  glm-4-flash 等  openai的chatgpt 没有这类问题

![image](https://github.com/user-attachments/assets/4f610e6a-8603-4dea-b534-72ba3f18a3e3)

**Comment by xiaxiaomo-debug** [comment]
可以给您提供一个中转key 测试:  url  https://gpts.xiamoai.top   key : sk-WHts9aHbrkYyxcRR1b55D4A477994a3386F1FfA23c5dA050   model: gpt-3.5-turbo

**Comment by RockChinQ** [comment]
这是你的中转站问题，它对AI响应进行了一次转义：

<img width="495" alt="image" src="https://github.com/user-attachments/assets/95268224-c2d4-4719-972a-c01644f09fd3">

<img width="527" alt="image" src="https://github.com/user-attachments/assets/7268b5d7-6d44-4755-be41-ce0961be050b">

OpenAI 官方key：

<img width="1016" alt="image" src="https://github.com/user-attachments/assets/c22260d5-834c-45c6-95bc-e4736421b505">

<img width="533" alt="image" src="https://github.com/user-attachments/assets/ad2dcd8b-ef43-4d35-b108-e78d69112413">
