### ISSUE TITLE
[Bug]: 使用实例项目时报错没有text_massage对象

### ISSUE THREAD

**Issue by TwperBody** [RockChinQ/QChatGPT#880]
### 消息平台适配器

None

### 运行环境

windows serves 2022  x86  python 3.10.9

### QChatGPT版本

3.3.0.1

### 异常情况

示例代码来源于文档[https://qchatgpt.rockchin.top/develop/plugin-dev.html](url)
测试报错为
![ed5a6f7d39d3dff48fd4dc6d14afb050](https://github.com/user-attachments/assets/ea10a2c4-406d-4537-a580-d295070bd09b)

在handsome插件下报错
[https://github.com/RockChinQ/TheMostHandsome](url)
**_[2024-09-07 21:48:52.166] C:\Users\Administrator\Desktop\qqbot\QChatGPT\pkg\plugin\manager.py (153) - [ERROR] :
    插件 Keyword_active_review 触发事件 PersonNormalMessageReceived 时发生错误: 'message_chain'_**
都是事件监听器出了问题（应该
但是不知道如何解决
十分感谢

### 启用的插件

使用的插件有（不包括测试）
#1 Md2QQImage 
优化 bot 发送的消息，将图片链接转换为实际图片
v1.0
作者: Annalasu

#2 SillyTavernPlugin 
SillyTavernPlugin插件，用于将酒馆角色卡转写为QChatGPT人格预设的插件
v1.0
作者: the-lazy-me

#3 URLMasker 
Mask url to bypass
v0.1
作者: Antlt

**Comment by RockChinQ** [comment]
1. HelloPlugin 和文档中的实例代码的逻辑正常可用，你需要检查自己的代码是否有问题

<img width="580" alt="image" src="https://github.com/user-attachments/assets/dade5385-b7f4-4a1d-a9d4-882439bccaa1">

<img width="597" alt="image" src="https://github.com/user-attachments/assets/14bc75c0-5065-451a-8612-b929775cdf23">
