### ISSUE TITLE
[Plugin]: 请求登记新插件

### ISSUE THREAD

**Issue by Licy12138** [RockChinQ/QChatGPT#884]
### 插件名称

SendLike

### 插件代码库地址

https://github.com/Licy12138/SendLike

### 插件简介

一个给QQ名片点赞的插件！

**Comment by RockChinQ** [comment]
感谢贡献！已加入 [star集](https://github.com/stars/RockChinQ/lists/qchatgpt-%E6%8F%92%E4%BB%B6)
