### ISSUE TITLE
[Bug]: 中转站claude回复消息时，不返回role，导致出现none is not an allowed value报错

### ISSUE THREAD

**Issue by YunZLu** [RockChinQ/QChatGPT#886]
### 消息平台适配器

aiocqhttp（使用 OneBot 协议接入的）

### 运行环境

win10

### QChatGPT版本

v3.3.1.0

### 异常情况

BUG原因:
1、调用中转站api时，中转站返回如下：
{'id': 'chatcmpl-98lgI5GPYHMHFUl1pWKOY2BzRWCLJ', 'object': 'chat.completion.chunk', 'created': 0, 'choices': [{'index': 0, 'message': {'content': '你好！很高兴见到你。有什么我可以帮助你的吗?'}}], 'model': 'claude-3-5-sonnet-20240620'}

明显该中转站在返回message时未返回role值

2、在pkg/provider/modelmgr/apis/ 中各请求器未判断返回message时未返回role的情况，导致_make_msg函数中role变量为none
，故报错：

 [ERROR]:
1 validation error for Message
rolenone is not an allowed value (type=type_error.none.not_allowed)

临时解决办法：
在_make_msg函数中实例化Message 对象之前检查role是否为空:

    async def _make_msg(
        self,
        chat_completion: chat_completion.ChatCompletion,
    ) -> llm_entities.Message:
        chatcmpl_message = chat_completion.choices[0].message.dict()

        # 确保 role 字段存在且不为 None
        if 'role' not in chatcmpl_message or chatcmpl_message['role'] is None:
            chatcmpl_message['role'] = 'assistant'

        message = llm_entities.Message(**chatcmpl_message)

        return message

**Comment by RockChinQ** [comment]
最近在忙公司项目没有时间看。
欢迎提PR修改。

**Comment by YunZLu** [comment]
好的，已提交PR。
