### ISSUE TITLE
[Plugin]: 请求登记新插件

### ISSUE THREAD

**Issue by sanxianxiaohuntun** [RockChinQ/QChatGPT#913]
### 插件名称

XiaocxPlugin

### 插件代码库地址

https://github.com/sanxianxiaohuntun/XiaocxPlugin

### 插件简介

一个QChatGPT的小插件

一个小程序运行插件可以让gpt帮你写一些简单的小功能py然后丢进QChatGPT\plugins\XiaocxPlugin\data\里就可以执行小程序，里面我已经丢了几个文件了 只需要/py文件名比如 天气.py 你就/天气它就会执行这个小程序
![1](https://github.com/user-attachments/assets/cfacc80a-7c32-4faf-b556-341801e28228)
![QQ截图20241026000430](https://github.com/user-attachments/assets/37966dc5-c3e4-46f4-92e8-9ee76691ad45)

**Comment by sanxianxiaohuntun** [comment]
注意 只需把py丢进data里然后直接/py名字无需加.py后续 即可测试 完全不用重启主程序

**Comment by RockChinQ** [comment]
非常好插件，感谢贡献！已加入 [star集](https://github.com/stars/RockChinQ/lists/qchatgpt-%E6%8F%92%E4%BB%B6)
