### ISSUE TITLE
[Feature]: 希望能够兼容模型以及bug修复

### ISSUE THREAD

**Issue by sanxianxiaohuntun** [RockChinQ/QChatGPT#914]
### 这是一个？

功能优化意见以及bug

### 详细描述

功能优化为：
api的完整返回原始内容
HTTP/11" 200 None
2024-10-28 06:45:09,922 - DEBUG - 响应状态码: 200
2024-10-28 06:45:09,922 - DEBUG - 原始响应内容:
data:  {"choices":[{"delta":{"content":"\xe5\x97¨\xef\xbc\x8c\xe6\x88\x91\xe6\x98\xafN"}}]}

data:  {"choices":[{"delta":{"content":"alang"}}]}

data:  {"choices":[{"delta":{"content":"AI\xef\xbc\x8cé\x9a\x8f\xe6\x97\xb6"}}]}

data:  {"choices":[{"delta":{"content":"\xe5\x87\x86\xe5¤\x87\xe5\xa5\xbd\xe5\x9b\x9e\xe7\xad\x94"}}]}

data:  {"choices":[{"delta":{"content":"\xe4\xbd\xa0\xe7\x9a\x84é\x97\xaeé\xa2\x98\xef\xbc\x81"}}]}

2024-10-28 06:45:09,922 - ERROR - 发生错误: Expecting value: line 1 column 1 (char 0)

[2024-10-28 05:28:03.501] D:\QChatGPT\QChatGPT\pkg\pipeline\process\handlers\chat.py (123) - [ERROR] :
    对话(0)请求失败: 'str' object has no attribute 'choices'
[2024-10-28 05:28:04.476] D:\QChatGPT\QChatGPT\pkg\pipeline\controller.py (94) - [ERROR] :
    'str' object has no attribute 'choices'

QGPT的返回是这个报错

大概是data: 这个字符破坏了 整体的json格式 希望能够增加识别这个模型的读取方法，合并内容后返回打印

以及bug：

在群聊中发送图片会变成一个空白 空格 没有内容，然后部分图片在群聊中无法显示 （请求是返回了但是消息里并未出现），一些图片是提示为该消息类型暂不支持查看，可能图片是web格式

**Comment by RockChinQ** [comment]
用 [bug 模板](https://github.com/RockChinQ/QChatGPT/issues/new?assignees=&labels=bug%3F&projects=&template=bug-report.yml&title=%5BBug%5D%3A+)提，不要用 feature，并且告诉我复现步骤。
