### ISSUE TITLE
[Bug]: 疑似权限不足无法启动

### ISSUE THREAD

**Issue by catoxide** [RockChinQ/QChatGPT#918]
### 消息平台适配器

None

### 运行环境

Windows11 python3.10.14 in miniconda 主机上海

### QChatGPT版本

3.3.0 release

### 异常情况

QChat端报错：
[2024-11-11 01:23:47.861] D:\AI\qqgpt\QChatGPT-3.3.1.1\pkg\core\stages\show_notes.py (26) - [INFO] :
    您正在使用 Windows 系统，若窗口左上角显示处于”选择“模式，程序将被暂停运行，此时请右键窗口中空白区域退出选择模式。
[2024-11-11 01:23:47.862] D:\AI\qqgpt\QChatGPT-3.3.1.1\pkg\platform\manager.py (174) - [ERROR] :
    平台适配器运行出错: [WinError 10013] 以一种访问权限不允许的方式做了一个访问套接字的尝试。

Lagrange部署报错：

warn: Lagrange.OneBot.Core.Network.Service.ReverseWSService[1001]
      [ReverseWSService] Disconnect(fc651244-5c59-4326-8c70-324953c1f52c)
      System.Net.WebSockets.WebSocketException (0x80004005): The server returned status code '500' when status code '101' was expected.
         at System.Net.WebSockets.WebSocketHandle.ValidateResponse(HttpResponseMessage response
, String secValue)
         at System.Net.WebSockets.WebSocketHandle.ConnectAsync(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken, ClientWebSocketOptions options)
         at System.Net.WebSockets.ClientWebSocket.ConnectAsyncCore(Uri uri, HttpMessageInvoker invoker, CancellationToken cancellationToken)
         at Lagrange.OneBot.Core.Network.Service.ReverseWSService.ExecuteAsync(CancellationToken stoppingToken)

Qchat报错并停止，lagrange重复上述报错
尝试了一些办法无法解决，搜索得知是权限相关

### 启用的插件

/

**Comment by RockChinQ** [comment]
看看你platform.json咋配置的

**Comment by catoxide** [comment]
> 看看你platform.json咋配置的

{
    "platform-adapters": [
        {
            "adapter": "yiri-mirai",
            "enable": false,
            "host": "127.0.0.1",
            "port": 8080,
            "verifyKey": "yirimirai",
            "qq": 123456789
        },
        {
            "adapter": "nakuru",
            "enable": false,
            "host": "127.0.0.1",
            "ws_port": 8080,
            "http_port": 5700,
            "token": ""
        },
        {
            "adapter": "aiocqhttp",
            "enable": true,
            "host": "0.0.0.0",
            "port": 8080,
            "access-token": ""
        },
        {
            "adapter": "qq-botpy",
            "enable": false,
            "appid": "",
            "secret": "",
            "intents": [
                "public_guild_messages",
                "direct_message"
            ]
        }
    ],
    "track-function-calls": true,
    "quote-origin": false,
    "at-sender": false,
    "force-delay": [0, 0],
    "long-text-process": {
        "threshold": 256,
        "strategy": "forward",
        "font-path": ""
    },
    "hide-exception-info": true
}

好像没怎么动 我就把enable改成了true好像

**Comment by RockChinQ** [comment]
你的 8080 端口被其他程序占用了，https://www.cnblogs.com/ck-zscs/p/16053551.html 。把你 aiocqhttp 那个配置的端口改一下，换成 8081 8082 之类的，同时 lagrange 配置文件的端口也改一下。

**Comment by catoxide** [comment]
> 你的 8080 端口被其他程序占用了，https://www.cnblogs.com/ck-zscs/p/16053551.html 。把你 aiocqhttp 那个配置的端口改一下，换成 8081 8082 之类的，同时 lagrange 配置文件的端口也改一下。

啊啊 是的是的 能用了（）最近在干别的所以忘记回了（）感谢（）
