### ISSUE TITLE
机器人在群里不说话

### ISSUE THREAD

**Issue by izhangguapi** [RockChinQ/QChatGPT#94]
![image](https://user-images.githubusercontent.com/33612298/211314741-b55a1193-f82b-49e6-bab0-ccabfd5813ec.png)

**Comment by RockChinQ** [comment]
已修复，请更新，更新方法见 https://github.com/RockChinQ/QChatGPT/wiki/%E5%8A%9F%E8%83%BD%E5%B8%B8%E8%A7%81%E9%97%AE%E9%A2%98#-%E5%A6%82%E4%BD%95%E6%9B%B4%E6%96%B0%E4%BB%A3%E7%A0%81%E5%88%B0%E6%9C%80%E6%96%B0%E7%89%88%E6%9C%AC

**Comment by izhangguapi** [comment]
非常感谢，之前是直接下载的zip，用git拉一遍就好了
