### ISSUE TITLE
机器人当面一套背后一套是什么情况

### ISSUE THREAD

**Issue by izhangguapi** [RockChinQ/QChatGPT#95]
在群里询问请用java写一个归并排序
![群](https://user-images.githubusercontent.com/33612298/211325340-4c6407c3-8a4e-4cd0-bbb2-dfd7d8c10a55.png)

私聊询问请用java写一个归并排序
![私聊](https://user-images.githubusercontent.com/33612298/211325488-e6a20a72-b3ff-41b7-8c70-41e9ab56b69b.png)

**Comment by izhangguapi** [comment]
运行日志
![日志](https://user-images.githubusercontent.com/33612298/211325889-70daa070-efaf-41ef-a207-995ca79ebf75.png)

**Comment by RockChinQ** [comment]
OpenAI模型生成的内容具有随机性，具体使用方式请查看openai官网的文档，以及本仓库wiki
