### ISSUE TITLE
[提示] 同一主机内机器人多开的方式

### ISSUE THREAD

**Issue by RockChinQ** [RockChinQ/QChatGPT#98]
同主机多mirai、多yirimirai、多QChatGPT机器人解决方案  
欢迎各位补充

**Comment by q123458384** [comment]
目前可以用多开多个docker容器的方式

**Comment by Ctrini** [comment]
可以更改mirai中的setting.yml端口，和Qchatgpt中的config.py端口，进行多开机器人。

**Comment by Fatima-meow** [comment]
在mirai中使用autoLogin add <账号> <密码>(去掉<>)就能实现多个账号登录，只要Bot不储存在同一个文件夹应该就没问题

**Comment by RockChinQ** [comment]
以上是 2.x 版本的方案，可能已经过时。
